<DOC>
<DOCID>LN-20021113043</DOCID>
<DOCNO>LN-20021113043</DOCNO>
<DATE>11/13/02</DATE>
<TITLE>
1	Desetitisíce	desetitisíc	NNIS2-----A----	5	Obj
2	lidí	člověk	NNMP2-----A----	1	Atr
3	by	být	Vc-------------	4	AuxV
4	mohly	moci_^(mít_možnost_[něco_dělat])	VpTP---XR-AA---	0	Pred
5	bydlet	bydlet	Vf--------A----	4	Obj
6	na	na-1	RR--6----------	5	AuxP
7	ostrovech	ostrov	NNIP6-----A----	6	Adv
8	,	,	Z:-------------	12	AuxX
9	jejichž	jenž_^(který...[ve_vedl._větě])	P1XXXXP3-------	11	Atr
10	případnou	případný	AAFS4----1A----	11	Atr
11	stavbu	stavba	NNFS4-----A----	12	Sb
12	má	mít	VB-S---3P-AA---	7	Atr
13	prozkoumat	prozkoumat_:W	Vf--------A----	12	Obj
14	vládní	vládní	AAFS4----1A----	15	Atr
15	komise	komise	NNFS2-----A----	13	Sb

</TITLE>
<TEXT>
1	Miliardu	miliarda`1000000000	NNFS4-----A----	3	Obj
2	dolarů	dolar_;b	NNIP2-----A----	1	Atr
3	má	mít	VB-S---3P-AA---	0	Pred
4	stát	stát-1_^(státní_útvar)	NNIS4-----A----	3	Sb
5	jeden	jeden`1	ClIS4----------	6	Atr
6	ostrov	ostrov	NNIS4-----A----	3	Obj
7	o	o-1	RR--6----------	6	AuxP
8	velikosti	velikost_^(*3ý)	NNFS6-----A----	7	Obj
9	tří	tři`3	ClXP2----------	11	Atr
10	čtverečních	čtvereční	AAIP2----1A----	11	Atr
11	kilometrů	kilometr	NNIP2-----A----	8	Atr
12	.	.	Z:-------------	0	AuxK

1	Jednotlivé	jednotlivý	AAIP1----1A----	2	Atr
2	ostrovy	ostrov	NNIP1-----A----	7	Sb
3	u	u-1	RR--2----------	2	AuxP
4	izraelského	izraelský	AANS2----1A----	5	Atr
5	pobřeží	pobřeží	NNNS2-----A----	3	Atr
6	by	být	Vc-------------	7	AuxV
7	měly	mít	VpTP---XR-AA---	0	Pred
8	být	být	Vf--------A----	9	AuxV
9	pospojovány	pospojovat_:W	VsTP---XX-AP---	7	Obj
10	podmořskými	podmořský	AAIP7----1A----	11	Atr
11	tunely	tunel	NNIP7-----A----	9	Adv
12	.	.	Z:-------------	0	AuxK

1	TEL	Tel-1_;G_,t_^(Tel_Aviv)	AAXXX----1A----	2	Atr
2	AVIV	Aviv_;G	NNIS1-----A----	3	Sb
3	-	-	Z:-------------	5	Apos
4	Izraelská	izraelský	AAFS1----1A----	5	Atr
5	vláda	vláda	NNFS1-----A----	6	Sb
6	rozhodla	rozhodnout_:W	VpQW---XR-AA--1	0	Pred
7	o	o-1	RR--6----------	6	AuxP
8	ustavení	ustavení_^(*3it)	NNNS6-----A----	7	Obj
9	komise	komise	NNFS2-----A----	8	Atr
10	,	,	Z:-------------	12	AuxX
11	která	který	P4FS1----------	12	Sb
12	má	mít	VB-S---3P-AA---	9	Atr
13	posoudit	posoudit_:W	Vf--------A----	12	Obj
14	plán	plán	NNIS4-----A----	13	Obj
15	na	na-1	RR--6----------	14	AuxP
16	vybudování	vybudování_^(*3at)	NNNS6-----A----	15	Atr
17	umělých	umělý	AAIP2----1A----	18	Atr
18	ostrovů	ostrov	NNIP2-----A----	16	Atr
19	podél	podél	RR--2----------	18	AuxP
20	pobřeží	pobřeží	NNNS2-----A----	19	Atr
21	Středozemního	středozemní	AANS2----1A----	22	Atr
22	moře	moře	NNNS2-----A----	20	Atr
23	.	.	Z:-------------	0	AuxK

1	O	o-1	RR--6----------	6	AuxP
2	tomto	tento	PDZS6----------	4	Atr
3	mnohamiliardovém	mnohomiliardový	AAIS6----1A----	4	Atr
4	projektu	projekt	NNIS6-----A----	1	Obj
5	se	se_^(zvr._zájmeno/částice)	P7-X4----------	6	AuxR
6	hovoří	hovořit_:T	VB-S---3P-AA---	0	Pred
7	už	už	Db-------------	9	AuxZ
8	přibližně	přibližně_^(*1ý)	Dg-------1A----	9	AuxZ
9	deset	deset`10	Cn-S4----------	6	Sb
10	let	rok	NNNP2-----A----	9	Atr
11	.	.	Z:-------------	0	AuxK

1	Ustavení	ustavení_^(*3it)	NNNS1-----A----	3	Sb
2	komise	komise	NNFS2-----A----	1	Atr
3	je	být	VB-S---3P-AA---	0	Pred
4	zatím	zatím	Db-------------	3	Adv
5	posledním	poslední	AAIS7----1A----	6	Atr
6	krokem	krok	NNIS7-----A----	3	Pnom
7	,	,	Z:-------------	9	AuxX
8	který	který	P4YS1----------	9	Sb
9	svědčí	svědčit_:T	VB-S---3P-AA---	6	Atr
10	o	o-1	RR--6----------	9	AuxP
11	tom	ten	PDZS6----------	10	Obj
12	,	,	Z:-------------	13	AuxX
13	že	že	J,-------------	11	AuxC
14	izraelská	izraelský	AAFS1----1A----	15	Atr
15	vláda	vláda	NNFS1-----A----	20	Sb
16	o	o-1	RR--6----------	20	AuxP
17	vybudování	vybudování_^(*3at)	NNNS6-----A----	16	Atr
18	ostrovů	ostrov	NNIP2-----A----	17	Atr
19	vážně	vážně_^(*1ý)	Dg-------1A----	20	Adv
20	uvažuje	uvažovat_:T	VB-S---3P-AA---	13	Obj
21	.	.	Z:-------------	0	AuxK

1	Nejprve	nejprve	Db-------------	3	Adv
2	by	být	Vc-------------	3	AuxV
3	měly	mít	VpTP---XR-AA---	0	Pred
4	být	být	Vf--------A----	8	AuxV
5	podle	podle-2	RR--2----------	8	AuxP
6	izraelských	izraelský	AANP2----1A----	7	Atr
7	médií	médium	NNNP2-----A----	5	Adv
8	vybudovány	vybudovat_:W	VsTP---XX-AP---	3	Obj
9	tři	tři`3	ClXP1----------	10	Atr
10	ostrovy	ostrov	NNIP1-----A----	8	Sb
11	.	.	Z:-------------	0	AuxK

1	Zřejmě	zřejmě_^(*1ý)	Dg-------1A----	3	AuxZ
2	u	u-1	RR--2----------	0	AuxP
3	měst	město	NNNP2-----A----	2	Adv
4	Tel	Tel-1_;G_,t_^(Tel_Aviv)	AAXXX----1A----	8	Atr
5	Aviv	Aviv_;G	NNIS1-----A----	4	Atr
6	,	,	Z:-------------	8	AuxX
7	Haifa	Haifa_;G	NNFS1-----A----	8	Sb
8	a	a-1	J^-------------	3	Coord
9	Herzlija	Herzlija	NNFS1-----A----	10	Sb
10	či	či	J^-------------	8	Coord
11	Netanja	Netanj	NNMS1-----A----	10	Sb
12	.	.	Z:-------------	0	AuxK

1	Měly	mít	VpTP---XR-AA---	0	Pred
2	by	být	Vc-------------	1	AuxV
3	být	být	Vf--------A----	4	AuxV
4	určeny	určit	VsTP---XX-AP---	1	Obj
5	jak	jak-2	J,-------------	9	AuxY
6	pro	pro-1	RR--4----------	9	AuxP
7	turisty	turista	NNMP4-----A----	6	ExD
8	,	,	Z:-------------	9	AuxX
9	tak	tak-3	Db-------------	4	Coord
10	pro	pro-1	RR--4----------	9	AuxP
11	stálé	stálý	AAMP4----1A----	12	Atr
12	obyvatele	obyvatel	NNMP4-----A----	13	Obj
13	a	a-1	J^-------------	10	Coord
14	kanceláře	kancelář	NNFP4-----A----	13	Obj
15	.	.	Z:-------------	0	AuxK

1	Pospojovány	pospojovat_:W	VsTP---XX-AP---	3	Obj
2	by	být	Vc-------------	3	AuxV
3	měly	mít	VpTP---XR-AA---	0	Pred
4	být	být	Vf--------A----	1	AuxV
5	podmořskými	podmořský	AAIP7----1A----	6	Atr
6	tunely	tunel	NNIP7-----A----	4	Pnom
7	a	a-1	J^-------------	3	Coord
8	silnicí	silnice	NNFP2-----A---1	7	Atr
9	s	s-1	RR--7----------	8	AuxP
10	pobřežím	pobřeží	NNNS7-----A----	9	Atr
11	.	.	Z:-------------	0	AuxK

1	V	v-1	RR--6----------	4	AuxP
2	blízkosti	blízkost_^(*3ý)	NNFS6-----A----	1	Adv
3	by	být	Vc-------------	4	AuxV
4	mělo	mít	VpNS---XR-AA---	0	Pred
5	být	být	Vf--------A----	6	AuxV
6	vybudováno	vybudovat_:W	VsNS---XX-AP---	4	Obj
7	letiště	letiště	NNNS1-----A----	4	Sb
8	.	.	Z:-------------	0	AuxK

1	Uvažuje	uvažovat_:T	VB-S---3P-AA---	0	Pred
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	1	AuxR
3	i	i-1	J^-------------	5	AuxZ
4	o	o-1	RR--6----------	1	AuxP
5	tom	ten	PDZS6----------	4	Obj
6	,	,	Z:-------------	7	AuxX
7	že	že	J,-------------	5	AuxC
8	by	být	Vc-------------	14	AuxV
9	se	se_^(zvr._zájmeno/částice)	P7-X4----------	14	AuxT
10	na	na-1	RR--6----------	14	AuxP
11	jednom	jeden`1	ClZS6----------	10	Adv
12	z	z-1	RR--2----------	11	AuxP
13	ostrovů	ostrov	NNIP2-----A----	12	Atr
14	postavilo	postavit_:W	VpNS---XR-AA---	7	Obj
15	letiště	letiště	NNNS4-----A----	14	Obj
16	.	.	Z:-------------	0	AuxK

1	Ekologické	ekologický	AAFP1----1A----	2	Atr
2	organizace	organizace	NNFP1-----A----	5	Sb
3	tento	tento	PDIS4----------	4	Atr
4	plán	plán	NNIS4-----A----	5	Obj
5	odmítají	odmítat_:T	VB-P---3P-AA---	0	Pred
6	s	s-1	RR--7----------	5	AuxP
7	tím	ten	PDZS7----------	6	Obj
8	,	,	Z:-------------	9	AuxX
9	že	že	J,-------------	7	AuxC
10	vybudování	vybudování_^(*3at)	NNNS1-----A----	12	Sb
11	ostrovů	ostrov	NNIP2-----A----	10	Atr
12	poničí	poničit_:W	VB-P---3P-AA---	15	Pred
13	izraelské	izraelský	AAFP4----1A----	14	Atr
14	pláže	pláž	NNFP4-----A----	12	Obj
15	a	a-1	J^-------------	9	Coord
16	naruší	narušit_:W	VB-S---3P-AA---	15	Pred
17	výhled	výhled	NNIS4-----A----	16	Obj
18	na	na-1	RR--6----------	17	AuxP
19	moře	mora	NNFS6-----A----	18	Atr
20	.	.	Z:-------------	0	AuxK

1	Navíc	navíc	Db-------------	5	Adv
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	5	AuxT
3	podle	podle-2	RR--2----------	5	AuxP
4	nich	on-1	P5XP2--3-------	3	Adv
5	zvýší	zvýšit_:W	VB-S---3P-AA---	0	Pred
6	znečištění	znečištění_^(*5stit)	NNNS1-----A----	5	Sb
7	v	v-1	RR--6----------	5	AuxP
8	oblasti	oblast	NNFS6-----A----	7	Atr
9	.	.	Z:-------------	0	AuxK

1	Řada	řada_^(linka,zástup,pořadí,...)	NNFS1-----A----	5	Sb
2	politiků	politik	NNMP2-----A----	3	Atr
3	a	a-1	J^-------------	1	Coord
4	obchodníků	obchodník	NNMP2-----A----	3	Atr
5	je	být	VB-S---3P-AA---	10	Pred
6	naopak	naopak	Db-------------	5	Adv
7	pro	pro-1	RR--4----------	5	AuxP
8	tento	tento	PDIS4----------	9	Atr
9	projekt	projekt	NNIS4-----A----	7	Adv
10	a	a-1	J^-------------	0	Coord
11	tvrdí	tvrdit_:T	VB-S---3P-AA---	10	Pred
12	,	,	Z:-------------	13	AuxX
13	že	že	J,-------------	11	AuxC
14	do	do-1	RR--2----------	19	AuxP
15	budoucna	budoucno	NNNS2-----A----	14	Adv
16	kvůli	kvůli	RR--3----------	15	AuxP
17	nedostatku	nedostatek	NNIS3-----A----	16	Atr
18	místa	místo-1_^(fyzické_umístění)	NNNS2-----A----	17	Atr
19	nezbude	zbýt	VB-S---3P-NA--1	13	Obj
20	Izraeli	Izrael_;G	NNIS6-----A----	19	Sb
21	stejně	stejně_^(*1ý)	Dg-------1A----	26	Adv
22	nic	nic	PW--4----------	19	Sb
23	jiného	jiný	AANS2----1A----	22	Atr
24	než	než-2	J,-------------	23	AuxC
25	se	se_^(zvr._zájmeno/částice)	P7-X4----------	26	AuxT
26	rozšiřovat	rozšiřovat_:T	Vf--------A----	24	Adv
27	do	do-1	RR--2----------	26	AuxP
28	moře	moře	NNNS2-----A----	27	Adv
29	.	.	Z:-------------	0	AuxK

</TEXT>
<HEADING>
1	Uskutečnitelný	uskutečnitelný_^(*4)	AAIS1----1A----	2	Atr
2	projekt	projekt	NNIS1-----A----	0	ExD
3	?	?	Z:-------------	0	AuxK

</HEADING>
<TEXT>
1	Pokud	pokud	J,-------------	7	AuxC
2	by	být	Vc-------------	3	AuxV
3	byl	být	VpYS---XR-AA---	5	AuxV
4	projekt	projekt	NNIS1-----A----	5	Sb
5	dokončen	dokončit	VsYS---XX-AP---	1	Adv
6	,	,	Z:-------------	1	AuxX
7	znamenalo	znamenat_:T	VpNS---XR-AA---	0	Pred
8	by	být	Vc-------------	7	AuxV
9	to	ten	PDNS1----------	7	Sb
10	vytvoření	vytvoření_^(*3it)	NNNS1-----A----	7	Sb
11	přibližně	přibližně_^(*1ý)	Dg-------1A----	13	Adv
12	desetitisíce	desetitisíc	NNIP1-----A----	7	Obj
13	nových	nový	AANP2----1A----	15	Atr
14	pracovních	pracovní	AANP2----1A----	15	Atr
15	míst	místo-1_^(fyzické_umístění)	NNNP2-----A----	12	Atr
16	.	.	Z:-------------	0	AuxK

1	Na	na-1	RR--6----------	10	AuxP
2	každém	každý	AAIS6----1A----	3	Atr
3	ostrově	ostrov	NNIS6-----A----	1	Adv
4	o	o-1	RR--6----------	3	AuxP
5	velikosti	velikost_^(*3ý)	NNFS6-----A----	4	Obj
6	tři	tři`3	ClXP4----------	8	Atr
7	čtvereční	čtvereční	AAIP4----1A----	8	Atr
8	kilometry	kilometr	NNIP4-----A----	10	Sb
9	by	být	Vc-------------	10	AuxV
10	mohly	moci_^(mít_možnost_[něco_dělat])	VpTP---XR-AA---	17	Pred
11	být	být	Vf--------A----	10	Obj
12	byty	byt_^(místo_k_bydlení)	NNIP4-----A----	10	Sb
13	pro	pro-1	RR--4----------	12	AuxP
14	dvacet	dvacet`20	Cn-S4----------	13	Adv
15	tisíc	tisíc-1`1000	ClXS2----------	14	Atr
16	obyvatel	obyvatel	NNMS1-----A----	15	Atr
17	a	a-1	J^-------------	0	Coord
18	pro	pro-1	RR--4----------	17	AuxP
19	stejný	stejný	AAIS4----1A----	20	Atr
20	počet	počet	NNIS4-----A----	18	ExD
21	turistů	turista	NNMP2-----A----	24	Atr
22	,	,	Z:-------------	24	AuxX
23	obchodníků	obchodník	NNMP2-----A----	24	Atr
24	a	a-1	J^-------------	20	Coord
25	dalších	další	AAMP2----1A----	24	Atr
26	.	.	Z:-------------	0	AuxK

1	Každý	každý	AAIS1----1A----	2	Atr
2	ostrov	ostrov	NNIS1-----A----	4	Sb
3	by	být	Vc-------------	4	AuxV
4	měl	mít	VpYS---XR-AA---	8	Pred
5	stát	stát-2_^(něco_se_přihodilo)	Vf--------A----	4	Obj
6	miliardu	miliarda`1000000000	NNFS4-----A----	5	Obj
7	dolarů	dolar_;b	NNIP2-----A----	6	Atr
8	a	a-1	J^-------------	0	Coord
9	měl	mít	VpYS---XR-AA---	8	Pred
10	by	být	Vc-------------	9	AuxV
11	být	být	Vf--------A----	12	AuxV
12	financován	financovat_:T	VsYS---XX-AP---	9	Obj
13	ze	z-1	RV--2----------	12	AuxP
14	soukromých	soukromý	AAIP2----1A----	15	Atr
15	zdrojů	zdroj	NNIP2-----A----	13	Adv
16	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	2	AuxG
2	Jsem	být	VB-S---1P-AA---	8	AuxV
3	pro	pro-1	RR--4----------	2	AuxP
4	vybudování	vybudování_^(*3at)	NNNS4-----A----	3	Adv
5	ostrovů	ostrov	NNIP2-----A----	4	Atr
6	,	,	Z:-------------	2	AuxX
7	"	"	Z:-------------	2	AuxG
8	řekl	říci_:W	VpYS---XR-AA---	0	Pred
9	nynější	nynější	AAMS1----1A----	11	Atr
10	izraelský	izraelský	AAMS1----1A----	11	Atr
11	premiér	premiér	NNMS1-----A----	13	Atr
12	Ariel	Ariel_;R	NNIS1-----A----	13	Atr
13	Šaron	Šaron	NNMS1-----A----	8	Sb
14	už	už	Db-------------	17	AuxZ
15	před	před-1	RR--7----------	8	AuxP
16	několika	několik	Ca--7----------	17	Atr
17	lety	rok	NNNP7-----A----	15	Adv
18	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	2	AuxG
2	Chtěl	chtít	VpYS---XR-AA---	0	Pred
3	bych	být	Vc-S---1-------	2	AuxV
4	to	ten	PDNS4----------	5	Obj
5	uvést	uvést	Vf--------A----	2	Obj
6	do	do-1	RR--2----------	5	AuxP
7	praxe	praxe	NNFS2-----A----	6	Adv
8	.	.	Z:-------------	0	AuxK

1	Může	moci_^(mít_možnost_[něco_dělat])	VB-S---3P-AA---	0	Pred
2	to	ten	PDNS1----------	1	Sb
3	změnit	změnit_:W	Vf--------A----	1	Obj
4	kvalitu	kvalita	NNFS4-----A----	3	Obj
5	života	život	NNIS2-----A----	4	Atr
6	těch	ten	PDXP2----------	5	Atr
7	,	,	Z:-------------	9	AuxX
8	kteří	který	P4MP1----------	9	Sb
9	žijí	žít	VB-P---3P-AA--1	6	Atr
10	podél	podél	RR--2----------	9	AuxP
11	pobřeží	pobřeží	NNNS2-----A----	10	Adv
12	Izraele	Izrael_;G	NNIS2-----A----	11	Atr
13	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	2	AuxG
2	Není	být	VB-S---3P-NA---	3	Pred
3	proto	proto-1_^(proto;_a_proto,_ale_proto,...)	J^-------------	0	Coord
4	divu	div-1	NNIS2-----A----	2	Sb
5	,	,	Z:-------------	6	AuxX
6	že	že	J,-------------	2	AuxC
7	odcházející	odcházející_^(*4t)	AGFS1-----A----	9	Atr
8	Šaronova	Šaronův_^(*2)	AUFS1M---------	9	Atr
9	vláda	vláda	NNFS1-----A----	11	Sb
10	ještě	ještě	Db-------------	11	Adv
11	ustavila	ustavit_:W	VpQW---XR-AA---	6	Obj
12	vládní	vládní	AAFS4----1A----	13	Atr
13	komisi	komise	NNFS4-----A----	11	Obj
14	,	,	Z:-------------	19	AuxX
15	která	který	P4FS1----------	19	Sb
16	se	se_^(zvr._zájmeno/částice)	P7-X4----------	19	AuxT
17	bude	být	VB-S---3F-AA---	19	AuxV
18	problémem	problém	NNIS7-----A----	19	Obj
19	zabývat	zabývat_:T	Vf--------A----	13	Atr
20	.	.	Z:-------------	0	AuxK

1	Mluvčí	mluvčí	NNMS1-----A----	13	Sb
2	izraelského	izraelský	AAIS2----1A----	4	Atr
3	Technologického	technologický	AAIS2----1A----	4	Atr
4	ústavu	ústav	NNIS2-----A----	1	Atr
5	,	,	Z:-------------	7	AuxX
6	který	který	P4YS1----------	7	Sb
7	má	mít	VB-S---3P-AA---	4	Atr
8	na	na-1	RR--6----------	7	AuxP
9	starosti	starost	NNFS6-----A----	8	Obj
10	výzkum	výzkum	NNIS1-----A----	7	Obj
11	projektu	projekt	NNIS2-----A----	10	Atr
12	,	,	Z:-------------	7	AuxX
13	řekl	říci_:W	VpYS---XR-AA---	0	Pred
14	BBC	BBC_:B_;K	NNFXX-----A---8	13	Sb
15	,	,	Z:-------------	16	AuxX
16	že	že	J,-------------	13	AuxC
17	ostrovy	ostrov	NNIP1-----A----	18	Sb
18	budou	být	VB-P---3F-AA---	16	Obj
19	alternativou	alternativa	NNFS7-----A----	18	Pnom
20	k	k-1	RR--3----------	19	AuxP
21	výstavbě	výstavba	NNFS3-----A----	20	Atr
22	v	v-1	RR--6----------	21	AuxP
23	poušti	poušť	NNFS6-----A----	22	Atr
24	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	4	AuxG
2	Části	část	NNFS2-----A----	4	Sb
3	Izraele	Izrael_;G	NNIS2-----A----	2	Atr
4	nemohou	moci_^(mít_možnost_[něco_dělat])	VB-P---3P-NA--1	19	Obj
5	být	být	Vf--------A----	6	AuxV
6	využity	využít	VsTP---XX-AP---	4	Obj
7	pro	pro-1	RR--4----------	6	AuxP
8	stavební	stavební	AAIP4----1A----	9	Atr
9	ani	ani	J^-------------	11	Coord
10	turistické	turistický	AAIP4----1A----	9	Atr
11	účely	účel	NNIP4-----A----	7	Adv
12	kvůli	kvůli	RR--3----------	11	AuxP
13	písečnému	písečný	AAIS3----1A----	14	Atr
14	a	a-1	J^-------------	16	Coord
15	kamenitému	kamenitý	AAIS3----1A----	14	Atr
16	podloží	podloží	NNNS1-----A----	12	Atr
17	,	,	Z:-------------	6	AuxX
18	"	"	Z:-------------	6	AuxG
19	tvrdí	tvrdit_:T	VB-S---3P-AA---	0	Pred
20	Tony	Tony_;Y	NNMS1-----A----	21	Atr
21	Bernstein	Bernstein_;S	NNMS1-----A----	19	Sb
22	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	10	AuxG
2	Do	do-1	RR--2----------	6	AuxP
3	budoucna	budoucno	NNNS2-----A----	2	Atr
4	nás	já	PP-P4--1-------	10	Obj
5	to	ten	PDNS1----------	6	Sb
6	bude	být	VB-S---3F-AA---	10	AuxV
7	více	hodně	Dg-------2A----	8	Adv
8	a	a-1	J^-------------	10	Coord
9	více	hodně	Dg-------2A----	8	Adv
10	limitovat	limitovat_:T	Vf--------A----	0	Pred
11	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	4	AuxG
2	Podle	podle-2	RR--2----------	4	AuxP
3	něj	on-1	P5ZS2--3-------	2	Adv
4	je	být	VB-S---3P-AA---	11	Pred
5	vybudování	vybudování_^(*3at)	NNNS1-----A----	4	Sb
6	umělých	umělý	AAIP2----1A----	7	Atr
7	ostrovů	ostrov	NNIP2-----A----	5	Atr
8	velice	velice	Db-------------	9	Adv
9	složité	složitý	AAIP1----1A----	4	Pnom
10	,	,	Z:-------------	11	AuxX
11	nicméně	nicméně	J^-------------	0	Coord
12	uskutečnitelné	uskutečnitelný_^(*4)	AAIP1----1A----	4	Pnom
13	.	.	Z:-------------	0	AuxK

1	Zvláště	zvláště	Db-------------	3	Adv
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	3	AuxT
3	objevily	objevit_:W	VpTP---XR-AA---	0	Pred
4	obavy	obava	NNFP1-----A----	3	Sb
5	z	z-1	RR--2----------	4	AuxP
6	toho	ten	PDZS2----------	5	Atr
7	,	,	Z:-------------	8	AuxX
8	že	že	J,-------------	6	AuxC
9	by	být	Vc-------------	12	AuxV
10	se	se_^(zvr._zájmeno/částice)	P7-X4----------	13	AuxT
11	ostrovy	ostrov	NNIP1-----A----	12	Sb
12	mohly	moci_^(mít_možnost_[něco_dělat])	VpTP---XR-AA---	8	Obj
13	stát	stát-2_^(něco_se_přihodilo)	Vf--------A----	12	Obj
14	vhodným	vhodný	AAIS7----1A----	15	Atr
15	a	a-1	J^-------------	17	Coord
16	snadným	snadný	AAIS7----1A----	15	Atr
17	cílem	cíl	NNIS7-----A----	13	Obj
18	pro	pro-1	RR--4----------	17	AuxP
19	teroristy	terorista	NNMP4-----A----	18	Atr
20	.	.	Z:-------------	0	AuxK

1	Bernstein	Bernstein_;S	NNMS1-----A----	2	Sb
2	je	být	VB-S---3P-AA---	3	Pred
3	však	však	J^-------------	0	Coord
4	přesvědčen	přesvědčit_:W	VsYS---XX-AP---	2	Pnom
5	,	,	Z:-------------	6	AuxX
6	že	že	J,-------------	4	AuxC
7	se	se_^(zvr._zájmeno/částice)	P7-X4----------	8	AuxR
8	dají	dát	VB-P---3P-AA---	6	Obj
9	přijmout	přijmout-2	Vf--------A----	8	Obj
10	taková	takový	PDNP4----------	12	Atr
11	bezpečnostní	bezpečnostní	AANP4----1A----	12	Atr
12	opatření	opatření_^(*3it)	NNNP4-----A----	9	Obj
13	,	,	Z:-------------	14	AuxX
14	aby	aby	J,-------------	8	AuxC
15	lidem	člověk	NNMP3-----A----	22	Obj
16	,	,	Z:-------------	18	AuxX
17	kteří	který	P4MP1----------	22	Sb
18	budou	být	VB-P---3F-AA---	15	Atr
19	na	na-1	RR--6----------	18	AuxP
20	ostrovech	ostrov	NNIP6-----A----	19	Adv
21	,	,	Z:-------------	8	AuxX
22	nehrozilo	hrozit_:T	VpNS---XR-NA---	14	Obj
23	příliš	příliš	Db-------------	24	Adv
24	velké	velký	AANS1----1A----	25	Atr
25	nebezpečí	nebezpečí	NNNS1-----A----	22	Sb
26	.	.	Z:-------------	0	AuxK

1	Vládou	vláda	NNFS7-----A----	2	Obj
2	ustavená	ustavený_^(*3it)	AAFS1----1A----	3	Atr
3	komise	komise	NNFS1-----A----	5	Sb
4	by	být	Vc-------------	5	AuxV
5	měla	mít	VpQW---XR-AA---	0	Pred
6	projekt	projekt	NNIS4-----A----	11	Obj
7	v	v-1	RR--6----------	11	AuxP
8	příštích	příští	AAIP6----1A----	10	Atr
9	třech	tři`3	ClXP6----------	10	Atr
10	měsících	měsíc	NNIP6-----A----	7	Atr
11	posuzovat	posuzovat_:T	Vf--------A----	5	Obj
12	.	.	Z:-------------	0	AuxK

1	Poté	poté	Db-------------	3	Adv
2	by	být	Vc-------------	3	AuxV
3	mělo	mít	VpNS---XR-AA---	0	Pred
4	být	být	Vf--------A----	5	AuxV
5	vydáno	vydat-1_:W_^(emitovat:_cenné_papíry,_knihu,_zvuk,...)	VsNS---XX-AP---	3	Obj
6	závěrečné	závěrečný	AANS1----1A----	7	Atr
7	rozhodnutí	rozhodnutí_^(*3out)	NNNS1-----A----	3	Sb
8	.	.	Z:-------------	0	AuxK

1	Pokud	pokud	J,-------------	6	AuxC
2	bude	být	VB-S---3F-AA---	1	Adv
3	rozhodnutí	rozhodnutí_^(*3out)	NNNS1-----A----	2	Sb
4	kladné	kladný	AANS1----1A----	3	Atr
5	,	,	Z:-------------	1	AuxX
6	mohla	moci_^(mít_možnost_[něco_dělat])	VpQW---XR-AA---	0	Pred
7	by	být	Vc-------------	6	AuxV
8	podle	podle-2	RR--2----------	10	AuxP
9	expertů	expert	NNMP2-----A----	8	Adv
10	začít	začít-1	Vf--------A----	6	Obj
11	výstavba	výstavba	NNFS1-----A----	6	Sb
12	prvního	první	CrIS2----------	13	Atr
13	ostrova	ostrov	NNIS2-----A----	11	Atr
14	do	do-1	RR--2----------	11	AuxP
15	tří	tři`3	ClXP2----------	16	Atr
16	let	rok	NNNP2-----A----	14	Atr
17	.	.	Z:-------------	0	AuxK

1	Pokud	pokud	J,-------------	7	AuxC
2	by	být	Vc-------------	3	AuxV
3	byl	být	VpYS---XR-AA---	5	AuxV
4	projekt	projekt	NNIS1-----A----	5	Sb
5	dokončen	dokončit	VsYS---XX-AP---	1	Adv
6	,	,	Z:-------------	1	AuxX
7	znamenalo	znamenat_:T	VpNS---XR-AA---	0	Pred
8	by	být	Vc-------------	7	AuxV
9	to	ten	PDNS1----------	7	Sb
10	vytvoření	vytvoření_^(*3it)	NNNS1-----A----	7	Sb
11	přibližně	přibližně_^(*1ý)	Dg-------1A----	13	Adv
12	desetitisíce	desetitisíc	NNIP1-----A----	7	Obj
13	nových	nový	AANP2----1A----	15	Atr
14	pracovních	pracovní	AANP2----1A----	15	Atr
15	míst	místo-1_^(fyzické_umístění)	NNNP2-----A----	12	Atr
16	.	.	Z:-------------	0	AuxK

1	Na	na-1	RR--6----------	10	AuxP
2	každém	každý	AAIS6----1A----	3	Atr
3	ostrově	ostrov	NNIS6-----A----	1	Adv
4	o	o-1	RR--6----------	3	AuxP
5	velikosti	velikost_^(*3ý)	NNFS6-----A----	4	Obj
6	tři	tři`3	ClXP4----------	8	Atr
7	čtvereční	čtvereční	AAIP4----1A----	8	Atr
8	kilometry	kilometr	NNIP4-----A----	10	Sb
9	by	být	Vc-------------	10	AuxV
10	mohly	moci_^(mít_možnost_[něco_dělat])	VpTP---XR-AA---	17	Pred
11	být	být	Vf--------A----	10	Obj
12	byty	byt_^(místo_k_bydlení)	NNIP4-----A----	10	Sb
13	pro	pro-1	RR--4----------	12	AuxP
14	dvacet	dvacet`20	Cn-S4----------	13	Adv
15	tisíc	tisíc-1`1000	ClXS2----------	14	Atr
16	obyvatel	obyvatel	NNMS1-----A----	15	Atr
17	a	a-1	J^-------------	0	Coord
18	pro	pro-1	RR--4----------	17	AuxP
19	stejný	stejný	AAIS4----1A----	20	Atr
20	počet	počet	NNIS4-----A----	18	ExD
21	turistů	turista	NNMP2-----A----	24	Atr
22	,	,	Z:-------------	24	AuxX
23	obchodníků	obchodník	NNMP2-----A----	24	Atr
24	a	a-1	J^-------------	20	Coord
25	dalších	další	AAMP2----1A----	24	Atr
26	.	.	Z:-------------	0	AuxK

1	Každý	každý	AAIS1----1A----	2	Atr
2	ostrov	ostrov	NNIS1-----A----	4	Sb
3	by	být	Vc-------------	4	AuxV
4	měl	mít	VpYS---XR-AA---	8	Pred
5	stát	stát-2_^(něco_se_přihodilo)	Vf--------A----	4	Obj
6	miliardu	miliarda`1000000000	NNFS4-----A----	5	Obj
7	dolarů	dolar_;b	NNIP2-----A----	6	Atr
8	a	a-1	J^-------------	0	Coord
9	měl	mít	VpYS---XR-AA---	8	Pred
10	by	být	Vc-------------	9	AuxV
11	být	být	Vf--------A----	12	AuxV
12	financován	financovat_:T	VsYS---XX-AP---	9	Obj
13	ze	z-1	RV--2----------	12	AuxP
14	soukromých	soukromý	AAIP2----1A----	15	Atr
15	zdrojů	zdroj	NNIP2-----A----	13	Adv
16	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	2	AuxG
2	Jsem	být	VB-S---1P-AA---	8	AuxV
3	pro	pro-1	RR--4----------	2	AuxP
4	vybudování	vybudování_^(*3at)	NNNS4-----A----	3	Adv
5	ostrovů	ostrov	NNIP2-----A----	4	Atr
6	,	,	Z:-------------	2	AuxX
7	"	"	Z:-------------	2	AuxG
8	řekl	říci_:W	VpYS---XR-AA---	0	Pred
9	nynější	nynější	AAMS1----1A----	11	Atr
10	izraelský	izraelský	AAMS1----1A----	11	Atr
11	premiér	premiér	NNMS1-----A----	13	Atr
12	Ariel	Ariel_;R	NNIS1-----A----	13	Atr
13	Šaron	Šaron	NNMS1-----A----	8	Sb
14	už	už	Db-------------	17	AuxZ
15	před	před-1	RR--7----------	8	AuxP
16	několika	několik	Ca--7----------	17	Atr
17	lety	rok	NNNP7-----A----	15	Adv
18	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	2	AuxG
2	Chtěl	chtít	VpYS---XR-AA---	0	Pred
3	bych	být	Vc-S---1-------	2	AuxV
4	to	ten	PDNS4----------	5	Obj
5	uvést	uvést	Vf--------A----	2	Obj
6	do	do-1	RR--2----------	5	AuxP
7	praxe	praxe	NNFS2-----A----	6	Adv
8	.	.	Z:-------------	0	AuxK

1	Může	moci_^(mít_možnost_[něco_dělat])	VB-S---3P-AA---	0	Pred
2	to	ten	PDNS1----------	1	Sb
3	změnit	změnit_:W	Vf--------A----	1	Obj
4	kvalitu	kvalita	NNFS4-----A----	3	Obj
5	života	život	NNIS2-----A----	4	Atr
6	těch	ten	PDXP2----------	5	Atr
7	,	,	Z:-------------	9	AuxX
8	kteří	který	P4MP1----------	9	Sb
9	žijí	žít	VB-P---3P-AA--1	6	Atr
10	podél	podél	RR--2----------	9	AuxP
11	pobřeží	pobřeží	NNNS2-----A----	10	Adv
12	Izraele	Izrael_;G	NNIS2-----A----	11	Atr
13	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	2	AuxG
2	Není	být	VB-S---3P-NA---	3	Pred
3	proto	proto-1_^(proto;_a_proto,_ale_proto,...)	J^-------------	0	Coord
4	divu	div-1	NNIS2-----A----	2	Sb
5	,	,	Z:-------------	6	AuxX
6	že	že	J,-------------	2	AuxC
7	odcházející	odcházející_^(*4t)	AGFS1-----A----	9	Atr
8	Šaronova	Šaronův_^(*2)	AUFS1M---------	9	Atr
9	vláda	vláda	NNFS1-----A----	11	Sb
10	ještě	ještě	Db-------------	11	Adv
11	ustavila	ustavit_:W	VpQW---XR-AA---	6	Obj
12	vládní	vládní	AAFS4----1A----	13	Atr
13	komisi	komise	NNFS4-----A----	11	Obj
14	,	,	Z:-------------	19	AuxX
15	která	který	P4FS1----------	19	Sb
16	se	se_^(zvr._zájmeno/částice)	P7-X4----------	19	AuxT
17	bude	být	VB-S---3F-AA---	19	AuxV
18	problémem	problém	NNIS7-----A----	19	Obj
19	zabývat	zabývat_:T	Vf--------A----	13	Atr
20	.	.	Z:-------------	0	AuxK

1	Mluvčí	mluvčí	NNMS1-----A----	13	Sb
2	izraelského	izraelský	AAIS2----1A----	4	Atr
3	Technologického	technologický	AAIS2----1A----	4	Atr
4	ústavu	ústav	NNIS2-----A----	1	Atr
5	,	,	Z:-------------	7	AuxX
6	který	který	P4YS1----------	7	Sb
7	má	mít	VB-S---3P-AA---	4	Atr
8	na	na-1	RR--6----------	7	AuxP
9	starosti	starost	NNFS6-----A----	8	Obj
10	výzkum	výzkum	NNIS1-----A----	7	Obj
11	projektu	projekt	NNIS2-----A----	10	Atr
12	,	,	Z:-------------	7	AuxX
13	řekl	říci_:W	VpYS---XR-AA---	0	Pred
14	BBC	BBC_:B_;K	NNFXX-----A---8	13	Sb
15	,	,	Z:-------------	16	AuxX
16	že	že	J,-------------	13	AuxC
17	ostrovy	ostrov	NNIP1-----A----	18	Sb
18	budou	být	VB-P---3F-AA---	16	Obj
19	alternativou	alternativa	NNFS7-----A----	18	Pnom
20	k	k-1	RR--3----------	19	AuxP
21	výstavbě	výstavba	NNFS3-----A----	20	Atr
22	v	v-1	RR--6----------	21	AuxP
23	poušti	poušť	NNFS6-----A----	22	Atr
24	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	4	AuxG
2	Části	část	NNFS2-----A----	4	Sb
3	Izraele	Izrael_;G	NNIS2-----A----	2	Atr
4	nemohou	moci_^(mít_možnost_[něco_dělat])	VB-P---3P-NA--1	19	Obj
5	být	být	Vf--------A----	6	AuxV
6	využity	využít	VsTP---XX-AP---	4	Obj
7	pro	pro-1	RR--4----------	6	AuxP
8	stavební	stavební	AAIP4----1A----	9	Atr
9	ani	ani	J^-------------	11	Coord
10	turistické	turistický	AAIP4----1A----	9	Atr
11	účely	účel	NNIP4-----A----	7	Adv
12	kvůli	kvůli	RR--3----------	11	AuxP
13	písečnému	písečný	AAIS3----1A----	14	Atr
14	a	a-1	J^-------------	16	Coord
15	kamenitému	kamenitý	AAIS3----1A----	14	Atr
16	podloží	podloží	NNNS1-----A----	12	Atr
17	,	,	Z:-------------	6	AuxX
18	"	"	Z:-------------	6	AuxG
19	tvrdí	tvrdit_:T	VB-S---3P-AA---	0	Pred
20	Tony	Tony_;Y	NNMS1-----A----	21	Atr
21	Bernstein	Bernstein_;S	NNMS1-----A----	19	Sb
22	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	10	AuxG
2	Do	do-1	RR--2----------	6	AuxP
3	budoucna	budoucno	NNNS2-----A----	2	Atr
4	nás	já	PP-P4--1-------	10	Obj
5	to	ten	PDNS1----------	6	Sb
6	bude	být	VB-S---3F-AA---	10	AuxV
7	více	hodně	Dg-------2A----	8	Adv
8	a	a-1	J^-------------	10	Coord
9	více	hodně	Dg-------2A----	8	Adv
10	limitovat	limitovat_:T	Vf--------A----	0	Pred
11	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	4	AuxG
2	Podle	podle-2	RR--2----------	4	AuxP
3	něj	on-1	P5ZS2--3-------	2	Adv
4	je	být	VB-S---3P-AA---	11	Pred
5	vybudování	vybudování_^(*3at)	NNNS1-----A----	4	Sb
6	umělých	umělý	AAIP2----1A----	7	Atr
7	ostrovů	ostrov	NNIP2-----A----	5	Atr
8	velice	velice	Db-------------	9	Adv
9	složité	složitý	AAIP1----1A----	4	Pnom
10	,	,	Z:-------------	11	AuxX
11	nicméně	nicméně	J^-------------	0	Coord
12	uskutečnitelné	uskutečnitelný_^(*4)	AAIP1----1A----	4	Pnom
13	.	.	Z:-------------	0	AuxK

1	Zvláště	zvláště	Db-------------	3	Adv
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	3	AuxT
3	objevily	objevit_:W	VpTP---XR-AA---	0	Pred
4	obavy	obava	NNFP1-----A----	3	Sb
5	z	z-1	RR--2----------	4	AuxP
6	toho	ten	PDZS2----------	5	Atr
7	,	,	Z:-------------	8	AuxX
8	že	že	J,-------------	6	AuxC
9	by	být	Vc-------------	12	AuxV
10	se	se_^(zvr._zájmeno/částice)	P7-X4----------	13	AuxT
11	ostrovy	ostrov	NNIP1-----A----	12	Sb
12	mohly	moci_^(mít_možnost_[něco_dělat])	VpTP---XR-AA---	8	Obj
13	stát	stát-2_^(něco_se_přihodilo)	Vf--------A----	12	Obj
14	vhodným	vhodný	AAIS7----1A----	15	Atr
15	a	a-1	J^-------------	17	Coord
16	snadným	snadný	AAIS7----1A----	15	Atr
17	cílem	cíl	NNIS7-----A----	13	Obj
18	pro	pro-1	RR--4----------	17	AuxP
19	teroristy	terorista	NNMP4-----A----	18	Atr
20	.	.	Z:-------------	0	AuxK

1	Bernstein	Bernstein_;S	NNMS1-----A----	2	Sb
2	je	být	VB-S---3P-AA---	3	Pred
3	však	však	J^-------------	0	Coord
4	přesvědčen	přesvědčit_:W	VsYS---XX-AP---	2	Pnom
5	,	,	Z:-------------	6	AuxX
6	že	že	J,-------------	4	AuxC
7	se	se_^(zvr._zájmeno/částice)	P7-X4----------	8	AuxR
8	dají	dát	VB-P---3P-AA---	6	Obj
9	přijmout	přijmout-2	Vf--------A----	8	Obj
10	taková	takový	PDNP4----------	12	Atr
11	bezpečnostní	bezpečnostní	AANP4----1A----	12	Atr
12	opatření	opatření_^(*3it)	NNNP4-----A----	9	Obj
13	,	,	Z:-------------	14	AuxX
14	aby	aby	J,-------------	8	AuxC
15	lidem	člověk	NNMP3-----A----	22	Obj
16	,	,	Z:-------------	18	AuxX
17	kteří	který	P4MP1----------	22	Sb
18	budou	být	VB-P---3F-AA---	15	Atr
19	na	na-1	RR--6----------	18	AuxP
20	ostrovech	ostrov	NNIP6-----A----	19	Adv
21	,	,	Z:-------------	8	AuxX
22	nehrozilo	hrozit_:T	VpNS---XR-NA---	14	Obj
23	příliš	příliš	Db-------------	24	Adv
24	velké	velký	AANS1----1A----	25	Atr
25	nebezpečí	nebezpečí	NNNS1-----A----	22	Sb
26	.	.	Z:-------------	0	AuxK

1	Vládou	vláda	NNFS7-----A----	2	Obj
2	ustavená	ustavený_^(*3it)	AAFS1----1A----	3	Atr
3	komise	komise	NNFS1-----A----	5	Sb
4	by	být	Vc-------------	5	AuxV
5	měla	mít	VpQW---XR-AA---	0	Pred
6	projekt	projekt	NNIS4-----A----	11	Obj
7	v	v-1	RR--6----------	11	AuxP
8	příštích	příští	AAIP6----1A----	10	Atr
9	třech	tři`3	ClXP6----------	10	Atr
10	měsících	měsíc	NNIP6-----A----	7	Atr
11	posuzovat	posuzovat_:T	Vf--------A----	5	Obj
12	.	.	Z:-------------	0	AuxK

1	Poté	poté	Db-------------	3	Adv
2	by	být	Vc-------------	3	AuxV
3	mělo	mít	VpNS---XR-AA---	0	Pred
4	být	být	Vf--------A----	5	AuxV
5	vydáno	vydat-1_:W_^(emitovat:_cenné_papíry,_knihu,_zvuk,...)	VsNS---XX-AP---	3	Obj
6	závěrečné	závěrečný	AANS1----1A----	7	Atr
7	rozhodnutí	rozhodnutí_^(*3out)	NNNS1-----A----	3	Sb
8	.	.	Z:-------------	0	AuxK

1	Pokud	pokud	J,-------------	6	AuxC
2	bude	být	VB-S---3F-AA---	1	Adv
3	rozhodnutí	rozhodnutí_^(*3out)	NNNS1-----A----	2	Sb
4	kladné	kladný	AANS1----1A----	3	Atr
5	,	,	Z:-------------	1	AuxX
6	mohla	moci_^(mít_možnost_[něco_dělat])	VpQW---XR-AA---	0	Pred
7	by	být	Vc-------------	6	AuxV
8	podle	podle-2	RR--2----------	10	AuxP
9	expertů	expert	NNMP2-----A----	8	Adv
10	začít	začít-1	Vf--------A----	6	Obj
11	výstavba	výstavba	NNFS1-----A----	6	Sb
12	prvního	první	CrIS2----------	13	Atr
13	ostrova	ostrov	NNIS2-----A----	11	Atr
14	do	do-1	RR--2----------	11	AuxP
15	tří	tři`3	ClXP2----------	16	Atr
16	let	rok	NNNP2-----A----	14	Atr
17	.	.	Z:-------------	0	AuxK

</TEXT>
</DOC>
