<DOC>
<DOCID>LN-20020225056</DOCID>
<DOCNO>LN-20020225056</DOCNO>
<DATE>02/25/02</DATE>
<TITLE>
1	Banky	banka	NNFP1-----A----	2	Sb
2	zvyšují	zvyšovat_:T	VB-P---3P-AA---	0	Pred
3	sazby	sazba	NNFP1-----A----	2	Obj
4	za	za-1	RR--4----------	3	AuxP
5	směnu	směna-1_^(výměna_za_něco)	NNFS4-----A----	4	Atr
6	měn	měna	NNFP2-----A----	5	Atr
7	zemí	země	NNFP2-----A----	6	Atr
8	EMU	ema	NNFS4-----A----	15	Obj
9	*	*	Z:-------------	15	Pnom
10	Francouzský	francouzský	AAIS4----1A----	11	Atr
11	frank	frank	NNIS4-----A----	15	Obj
12	,	,	Z:-------------	15	AuxX
13	holandský	holandský	AAIS4----1A----	14	Atr
14	gulden	gulden	NNIS4-----A----	15	Obj
15	a	a-1	J^-------------	2	Coord
16	irská	irský	AAFS1----1A----	17	Atr
17	libra	libra-1_^(jednotka_britské_měny)	NNFS1-----A----	19	Sb
18	definitivně	definitivně_^(*1í)	Dg-------1A----	19	Adv
19	zanikly	zaniknout_:W	VpTP---XR-AA--1	15	Pred

</TITLE>
<TEXT>
1	Šest	šest`6	Cn-S1----------	2	Sb
2	a	a-1	J^-------------	4	Coord
3	půl	půl-2	NNFS1-----A----	2	Sb
4	století	století	NNNS2-----A----	6	Atr
5	-	-	Z:-------------	7	AuxG
6	tak	tak-3	Db-------------	7	Adv
7	dlouho	dlouho_^(o_čase;_př._dlouhá_doba)	Dg-------1A----	8	Adv
8	platili	platit_:T_:W	VpMP---XR-AA---	0	Pred
9	Francouzi	Francouz_;E	NNMP1-----A----	8	Sb
10	svými	svůj-1_^(přivlast.)	P8XP7----------	8	Adv
11	franky	frank	NNIP4-----A----	8	Obj
12	.	.	Z:-------------	0	AuxK

1	Od	od-1	RR--2----------	10	AuxP
2	minulého	minulý	AAIS2----1A----	3	Atr
3	týdne	týden_^(jednotka_času)	NNIS2-----A----	1	Adv
4	mohou	moci_^(mít_možnost_[něco_dělat])	VB-P---3P-AA--1	0	Pred
5	na	na-1	RR--4----------	10	AuxP
6	tyto	tento	PDIP4----------	8	Atr
7	idylické	idylický	AAIP4----1A----	8	Atr
8	dny	den_^(jednotka_času)	NNIP4-----A----	5	Adv
9	jenom	jenom_^(pouze)	TT-------------	10	AuxZ
10	vzpomínat	vzpomínat_:T	Vf--------A----	4	Obj
11	.	.	Z:-------------	0	AuxK

1	Za	za-1	RR--4----------	4	AuxP
2	tři	tři`3	ClXP4----------	3	Atr
3	dny	den_^(jednotka_času)	NNIP4-----A----	1	Adv
4	zaniknou	zaniknout_:W	VB-P---3P-AA---	0	Pred
5	i	i-1	J^-------------	7	AuxZ
6	ostatní	ostatní	AAFP1----1A----	7	Atr
7	měny	měna	NNFP1-----A----	4	Sb
8	zemí	země	NNFP2-----A----	7	Atr
9	Evropské	evropský	AAFS2----1A----	11	Atr
10	měnové	měnový	AAFS2----1A----	11	Atr
11	unie	unie	NNFS2-----A----	8	Atr
12	.	.	Z:-------------	0	AuxK

1	Skeptici	skeptik	NNMP1-----A----	2	Sb
2	očekávali	očekávat_:T	VpMP---XR-AA---	19	Pred
3	obrovské	obrovský	AAIP4----1A----	4	Atr
4	problémy	problém	NNIP4-----A----	2	Obj
5	s	s-1	RR--7----------	4	AuxP
6	přechodem	přechod	NNIS7-----A----	5	Atr
7	na	na-1	RR--4----------	6	AuxP
8	společnou	společný	AAFS4----1A----	9	Atr
9	měnu	měna	NNFS4-----A----	7	Atr
10	-	-	Z:-------------	11	AuxG
11	více	hodně	Dg-------2A----	2	Adv
12	než	než-2	J,-------------	11	AuxC
13	300	300	C=-------------	12	Adv
14	000	000	C=-------------	12	ExD
15	milionů	milión`1000000	NNIP2-----A----	11	Atr
16	obyvatel	obyvatel	NNMS1-----A----	15	Atr
17	zemí	země	NNFS7-----A----	16	Atr
18	EMU	ema	NNFS4-----A----	17	Atr
19	však	však	J^-------------	0	Coord
20	tento	tento	PDIS4----------	21	Atr
21	krok	krok	NNIS4-----A----	22	Obj
22	zvládlo	zvládnout_:W	VpNS---XR-AA--1	19	Pred
23	až	až-3_^(až_k_...,_až_dost)	TT-------------	24	AuxZ
24	překvapivě	překvapivě_^(*1ý)	Dg-------1A----	22	Adv
25	snadno	snadno	Dg-------1A----	22	Adv
26	.	.	Z:-------------	0	AuxK

1	Možná	možná_^(snad)	Db-------------	0	ExD
2	,	,	Z:-------------	3	AuxX
3	že	že	J,-------------	12	AuxC
4	něco	něco	PZ--4----------	6	Obj
5	podobného	podobný	AANS2----1A----	4	Atr
6	čeká	čekat_:T	VB-S---3P-AA---	15	Pred
7	za	za-1	RR--4----------	6	AuxP
8	několik	několik	Ca--4----------	7	Adv
9	let	rok	NNNP2-----A----	8	Atr
10	i	i-1	J^-------------	8	Coord
11	ČR	ČR-1_:B_;G_^(Česká_republika)	NNFXX-----A---8	10	Atr
12	,	,	Z:-------------	15	AuxX
13	zatím	zatím	Db-------------	14	Adv
14	je	být	VB-S---3P-AA---	15	Pred
15	však	však	J^-------------	1	Coord
16	aktuální	aktuální	AAIS1----1A----	18	Atr
17	jiný	jiný	AAIS1----1A----	18	Atr
18	problém	problém	NNIS1-----A----	14	Sb
19	.	.	Z:-------------	0	AuxK

1	Jak	jak-3	Db-------------	2	Adv
2	naložit	naložit_:W	Vf--------A----	0	Pred
3	s	s-1	RR--7----------	2	AuxP
4	markami	marka	NNFP7-----A----	7	Atr
5	,	,	Z:-------------	7	Coord
6	franky	frank	NNIP7-----A----	7	Obj
7	či	či	J^-------------	3	Coord
8	guldeny	gulden	NNIP1-----A----	7	Obj
9	?	?	Z:-------------	8	AuxG
10	Mince	mince	NNFS1-----A----	11	Obj
11	přestala	přestat	VpQW---XR-AA---	5	Pred
12	většina	většina	NNFS1-----A----	11	Sb
13	českých	český	AAFP2----1A----	14	Atr
14	bank	banka	NNFP2-----A----	12	Atr
15	přijímat	přijímat_:T	Vf--------A----	11	Obj
16	ke	k-1	RV--3----------	15	AuxP
17	směně	směně_^(*2t)	Dg-------1A----	16	Adv
18	již	již	Db-------------	21	AuxZ
19	před	před-1	RR--7----------	15	AuxP
20	několika	několik	Ca--7----------	21	Atr
21	týdny	týden_^(jednotka_času)	NNIP7-----A----	19	Adv
22	.	.	Z:-------------	0	AuxK

1	Bankovky	bankovka	NNFP1-----A----	2	Sb
2	jsou	být	VB-P---3P-AA---	0	Pred
3	přijímány	přijímat_:T	VsTP---XX-AP---	2	Pnom
4	nadále	nadále	Db-------------	3	Adv
5	bez	bez-1	RR--2----------	2	AuxP
6	problémů	problém	NNIP2-----A----	5	Adv
7	.	.	Z:-------------	0	AuxK

1	Dají	dát	VB-P---3P-AA---	0	Pred
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	1	AuxR
3	buď	buď	J^-------------	8	AuxY
4	směnit	směnit_:W	Vf--------A----	8	Obj
5	ve	v-1	RV--6----------	4	AuxP
6	směnárnách	směnárna	NNFP6-----A----	5	Adv
7	,	,	Z:-------------	8	AuxX
8	či	či	J^-------------	1	Coord
9	uložit	uložit_:W	Vf--------A----	8	Obj
10	na	na-1	RR--4----------	9	AuxP
11	devizové	devizový	AANS4----1A----	12	Atr
12	konto	konto	NNNS4-----A----	10	Obj
13	.	.	Z:-------------	0	AuxK

1	S	s-1	RR--7----------	13	AuxP
2	tím	ten	PDZS7----------	1	Adv
3	,	,	Z:-------------	9	AuxX
4	jak	jak-3	Db-------------	9	Adv
5	národní	národní	AAFS1----1A----	6	Atr
6	měny	měna	NNFS2-----A----	9	Sb
7	postupně	postupně_^(*1ý)	Dg-------1A----	9	Adv
8	definitivně	definitivně_^(*1í)	Dg-------1A----	9	Adv
9	zanikají	zanikat_:T	VB-P---3P-AA---	2	Atr
10	,	,	Z:-------------	9	AuxX
11	jsou	být	VB-P---3P-AA---	0	Pred
12	směny	směna-1_^(výměna_za_něco)	NNFP1-----A----	13	Sb
13	prováděny	provádět_:T	VsTP---XX-AP---	11	Pnom
14	v	v-1	RR--6----------	13	AuxP
15	režimu	režim	NNIS6-----A----	14	Adv
16	prekluze	prekluze	NNFS2-----A----	15	Atr
17	.	.	Z:-------------	0	AuxK

1	To	ten	PDNS1----------	2	Sb
2	znamená	znamenat_:T	VB-S---3P-AA---	0	Pred
3	jediné	jediný	AAFS2----1A----	2	Obj
4	za	za-1	RR--4----------	7	AuxP
5	jejich	jeho_^(přivlast.)	PSXXXXP3-------	6	Atr
6	výměnu	výměna	NNFS4-----A----	4	Obj
7	zaplatí	zaplatit_:W	VB-S---3P-AA---	3	Atr
8	klient	klient	NNMS1-----A----	7	Sb
9	mnohem	mnohem	Db-------------	10	Adv
10	vyšší	vysoký	AAIP1----2A----	11	Atr
11	poplatky	poplatek	NNIP1-----A----	8	Atr
12	,	,	Z:-------------	13	AuxX
13	než	než-2	J,-------------	10	AuxC
14	na	na-1	RR--6----------	16	AuxP
15	jaké	jaký	P4FS6----------	14	Adv
16	je	být	VB-S---3P-AA---	13	Adv
17	ve	v-1	RV--6----------	16	AuxP
18	směnárnách	směnárna	NNFP6-----A----	17	Adv
19	bank	banka	NNFP2-----A----	18	Atr
20	zvyklý	zvyklý	AAIS1----1A----	16	Pnom
21	.	.	Z:-------------	0	AuxK

1	Opozdilci	opozdilec	NNMP1-----A----	3	Sb
2	tak	tak-3	Db-------------	3	Adv
3	vymění	vyměnit_:W	VB-P---3P-AA---	0	Pred
4	např	například_:B_,x	Db------------8	3	AuxY
5	.	.	Z:-------------	0	AuxK

1	v	v-1	RR--6----------	0	AuxP
2	pobočkách	pobočka	NNFP6-----A----	1	Adv
3	ČSOB	ČSOB_:B_;K_;b	NNFXX-----A---8	2	Atr
4	měny	měna	NNFS2-----A----	2	Atr
5	zemí	země	NNFP2-----A----	4	Atr
6	EMU	ema	NNFS4-----A----	5	Atr
7	za	za-1	RR--4----------	6	AuxP
8	poplatek	poplatek	NNIS4-----A----	7	Atr
9	ve	v-1	RV--6----------	8	AuxP
10	výši	výše_^(velikost_apod.;_též_tlaková_výše)	NNFS6-----A----	9	Atr
11	10	10	C=-------------	10	Atr
12	%	%	Z:-------------	13	AuxG
13	oproti	oproti	RR--3----------	10	AuxP
14	předchozím	předchozí	AAMS7----1A----	15	Atr
15	2	2	NNMS1-----A----	13	Atr
16	%	%	Z:-------------	13	AuxG
17	.	.	Z:-------------	0	AuxK

1	GE	GE-1_:B_;K_,t_^(General_Electric_Company)	NNFXX-----A----	3	Atr
2	Capital	Capital	AAXXX----1A----	3	Atr
3	Bank	bank	NNIS1-----A----	0	ExD
4	dokonce	dokonce	Db-------------	7	AuxZ
5	s	s-1	RR--7----------	3	AuxP
6	poplatkem	poplatek	NNIS7-----A----	5	Obj
7	plných	plný	AAFP2----1A----	8	Atr
8	30	30	C=-------------	6	Atr
9	%	%	Z:-------------	5	AuxG
10	.	.	Z:-------------	0	AuxK

1	Totéž	tentýž	PDNS1----------	2	Sb
2	platí	platit_:T_:W	VB-S---3P-AA---	9	Atr
3	pro	pro-1	RR--4----------	2	AuxP
4	ukládání	ukládání_^(*3at)	NNNS4-----A----	3	Adv
5	peněz	peníze_^(jako_platidlo)	NNIP2-----A----	4	Atr
6	na	na-1	RR--4----------	4	AuxP
7	devizový	devizový	AAIS4----1A----	8	Atr
8	účet	účet	NNIS4-----A----	6	Atr
9	-	-	Z:-------------	14	Coord
10	je	být	VB-S---3P-AA---	9	Pred
11	to	ten	PDNS1----------	10	Sb
12	možné	možný	AANS1----1A----	10	Pnom
13	,	,	Z:-------------	14	AuxX
14	ale	ale	J^-------------	0	Coord
15	zájemce	zájemce	NNMS1-----A----	16	Sb
16	musí	muset	VB-S---3P-AA---	14	Pred
17	počítat	počítat_:T	Vf--------A----	16	Obj
18	s	s-1	RR--7----------	17	AuxP
19	poplatky	poplatek	NNIP7-----A----	18	Obj
20	za	za-1	RR--4----------	19	AuxP
21	režim	režim	NNIS4-----A----	20	Atr
22	prekluze	prekluze	NNFS2-----A----	21	Atr
23	.	.	Z:-------------	0	AuxK

1	Rozhodnutí	rozhodnutí_^(*3out)	NNNS1-----A----	12	Sb
2	zbavit	zbavit_:W	Vf--------A----	1	Atr
3	se	se_^(zvr._zájmeno/částice)	P7-X4----------	2	AuxT
4	peněz	peníze_^(jako_platidlo)	NNIP2-----A----	2	Obj
5	třeba	třeba-2_^(například)	Db-------------	8	AuxZ
6	během	během	RR--2----------	12	AuxP
7	letní	letní	AAFS2----1A----	8	Atr
8	dovolené	dovolená_^(ze_zaměstnání)	NNFS2-----A----	6	Adv
9	v	v-1	RR--6----------	8	AuxP
10	příslušné	příslušný_^(*2et)	AAFS6----1A----	11	Atr
11	zemi	země	NNFS6-----A----	9	Atr
12	není	být	VB-S---3P-NA---	0	Pred
13	právě	právě	Db-------------	14	AuxZ
14	nejjistější	jistý	AAFS1----3A----	12	Pnom
15	.	.	Z:-------------	0	AuxK

1	Všechny	všechen	PLFP1----------	3	Atr
2	zbylé	zbylý	AAFP1----1A----	3	Atr
3	měny	měna	NNFP1-----A----	6	Sb
4	zemí	země	NNFP2-----A----	3	Atr
5	EMU	ema	NNFS4-----A----	6	Obj
6	mají	mít	VB-P---3P-AA---	0	Pred
7	před	před-1	RR--7----------	6	AuxP
8	sebou	se_^(zvr._zájmeno/částice)	P6-X7----------	7	Adv
9	už	už	Db-------------	12	AuxZ
10	jen	jen-1_^(pouze)	TT-------------	12	AuxZ
11	tři	tři`3	ClXP4----------	12	Atr
12	dny	den_^(jednotka_času)	NNIP4-----A----	6	Adv
13	existence	existence	NNFS2-----A----	12	Atr
14	.	.	Z:-------------	0	AuxK

1	V	v-1	RR--6----------	8	AuxP
2	noci	noc	NNFS6-----A----	1	Adv
3	ze	z-1	RV--2----------	2	AuxP
4	středy	středa	NNFS2-----A----	3	Atr
5	na	na-1	RR--4----------	2	AuxP
6	čtvrtek	čtvrtek	NNIS4-----A----	5	Adv
7	definitivně	definitivně_^(*1í)	Dg-------1A----	8	Adv
8	zaniknou	zaniknout_:W	VB-P---3P-AA---	9	Pred
9	a	a-1	J^-------------	0	Coord
10	poslední	poslední	AAFP1----1A----	11	Atr
11	bankovky	bankovka	NNFP1-----A----	12	Sb
12	a	a-1	J^-------------	8	Coord
13	mince	mince	NNFP1-----A----	12	Sb
14	budou	být	VB-P---3F-AA---	15	AuxV
15	staženy	stáhnout	VsTP---XX-AP---	12	Sb
16	z	z-1	RR--2----------	15	AuxP
17	oběhu	oběh	NNIS2-----A----	16	Adv
18	.	.	Z:-------------	0	AuxK

1	Konverze	konverze	NNFP1-----A----	6	Obj
2	budou	být	VB-P---3F-AA---	6	AuxV
3	ještě	ještě	Db-------------	5	AuxZ
4	nějakou	nějaký	PZFS4----------	5	Atr
5	dobu	doba	NNFS4-----A----	6	Obj
6	provádět	provádět_:T	Vf--------A----	0	Pred
7	i	i-1	J^-------------	9	AuxZ
8	obchodní	obchodní	AAFS2----1A----	9	Atr
9	banky	banka	NNFS2-----A----	6	Obj
10	v	v-1	RR--6----------	9	AuxP
11	jednotlivých	jednotlivý	AAFP6----1A----	12	Atr
12	zemích	země	NNFP6-----A----	10	Atr
13	.	.	Z:-------------	0	AuxK

1	Nemají	mít	VB-P---3P-NA---	2	Pred
2	však	však	J^-------------	0	Coord
3	povinnost	povinnost_^(*3ý)	NNFS4-----A----	1	Obj
4	bankovky	bankovka	NNFS2-----A----	5	Atr
5	či	či	J^-------------	3	Coord
6	mince	mince	NNFS2-----A----	5	Atr
7	přijímat	přijímat_:T	Vf--------A----	1	Obj
8	jen	jen-1_^(pouze)	TT-------------	10	AuxZ
9	v	v-1	RR--6----------	11	AuxP
10	souladu	soulad	NNIS6-----A----	11	AuxP
11	s	s-1	RR--7----------	7	AuxP
12	ustanovenými	ustanovený_^(*3it)	AANP7----1A----	13	Atr
13	pravidly	pravidlo	NNNP7-----A----	11	Atr
14	(	(	Z:-------------	15	AuxG
15	viz	viz_:W_^(odkaz_na_jiné_místo)	Vi-S---2--A---1	13	Pred
16	tabulka	tabulka	NNFS1-----A----	15	Obj
17	na	na-1	RR--6----------	16	AuxP
18	této	tento	PDFS6----------	19	Atr
19	straně	strana-1_^(v_prostoru)	NNFS6-----A----	17	Adv
20	)	)	Z:-------------	15	AuxG
21	.	.	Z:-------------	0	AuxK

1	Když	když	J,-------------	4	AuxC
2	zaniklé	zaniklý	AAFP1----1A----	3	Atr
3	měny	měna	NNFP1-----A----	4	Obj
4	přijímat	přijímat_:T	Vf--------A----	0	Pred
5	budou	být	VB-P---3F-AA---	4	AuxV
6	,	,	Z:-------------	1	AuxX
7	tak	tak-3	Db-------------	9	Adv
8	samozřejmě	samozřejmě_^(*1ý)	Dg-------1A----	7	AuxY
9	rovněž	rovněž	Db-------------	11	AuxZ
10	v	v-1	RR--6----------	4	AuxP
11	režimu	režim	NNIS6-----A----	10	Adv
12	prekluze	prekluze	NNFS2-----A----	11	Atr
13	.	.	Z:-------------	0	AuxK

1	Podobně	podobně_^(*1ý)	Dg-------1A----	11	Adv
2	jako	jako	J,-------------	1	AuxC
3	při	při-1	RR--6----------	2	AuxP
4	směně	směna-1_^(výměna_za_něco)	NNFS6-----A----	3	Adv
5	v	v-1	RR--6----------	4	AuxP
6	českých	český	AAFP6----1A----	7	Atr
7	bankách	banka	NNFP6-----A----	5	Atr
8	na	na-1	RR--6----------	7	AuxP
9	výměně	výměna	NNFS6-----A----	8	Atr
10	klient	klient	NNMS1-----A----	11	Sb
11	prodělá	prodělat_:W	VB-S---3P-AA---	0	Pred
12	.	.	Z:-------------	0	AuxK

1	Bankovky	bankovka	NNFP1-----A----	2	Sb
2	i	i-1	J^-------------	6	Coord
3	mince	mince	NNFP1-----A----	2	Sb
4	zaniklých	zaniklý	AAFP2----1A----	5	Atr
5	měn	měna	NNFP2-----A----	3	Atr
6	budou	být	VB-P---3F-AA---	10	AuxV
7	ještě	ještě	Db-------------	8	AuxZ
8	řadu	řada_^(linka,zástup,pořadí,...)	NNFS4-----A----	10	Obj
9	let	rok	NNNP2-----A----	8	Atr
10	přijímat	přijímat_:T	Vf--------A----	0	Pred
11	pouze	pouze	Db-------------	13	AuxZ
12	centrální	centrální	AAFP1----1A----	13	Atr
13	banky	banka	NNFP1-----A----	10	Obj
14	jednotlivých	jednotlivý	AAIP2----1A----	15	Atr
15	států	stát-1_^(státní_útvar)	NNIP2-----A----	13	Atr
16	.	.	Z:-------------	0	AuxK

1	Tato	tento	PDFS1----------	2	Atr
2	varianta	varianta	NNFS1-----A----	4	Sb
3	však	však	J^-------------	0	Coord
4	není	být	VB-S---3P-NA---	3	Pred
5	pro	pro-1	RR--4----------	4	AuxP
6	běžného	běžný	AAMS4----1A----	7	Atr
7	turistu	turista	NNMS4-----A----	5	Adv
8	právě	právě	Db-------------	9	AuxZ
9	lákavá	lákavý	AAFS1----1A----	10	Atr
10	a	a-1	J^-------------	4	Coord
11	praktická	praktický	AAFS1----1A----	10	Atr
12	.	.	Z:-------------	0	AuxK

</TEXT>
<HEADING>
1	Eura	euro_;b_^(evr._měna)	NNNP1-----A----	2	Obj
2	nakupujte	nakupovat_:T	Vi-P---2--A----	0	Pred
3	na	na-1	RR--6----------	2	AuxP
4	bezpečných	bezpečný-1	AANP6----1A----	5	Atr
5	místech	místo-1_^(fyzické_umístění)	NNNP6-----A----	3	Adv

</HEADING>
<TEXT>
1	Nové	nový	AAFP1----1A----	2	Atr
2	bankovky	bankovka	NNFP1-----A----	6	Sb
3	společné	společný	AAFS2----1A----	4	Atr
4	měny	měna	NNFS2-----A----	2	Atr
5	euro	euro_;b_^(evr._měna)	NNNS1-----A----	2	Atr
6	jsou	být	VB-P---3P-AA---	7	AuxV
7	chráněny	chránit	VsTP---XX-AP---	0	Pred
8	nejmodernějšími	moderní	AAFP7----3A----	9	Atr
9	technologiemi	technologie	NNFP7-----A----	7	Obj
10	.	.	Z:-------------	0	AuxK

1	Ať	ať	J,-------------	4	AuxC
2	už	už	Db-------------	1	AuxY
3	se	se_^(zvr._zájmeno/částice)	P7-X4----------	4	AuxT
4	jedná	jednat_:T	VB-S---3P-AA---	0	Pred
5	o	o-1	RR--4----------	4	AuxP
6	vodotisky	vodotisk	NNIP4-----A----	5	Obj
7	,	,	Z:-------------	12	AuxX
8	hologramy	hologram	NNIP4-----A----	12	Obj
9	,	,	Z:-------------	12	AuxX
10	ochranné	ochranný	AAIP4----1A----	11	Atr
11	proužky	proužek	NNIP4-----A----	12	Obj
12	a	a-1	J^-------------	6	Coord
13	podobně	podobně_^(*1ý)	Dg-------1A----	12	ExD
14	.	.	Z:-------------	0	AuxK

1	Přesto	přesto	Dg-------1A----	0	Coord
2	euro	euro_;b_^(evr._měna)	NNNS1-----A----	4	Sb
3	padělatele	padělatel	NNMS2-----A----	2	Atr
4	láká	lákat_:T	VB-S---3P-AA---	1	Pred
5	.	.	Z:-------------	0	AuxK

1	Mají	mít	VB-P---3P-AA---	0	Pred
2	velkou	velký	AAFS4----1A----	3	Atr
3	výhodu	výhoda	NNFS4-----A----	1	Obj
4	-	-	Z:-------------	1	Apos
5	měna	měna	NNFS1-----A----	7	Sb
6	dosud	dosud	Db-------------	7	Adv
7	není	být	VB-S---3P-NA---	11	Pred
8	příliš	příliš	Db-------------	9	Adv
9	známá	známý-2_^(co_[ne]známe)	AAFS1----1A----	7	Pnom
10	,	,	Z:-------------	11	AuxX
11	a	a-1	J^-------------	1	Coord
12	proto	proto-1_^(proto;_a_proto,_ale_proto,...)	J^-------------	11	AuxY
13	se	se_^(zvr._zájmeno/částice)	P7-X4----------	16	AuxT
14	mohou	moci_^(mít_možnost_[něco_dělat])	VB-P---3P-AA--1	11	Pred
15	lidé	člověk	NNMP1-----A---1	14	Sb
16	nechat	nechat_:T	Vf--------A----	14	Obj
17	snáze	snadno	Dg-------2A---1	18	Adv
18	napálit	napálit_:W	Vf--------A----	16	Obj
19	.	.	Z:-------------	0	AuxK

1	Ostatně	ostatně	Db-------------	9	AuxY
2	první	první	CrIP1----------	3	Atr
3	případy	případ	NNIP1-----A----	10	Sb
4	pokusu	pokus	NNIS2-----A----	3	Atr
5	používat	používat_:T_^(*3t)	Vf--------A----	4	Atr
6	falešné	falešný	AAFP4----1A----	7	Atr
7	bankovky	bankovka	NNFP4-----A----	5	Obj
8	už	už	Db-------------	10	Adv
9	byly	být	VpTP---XR-AA---	10	AuxV
10	zaznamenány	zaznamenat_:W	VsTP---XX-AP---	0	Pred
11	.	.	Z:-------------	0	AuxK

1	Jeden	jeden`1	ClYS1----------	11	Obj
2	i	i-1	J^-------------	4	AuxZ
3	u	u-1	RR--2----------	11	AuxP
4	nás	já	PP-P2--1-------	3	Adv
5	-	-	Z:-------------	6	AuxG
6	ačkoli	ačkoliv	J,------------1	0	AuxC
7	v	v-1	RR--6----------	11	AuxP
8	tomto	tento	PDZS6----------	9	Atr
9	případě	případ	NNIS6-----A----	7	Adv
10	podvodník	podvodník	NNMS1-----A----	11	Sb
11	neprojevil	projevit_:W	VpYS---XR-NA---	6	Adv
12	příliš	příliš	Db-------------	13	Atr
13	talentu	talent	NNIS3-----A----	11	Obj
14	.	.	Z:-------------	0	AuxK

1	Bankovku	bankovka	NNFS4-----A----	3	Obj
2	jednoduše	jednoduše	Dg-------1A----	3	Adv
3	okopíroval	okopírovat_:W	VpYS---XR-AA---	0	Pred
4	z	z-1	RR--2----------	3	AuxP
5	katalogu	katalog	NNIS2-----A----	4	Adv
6	,	,	Z:-------------	7	AuxX
7	takže	takže	J,-------------	3	AuxC
8	by	být	Vc-------------	10	AuxV
9	ji	on-1	PPFS4--3-------	10	Obj
10	nerozpoznal	rozpoznat_:W	VpYS---XR-NA---	7	Adv
11	asi	asi	TT-------------	10	AuxY
12	jen	jen-1_^(pouze)	TT-------------	13	AuxZ
13	málokdo	málokdo	PZM-1----------	10	Obj
14	.	.	Z:-------------	0	AuxK

1	Snad	snad	Db-------------	13	AuxY
2	jen	jen-1_^(pouze)	TT-------------	3	AuxZ
3	barman	barman	NNMS1-----A----	13	Sb
4	z	z-1	RR--2----------	3	AuxP
5	jihofrancouzského	jihofrancouzský	AANS2----1A----	6	Atr
6	městečka	městečko	NNNS2-----A----	4	Atr
7	Auch	Auch	NNFXX-----A----	6	Atr
8	,	,	Z:-------------	13	AuxX
9	který	který	P4YS1----------	13	Sb
10	na	na-1	RR--6----------	13	AuxP
11	začátku	začátek	NNIS6-----A----	10	Adv
12	roku	rok	NNIS2-----A---1	11	Atr
13	přijal	přijmout-2	VpYS---XR-AA---	0	Pred
14	místo	místo-1_^(fyzické_umístění)	NNNS4-----A----	13	Obj
15	bankovky	bankovka	NNFS2-----A----	14	Atr
16	v	v-1	RR--6----------	14	AuxP
17	hodnotě	hodnota	NNFS6-----A----	16	Atr
18	5	5	NNMS1-----A----	17	Atr
19	eur	euro_;b_^(evr._měna)	NNNP2-----A----	17	Atr
20	její	jeho_^(přivlast.)	PSFSXFS3-------	21	Atr
21	napodobeninu	napodobenina	NNFS4-----A----	19	Atr
22	ze	z-1	RV--2----------	21	AuxP
23	hry	hra_^(dětská;_v_divadle;...)	NNFS2-----A----	22	Atr
24	Monopoly	monopol	NNIP1-----A----	23	Atr
25	.	.	Z:-------------	0	AuxK

1	V	v-1	RR--6----------	5	AuxP
2	Itálii	Itálie_;G	NNFS6-----A----	1	Adv
3	však	však	J^-------------	0	Coord
4	policie	policie	NNFS1-----A----	5	Sb
5	odhalila	odhalit_:W	VpQW---XR-AA---	3	Pred
6	nebezpečnější	bezpečný-1	AAIS1----2N----	7	Atr
7	gang	gang	NNIS1-----A----	5	Obj
8	-	-	Z:-------------	3	Coord
9	jeho	jeho_^(přivlast.)	PSXXXZS3-------	10	Atr
10	produkce	produkce	NNFS1-----A----	13	Sb
11	falešných	falešný	AAFP2----1A----	12	Atr
12	bankovek	bankovka	NNFP2-----A----	10	Atr
13	byla	být	VpQW---XR-AA---	8	Pred
14	podle	podle-2	RR--2----------	13	AuxP
15	odborníků	odborník	NNMP2-----A----	14	Adv
16	velmi	velmi	Db-------------	17	Adv
17	zdařilá	zdařilý	AANP1----1A----	13	Pnom
18	.	.	Z:-------------	0	AuxK

1	Nezaměstnaný	zaměstnaný-1_^(všeob._význam:_činnost,_zaměstnání)_(*4t-1)	AAMS1----1N----	3	Atr
2	neapolský	neapolský	AAMS1----1A----	3	Atr
3	tiskař	tiskař	NNMS1-----A----	4	Sb
4	dokázal	dokázat	VpYS---XR-AA---	0	Pred
5	vyřešit	vyřešit_:W	Vf--------A----	4	Obj
6	problém	problém	NNIS4-----A----	5	Obj
7	,	,	Z:-------------	11	AuxX
8	se	s-1	RV--7----------	11	AuxP
9	kterým	který	P4ZS7----------	8	Obj
10	se	se_^(zvr._zájmeno/částice)	P7-X4----------	11	AuxT
11	potýkali	potýkat_:T	VpMP---XR-AA---	6	Atr
12	špičkoví	špičkový	AAMP1----1A----	13	Atr
13	odborníci	odborník	NNMP1-----A----	11	Sb
14	dlouhé	dlouhý-1_^(fyz._délka;_př._dlouhá_tyč)	AAIP1----1A----	15	Atr
15	měsíce	měsíc	NNIP1-----A----	16	Sb
16	a	a-1	J^-------------	11	Coord
17	roky	rok	NNIP4-----A----	16	Sb
18	.	.	Z:-------------	0	AuxK

1	Dá	dát	VB-S---3P-AA---	0	Pred
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	1	AuxR
3	očekávat	očekávat_:T	Vf--------A----	1	Obj
4	,	,	Z:-------------	5	AuxX
5	že	že	J,-------------	3	AuxC
6	v	v-1	RR--6----------	10	AuxP
7	několika	několik	Ca--6----------	9	Atr
8	příštích	příští	AAIP6----1A----	9	Atr
9	měsících	měsíc	NNIP6-----A----	6	Adv
10	nebudou	být	VB-P---3F-NA---	5	Sb
11	snahy	snaha	NNFP1-----A----	10	Sb
12	o	o-1	RR--4----------	11	AuxP
13	padělání	padělání_^(*3at)	NNNS4-----A----	12	Atr
14	měn	měna	NNFP2-----A----	13	Atr
15	příliš	příliš	Db-------------	16	Adv
16	velké	velký	AANS1----1A----	10	Pnom
17	,	,	Z:-------------	20	AuxX
18	kolem	kolem-1	RR--2----------	20	AuxP
19	eura	euro_;b_^(evr._měna)	NNNS2-----A----	18	AtrAdv
20	panuje	panovat_:T	VB-S---3P-AA---	11	Atr
21	zatím	zatím	Db-------------	20	Adv
22	rozruch	rozruch	NNIS1-----A----	20	Sb
23	.	.	Z:-------------	0	AuxK

1	V	v-1	RR--6----------	5	AuxP
2	období	období	NNNS6-----A----	1	Adv
3	letních	letní	AAFP2----1A----	4	Atr
4	dovolených	dovolená_^(ze_zaměstnání)	NNFP2-----A----	2	Atr
5	je	být	VB-S---3P-AA---	0	Pred
6	nutné	nutný	AANS1----1A----	5	Pnom
7	dávat	dávat_:T_^(*3t)	Vf--------A----	5	Sb
8	si	se_^(zvr._zájmeno/částice)	P7-X3----------	7	Obj
9	pozor	pozor-2	NNIS4-----A----	7	Obj
10	.	.	Z:-------------	0	AuxK

1	Pokud	pokud	J,-------------	9	AuxC
2	si	se_^(zvr._zájmeno/částice)	P7-X3----------	4	Adv
3	chcete	chtít	VB-P---2P-AA---	1	Adv
4	nakoupit	nakoupit_:W	Vf--------A----	3	Obj
5	eura	euro_;b_^(evr._měna)	NNNP4-----A----	4	Obj
6	,	,	Z:-------------	1	AuxX
7	rozhodně	rozhodně_^(*1ý)	Dg-------1A----	9	Adv
8	se	se_^(zvr._zájmeno/částice)	P7-X4----------	9	AuxT
9	vyplatí	vyplatit_:W	VB-P---3P-AA---	0	Pred
10	navštívit	navštívit_:W	Vf--------A----	9	Obj
11	banku	banka	NNFS4-----A----	12	Obj
12	či	či	J^-------------	10	Coord
13	směnárnu	směnárna	NNFS4-----A----	12	Obj
14	,	,	Z:-------------	16	AuxX
15	která	který	P4FS1----------	16	Sb
16	je	být	VB-S---3P-AA---	13	Atr
17	důvěryhodná	důvěryhodný	AAFS1----1A----	16	Pnom
18	.	.	Z:-------------	0	AuxK

1	Měnit	měnit_:T	Vf--------A----	7	Sb
2	si	se_^(zvr._zájmeno/částice)	P7-X3----------	1	Adv
3	peníze	peníz_^(drobná_mince)	NNIP4-----A----	1	Obj
4	u	u-1	RR--2----------	1	AuxP
5	překupníků	překupník	NNMP2-----A----	4	Atr
6	se	se_^(zvr._zájmeno/částice)	P7-X4----------	8	AuxT
7	nemusí	muset	VB-S---3P-NA---	0	Pred
8	vyplatit	vyplatit_:W	Vf--------A----	7	Obj
9	.	.	Z:-------------	0	AuxK

1	Před	před-1	RR--7----------	0	AuxP
2	cestou	cesta_^(konkrétní_i_abstr.;_i_'soudní_cestou')	NNFS7-----A----	1	Adv
3	do	do-1	RR--2----------	2	AuxP
4	zahraničí	zahraničí	NNNS2-----A----	3	Atr
5	a	a-1	J^-------------	2	Coord
6	první	první	CrFS7----------	7	Atr
7	zkušeností	zkušenost_^(*3ý)	NNFP2-----A----	5	Obj
8	s	s-1	RR--7----------	7	AuxP
9	novou	nový	AAFS7----1A----	10	Atr
10	měnou	měna	NNFS7-----A----	8	Atr
11	si	se_^(zvr._zájmeno/částice)	P7-X3----------	12	AuxZ
12	podobu	podoba	NNFS4-----A----	14	Obj
13	bankovek	bankovka	NNFP2-----A----	12	Atr
14	ověřte	ověřit_:W	Vi-P---2--A----	5	Pred
15	třeba	třeba-2_^(například)	Db-------------	18	AuxZ
16	na	na-1	RR--6----------	14	AuxP
17	internetových	internetový	AAFP6----1A----	18	Atr
18	stránkách	stránka	NNFP6-----A----	16	Adv
19	České	Český-1_;G_^(používá_se_i_pro_jména_org.,_výrobků_atd.)	AAFS2----1A----	21	Atr
20	národní	národní	AAFS2----1A----	21	Atr
21	banky	banka	NNFS2-----A----	18	Atr
22	(	(	Z:-------------	18	Apos
23	www	WWW-1_:B_,t_,x_^(World_Wide_Web)	NNFXX-----A---8	22	Atr
24	.	.	Z:-------------	0	AuxK

1	cnb	cnb	NNXXX-----A----	0	ExD
2	.	.	Z:-------------	0	AuxK

1	cz	cz	NNMS1-----A----	0	ExD
2	)	)	Z:-------------	1	ExD
3	,	,	Z:-------------	11	AuxX
4	kde	kde	Db-------------	5	Adv
5	najdete	najít	VB-P---2P-AA---	1	Atr
6	všechny	všechen	PLFP4----------	8	Atr
7	podstatné	podstatný	AAFP4----1A----	8	Atr
8	informace	informace	NNFP4-----A----	5	Obj
9	o	o-1	RR--6----------	8	AuxP
10	podobě	podoba	NNFS6-----A----	11	Atr
11	a	a-1	J^-------------	9	Coord
12	ochranných	ochranný	AAIP6----1A----	13	Atr
13	prvcích	prvek	NNIP6-----A----	11	Atr
14	eura	euro_;b_^(evr._měna)	NNNS2-----A----	13	Atr
15	.	.	Z:-------------	0	AuxK

1	Bankovky	bankovka	NNFP1-----A----	2	Sb
2	jsou	být	VB-P---3P-AA---	0	Pred
3	ve	v-1	RV--6----------	2	AuxP
4	všech	všechen	PLXP6----------	5	Atr
5	zemích	země	NNFP6-----A----	3	Adv
6	eurozóny	eurozóna	NNFS2-----A----	7	Atr
7	totožné	totožný	AAFS2----1A----	2	Pnom
8	.	.	Z:-------------	0	AuxK

1	Tištěny	tisknout	VsTP---XX-AP---	2	Pnom
2	jsou	být	VB-P---3P-AA---	0	Pred
3	na	na-1	RR--6----------	2	AuxP
4	různých	různý	AANP6----1A----	5	Atr
5	místech	místo-1_^(fyzické_umístění)	NNNP6-----A----	3	Adv
6	(	(	Z:-------------	2	ExD
7	celkem	celkem	Db-------------	8	AuxZ
8	15	15	C=-------------	2	Sb
9	mincoven	mincovna	NNFP2-----A----	8	Atr
10	ve	v-1	RV--6----------	9	AuxP
11	12	12	C=-------------	12	Atr
12	státech	stát-1_^(státní_útvar)	NNIP6-----A----	10	Atr
13	)	)	Z:-------------	10	AuxG
14	,	,	Z:-------------	17	AuxX
15	bankovky	bankovka	NNFP1-----A----	17	Sb
16	tak	tak-3	Db-------------	17	Adv
17	nemusí	muset	VB-S---3P-NA---	12	Atr
18	být	být	Vf--------A----	17	Obj
19	stoprocentně	stoprocentně_^(*1í)	Dg-------1A----	20	Adv
20	identické	identický	AANS1----1A----	18	Pnom
21	.	.	Z:-------------	0	AuxK

1	Objevit	objevit_:W	Vf--------A----	3	Obj
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	1	AuxT
3	mohou	moci_^(mít_možnost_[něco_dělat])	VB-P---3P-AA--1	0	Pred
4	například	například	Db-------------	6	AuxZ
5	nepatrné	patrný	AAIP1----1N----	6	Atr
6	rozdíly	rozdíl	NNIP1-----A----	3	Sb
7	v	v-1	RR--6----------	6	AuxP
8	kvalitě	kvalita	NNFS6-----A----	7	Atr
9	tisku	tisk	NNIS2-----A----	8	Atr
10	.	.	Z:-------------	0	AuxK

1	Mince	mince	NNFP1-----A----	2	Sb
2	mají	mít	VB-P---3P-AA---	0	Pred
3	společnou	společný	AAFS4----1A----	6	Atr
4	jen	jen-1_^(pouze)	TT-------------	5	AuxZ
5	jednu	jeden`1	ClFS4----------	6	Atr
6	stranu	strana-1_^(v_prostoru)	NNFS4-----A----	7	Obj
7	(	(	Z:-------------	2	Apos
8	takzvaná	takzvaný	AAFS1----1A----	9	Atr
9	eurostrana	eurostrana	NNFS1-----A----	7	Obj
10	)	)	Z:-------------	7	AuxG
11	.	.	Z:-------------	0	AuxK

1	Rub	rub	NNIS1-----A----	3	Sb
2	mincí	mince	NNFP2-----A----	1	Atr
3	je	být	VB-S---3P-AA---	0	Pred
4	zem	země	NNFS1-----A---1	3	Sb
5	od	od-1	RR--2----------	7	AuxP
6	země	země	NNFS2-----A----	5	Atr
7	odlišný	odlišný	AAIS1----1A----	3	Pnom
8	.	.	Z:-------------	0	AuxK

1	Celkem	celkem	Db-------------	2	Adv
2	je	být	VB-S---3P-AA---	0	Pred
3	v	v-1	RR--6----------	2	AuxP
4	oběhu	oběh	NNIS6-----A----	3	Adv
5	96	96	C=-------------	4	Atr
6	různých	různý	AAFP2----1A----	7	Atr
7	mincí	mince	NNFP2-----A----	5	Atr
8	.	.	Z:-------------	0	AuxK

1	K	k-1	RR--3----------	14	AuxP
2	záměně	záměna	NNFS3-----A----	1	Adv
3	(	(	Z:-------------	4	AuxG
4	nebo	nebo	J^-------------	1	Coord
5	pokusu	pokus	NNIS2-----A----	4	Atr
6	uvést	uvést	Vf--------A----	5	Atr
7	do	do-1	RR--2----------	6	AuxP
8	oběhu	oběh	NNIS2-----A----	7	Adv
9	mince	mince	NNFS2-----A----	8	Atr
10	"	"	Z:-------------	11	AuxG
11	vlastní	vlastní-1_^(příslušný_k_něčemu)	AANS1----1A----	8	Atr
12	"	"	Z:-------------	11	AuxG
13	)	)	Z:-------------	11	AuxG
14	může	moci_^(mít_možnost_[něco_dělat])	VB-S---3P-AA---	0	Pred
15	tedy	tedy	Db-------------	14	AuxY
16	dojít	dojít	Vf--------A----	14	Obj
17	celkem	celkem	Db-------------	18	Adv
18	snadno	snadno	Dg-------1A----	16	Adv
19	.	.	Z:-------------	0	AuxK

1	JAK	jak-2	J,-------------	3	Adv
2	SI	se_^(zvr._zájmeno/částice)	P7-X3----------	4	Adv
3	MŮŽETE	moci_^(mít_možnost_[něco_dělat])	VB-P---2P-AA---	0	Pred
4	VYMĚNIT	vyměnit_:W	Vf--------A----	3	Obj
5	PENÍZE	peníz_^(drobná_mince)	NNIP4-----A----	4	Obj
6	V	v-1	RR--6----------	5	AuxP
7	ZEMÍCH	země	NNFP6-----A----	6	Atr
8	EUROZÓNY	eurozóna	NNFS2-----A----	7	Atr
9	ZEMĚ	země	NNFS2-----A----	8	Atr
10	OBCHODNÍ	obchodní	AAFS2----1A----	11	Atr
11	BANKY	banka	NNFS2-----A----	9	Atr
12	CENTRÁLNÍ	centrální	AAFS2----1A----	13	Atr
13	BANKY	banka	NNFS2-----A----	11	Atr
14	bankovky	bankovka	NNFS2-----A----	13	Atr
15	mince	mince	NNFS2-----A----	14	Atr

</TEXT>
<HEADING>
1	Německo	Německo_;G	NNNS1-----A----	0	ExD
2	do	do-1	RR--2----------	1	AuxP
3	28	28	C=-------------	2	Atr
4	.	.	Z:-------------	0	AuxK

1	2	2	NNMS1-----A----	0	ExD
2	.	.	Z:-------------	0	AuxK

1	2002	2002	C=-------------	0	ExD
2	neomezeně	omezeně_^(*3it)	Dg-------1N----	3	Adv
3	neomezeně	omezeně_^(*3it)	Dg-------1N----	1	ExD

</HEADING>
<GEOGRAPHY>A</GEOGRAPHY>
<TEXT>
1	od	od-1	RR--2----------	0	AuxP
2	1	1	NNMS1-----A----	1	Adv
3	.	.	Z:-------------	0	AuxK

1	4	4	NNMS1-----A----	0	ExD
2	.	.	Z:-------------	0	AuxK

1	smějí	smět_:T	VB-P---3P-AA---	0	Pred
2	banky	banka	NNFP4-----A----	5	Atr
3	výměnu	výměna	NNFS4-----A----	5	Atr
4	zpoplatnit	zpoplatnit_:T	Vf--------A----	1	Obj
5	B	b-3_^(označení_pomocí_písmene)	NNNXX-----A----	4	Obj
6	-	-	Z:-------------	10	AuxG
7	v	v-1	RR--6----------	10	AuxP
8	těchto	tento	PDXP6----------	9	Atr
9	zemích	země	NNFP6-----A----	7	Adv
10	je	být	VB-S---3P-AA---	5	Atr
11	povinností	povinnost_^(*3ý)	NNFS7-----A----	10	Pnom
12	vykupovat	vykupovat_:T	Vf--------A----	11	Atr
13	měny	měna	NNFP4-----A----	12	Obj
14	do	do-1	RR--2----------	13	AuxP
15	1	1	NNMS1-----A----	14	Adv
16	.	.	Z:-------------	0	AuxK

1	3	3	NNMS1-----A----	0	ExD
2	.	.	Z:-------------	0	AuxK

1	2002	2002	C=-------------	4	Sb
2	,	,	Z:-------------	4	AuxX
3	poté	poté	Db-------------	4	Adv
4	záleží	záležet_:T	VB-S---3P-AA---	0	Pred
5	na	na-1	RR--4----------	4	AuxP
6	rozhodnutí	rozhodnutí_^(*3out)	NNNS4-----A----	5	Obj
7	jednotlivých	jednotlivý	AAFP2----1A----	8	Atr
8	bank	banka	NNFP2-----A----	6	Atr
9	,	,	Z:-------------	13	AuxX
10	jaká	jaký	P4NP1----------	11	Atr
11	pravidla	pravidlo	NNNP1-----A----	13	Obj
12	si	se_^(zvr._zájmeno/částice)	P7-X3----------	13	Adv
13	stanoví	stanovit_:W_^(určit)	VB-S---3P-AA---	8	Atr
14	C	c-3_^(označení_pomocí_písmene)	NNNXX-----A----	13	Sb
15	-	-	Z:-------------	13	Apos
16	do	do-1	RR--2----------	13	AuxP
17	tohoto	tento	PDZS2----------	18	Atr
18	data	datum_^(kalendářní)	NNNS2-----A----	16	Adv
19	všechny	všechen	PLFP4----------	20	Atr
20	banky	banka	NNFP4-----A----	13	Sb
21	,	,	Z:-------------	13	AuxX
22	pak	pak	Db-------------	25	Adv
23	podle	podle-2	RR--2----------	21	AuxP
24	jejich	jeho_^(přivlast.)	PSXXXXP3-------	26	Atr
25	individuálního	individuální	AANS2----1A----	26	Atr
26	rozhodnutí	rozhodnutí_^(*3out)	NNNS2-----A----	23	Adv
27	Pramen	Pramen_;K	NNIS1-----A----	26	Atr
28	:	:	Z:-------------	26	Apos
29	ČNB	ČNB-1_:B_;K_;b_^(Česká_národní_banka)	NNFXX-----A---8	27	Atr

</TEXT>
</DOC>
