<DOC>
<DOCID>MF-20020206201</DOCID>
<DOCNO>MF-20020206201</DOCNO>
<DATE>02/06/02</DATE>
<TITLE>
1	Podpětí	podpětí	NNNS1-----A----	2	Sb
2	může	moci_^(mít_možnost_[něco_dělat])	VB-S---3P-AA---	0	Pred
3	poškodit	poškodit_:W	Vf--------A----	2	Obj
4	i	i-1	J^-------------	5	AuxZ
5	lednice	lednice	NNFS1-----A----	3	Obj

</TITLE>
<GEOGRAPHY>Pardubice</GEOGRAPHY>
<TEXT>
1	Na	na-1	RR--6----------	4	AuxP
2	Pardubicku	Pardubicko_;G	NNNS6-----A----	1	Adv
3	se	se_^(zvr._zájmeno/částice)	P7-X4----------	4	AuxT
4	množí	množit_:T	VB-S---3P-AA---	0	Pred
5	počet	počet	NNIS1-----A----	4	Sb
6	rodin	rodina	NNFP2-----A----	5	Atr
7	,	,	Z:-------------	10	AuxX
8	které	který	P4FP1----------	10	Sb
9	si	se_^(zvr._zájmeno/částice)	P7-X3----------	10	AuxT
10	stěžují	stěžovat_:T	VB-P---3P-AA---	6	Atr
11	na	na-1	RR--4----------	10	AuxP
12	to	ten	PDNS4----------	11	Obj
13	,	,	Z:-------------	14	AuxX
14	že	že	J,-------------	12	AuxC
15	jim	on-1	PPXP3--3-------	19	Obj
16	je	být	VB-S---3P-AA---	14	Atr
17	do	do-1	RR--2----------	19	AuxP
18	domácnosti	domácnost	NNFS2-----A----	17	Adv
19	dodáváno	dodávat_:T_^(*4at)	VsNS---XX-AP---	16	Pnom
20	malé	malý	AANS1----1A----	21	Atr
21	množství	množství	NNNS1-----A----	19	Sb
22	elektrické	elektrický	AAFS2----1A----	23	Atr
23	energie	energie	NNFS2-----A----	21	Atr
24	.	.	Z:-------------	0	AuxK

1	Nejcitlivěji	citlivě_^(*1ý)	Dg-------3A----	11	Adv
2	na	na-1	RR--4----------	13	AuxP
3	takzvané	takzvaný	AANS4----1A----	4	Atr
4	podpětí	podpětí	NNNS4-----A----	2	Adv
5	,	,	Z:-------------	7	AuxX
6	které	který	P4NS1----------	11	Obj
7	může	moci_^(mít_možnost_[něco_dělat])	VB-S---3P-AA---	4	Atr
8	elektrospotřebiče	elektrospotřebič	NNIP1-----A----	7	Obj
9	v	v-1	RR--6----------	11	AuxP
10	domácnosti	domácnost	NNFS6-----A----	9	Atr
11	poškozovat	poškozovat_:T	Vf--------A----	7	Obj
12	,	,	Z:-------------	7	AuxX
13	reagují	reagovat_:T	VB-P---3P-AA---	0	Pred
14	počítače	počítač	NNIP1-----A----	15	Sb
15	a	a-1	J^-------------	13	Coord
16	ledničky	lednička	NNFP1-----A----	15	Sb
17	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	8	AuxG
2	Pořád	pořád	Db-------------	8	Adv
3	se	se_^(zvr._zájmeno/částice)	P7-X4----------	8	AuxT
4	nám	já	PP-P3--1-------	8	Obj
5	sám	sám_^(samotný)	PLYS1----------	8	AtvV
6	od	od-1	RR--2----------	8	AuxP
7	sebe	se_^(zvr._zájmeno/částice)	P6-X2----------	6	Adv
8	vypínal	vypínat_:T	VpYS---XR-AA---	18	Pred
9	počítač	počítač	NNIS4-----A----	8	Obj
10	,	,	Z:-------------	14	AuxX
11	tak	tak-3	Db-------------	14	Adv
12	jsme	být	VB-P---1P-AA---	14	AuxV
13	ho	on-1	PHZS4--3-------	14	Obj
14	dali	dát	VpMP---XR-AA---	18	Pred
15	do	do-1	RR--2----------	14	AuxP
16	opravny	opravna	NNFS2-----A----	15	Adv
17	,	,	Z:-------------	18	AuxX
18	ale	ale	J^-------------	0	Coord
19	tam	tam	Db-------------	22	Adv
20	žádnou	žádný	PWFS4----------	21	Atr
21	závadu	závada	NNFS4-----A----	22	Obj
22	nezjistili	zjistit_:W	VpMP---XR-NA---	18	Pred
23	.	.	Z:-------------	0	AuxK

1	Poradili	poradit_:T_:W	VpMP---XR-AA---	3	Pred
2	nám	já	PP-P3--1-------	1	Obj
3	ale	ale	J^-------------	0	Coord
4	,	,	Z:-------------	5	AuxX
5	abychom	aby	J,-P---1-------	1	AuxC
6	si	se_^(zvr._zájmeno/částice)	P7-X3----------	7	Adv
7	zjistili	zjistit_:W	VpMP---XR-AA---	5	Adv
8	,	,	Z:-------------	9	AuxX
9	zda	zda	J,-------------	7	AuxC
10	máme	mít	VB-P---1P-AA---	9	Obj
11	v	v-1	RR--6----------	10	AuxP
12	domácnosti	domácnost	NNFS6-----A----	11	Adv
13	dostatečně	dostatečně_^(*1ý)	Dg-------1A----	14	Adv
14	vysoké	vysoký	AANS4----1A----	16	Atr
15	elektrické	elektrický	AANS4----1A----	16	Atr
16	napětí	napětí_^(elektrické,_mechanické,_ve_vztazích)	NNNS4-----A----	10	Obj
17	.	.	Z:-------------	0	AuxK

1	Elektrikář	elektrikář	NNMS1-----A----	9	Sb
2	,	,	Z:-------------	7	AuxX
3	který	který	P4YS1----------	7	Sb
4	k	k-1	RR--3----------	7	AuxP
5	nám	já	PP-P3--1-------	4	Adv
6	poté	poté	Db-------------	7	Adv
7	přišel	přijít	VpYS---XR-AA---	1	Atr
8	,	,	Z:-------------	7	AuxX
9	zjistil	zjistit_:W	VpYS---XR-AA---	15	Pred
10	,	,	Z:-------------	15	AuxX
11	že	že	J,-------------	15	AuxC
12	tomu	ten	PDZS3----------	14	Sb
13	tak	tak-3	Db-------------	14	Adv
14	je	být	VB-S---3P-AA---	15	Pred
15	a	a-1	J^-------------	25	Coord
16	že	že	J,-------------	15	AuxC
17	to	ten	PDNS1----------	18	Obj
18	může	moci_^(mít_možnost_[něco_dělat])	VB-S---3P-AA---	16	Obj
19	elektrospotřebiče	elektrospotřebič	NNIP1-----A----	18	Obj
20	v	v-1	RR--6----------	22	AuxP
21	domácnosti	domácnost	NNFS6-----A----	20	Atr
22	poškodit	poškodit_:W	Vf--------A----	18	Obj
23	,	,	Z:-------------	18	AuxX
24	"	"	Z:-------------	15	AuxG
25	řekla	říci_:W	VpQW---XR-AA---	0	Pred
26	žena	žena	NNFS1-----A----	25	Sb
27	z	z-1	RR--2----------	26	AuxP
28	Pardubic	Pardubice_;G	NNFP2-----A----	27	Atr
29	,	,	Z:-------------	32	AuxX
30	která	který	P4FS1----------	32	Sb
31	si	se_^(zvr._zájmeno/částice)	P7-X3----------	32	AuxT
32	nepřála	přát	VpQW---XR-NA---	28	Atr
33	být	být	Vf--------A----	34	AuxV
34	jmenována	jmenovat_:T_:W	VsQW---XX-AP---	32	Obj
35	,	,	Z:-------------	36	AuxX
36	aby	aby	J,-------------	33	AuxC
37	neměla	mít	VpQW---XR-NA---	36	Obj
38	s	s-1	RR--7----------	37	AuxP
39	energetiky	energetika_^(věda)	NNFS2-----A----	38	Obj
40	problémy	problém	NNIP1-----A----	37	Obj
41	.	.	Z:-------------	0	AuxK

1	Pokud	pokud	J,-------------	9	AuxC
2	lidé	člověk	NNMP1-----A---1	3	Sb
3	pozorují	pozorovat_:T	VB-P---3P-AA---	1	Adv
4	v	v-1	RR--6----------	3	AuxP
5	domácnosti	domácnost	NNFS6-----A----	4	Adv
6	kolísání	kolísání_^(*3at)	NNNS2-----A----	5	Atr
7	napětí	napětí_^(elektrické,_mechanické,_ve_vztazích)	NNNS2-----A----	6	Atr
8	,	,	Z:-------------	1	AuxX
9	měli	mít	VpMP---XR-AA---	0	Pred
10	by	být	Vc-------------	9	AuxV
11	podle	podle-2	RR--2----------	9	AuxP
12	Pavla	Pavel-1_;Y	NNMS2-----A----	13	Atr
13	Krajáka	Krajácu	NNMS2-----A----	9	Obj
14	z	z-1	RR--2----------	13	AuxP
15	Východočeské	východočeský	AAFS2----1A----	16	Atr
16	energetiky	energetika_^(věda)	NNFS2-----A----	14	Atr
17	,	,	Z:-------------	20	AuxX
18	co	co-5_^(př._co_nejméně,_co_nevidět,_co_chvíli,_co_do_počtu,_atd.)	Db-------------	19	Adv
19	nejdříve	brzy	Dg-------3A----	20	Adv
20	informovat	informovat_:T_:W	Vf--------A----	9	Obj
21	dodavatele	dodavatel	NNMP4-----A----	20	Obj
22	energie	energie	NNFS2-----A----	21	Atr
23	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	2	AuxG
2	Má	mít	VB-S---3P-AA---	4	Adv
3	-	-	Z:-------------	4	AuxG
4	li	li	TT-------------	16	AuxC
5	někdo	někdo	PZM-1----------	6	Atr
6	podezření	podezření	NNNS1-----A----	2	Obj
7	,	,	Z:-------------	8	AuxX
8	že	že	J,-------------	6	AuxC
9	je	být	VB-S---3P-AA---	8	Obj
10	mu	on-1	PHZS3--3-------	13	Obj
11	do	do-1	RR--2----------	13	AuxP
12	domácnosti	domácnost	NNFS2-----A----	11	Adv
13	dodáváno	dodávat_:T_^(*4at)	VsNS---XX-AP---	9	Pnom
14	podpětí	podpětí	NNNS1-----A----	9	Sb
15	,	,	Z:-------------	4	AuxX
16	měl	mít	VpYS---XR-AA---	0	Pred
17	by	být	Vc-------------	16	AuxV
18	se	se_^(zvr._zájmeno/částice)	P7-X4----------	21	AuxT
19	na	na-1	RR--4----------	21	AuxP
20	nás	já	PP-P4--1-------	19	Adv
21	obrátit	obrátit_:W	Vf--------A----	16	Obj
22	.	.	Z:-------------	0	AuxK

1	Přijedeme	přijet-1_^(např._autem)	VB-P---1P-AA---	0	Pred
2	tam	tam	Db-------------	1	Adv
3	a	a-1	J^-------------	1	Coord
4	pomocí	pomocí	RR--2----------	6	AuxP
5	měření	měření_^(*3it)	NNNS2-----A----	4	Adv
6	zjistíme	zjistit_:W	VB-P---1P-AA---	3	Pred
7	,	,	Z:-------------	10	AuxX
8	v	v-1	RR--6----------	10	AuxP
9	čem	co-1	PQ--6----------	8	Adv
10	je	být	VB-S---3P-AA---	3	Pred
11	chyba	chyba	NNFS1-----A----	10	Sb
12	.	.	Z:-------------	0	AuxK

1	Pokud	pokud	J,-------------	7	AuxC
2	problém	problém	NNIS1-----A----	3	Sb
3	vzniká	vznikat_:T	VB-S---3P-AA---	1	Adv
4	naší	můj_^(přivlast.)	PSFS2-P1-------	5	Atr
5	vinou	vina	NNFS7-----A----	3	AuxP
6	,	,	Z:-------------	1	AuxX
7	máme	mít	VB-P---1P-AA---	0	Pred
8	několik	několik	Ca--4----------	7	Obj
9	způsobů	způsob	NNIP2-----A----	8	Atr
10	,	,	Z:-------------	1	AuxX
11	jak	jak-3	Db-------------	13	Adv
12	ho	on-1	PHZS4--3-------	13	Obj
13	odstranit	odstranit_:W	Vf--------A----	7	Obj
14	,	,	Z:-------------	15	AuxX
15	jako	jako	J,-------------	16	AuxY
16	například	například	Db-------------	17	AuxZ
17	zvednutím	zvednutí_^(*3out)	NNNS7-----A----	21	Adv
18	odbočky	odbočka	NNFS2-----A----	17	Atr
19	na	na-1	RR--6----------	13	AuxP
20	transformátoru	transformátor	NNIS6-----A----	19	Atr
21	nebo	nebo	J^-------------	19	Coord
22	změnou	změna	NNFS7-----A----	21	Adv
23	sítě	síť	NNFS2-----A----	22	Atr
24	.	.	Z:-------------	0	AuxK

1	Jakýkoliv	jakýkoliv	PZYS1----------	2	Atr
2	problém	problém	NNIS1-----A----	5	Sb
3	se	se_^(zvr._zájmeno/částice)	P7-X4----------	5	AuxR
4	tedy	tedy	Db-------------	5	AuxY
5	dá	dát	VB-S---3P-AA---	8	Pred
6	řešit	řešit_:T	Vf--------A----	5	Obj
7	,	,	Z:-------------	8	AuxX
8	ale	ale	J^-------------	15	Coord
9	musíme	muset	VB-P---1P-AA---	8	Pred
10	o	o-1	RR--6----------	12	AuxP
11	něm	on-1	P5ZS6--3-------	10	Obj
12	vědět	vědět	Vf--------A----	9	Obj
13	,	,	Z:-------------	8	AuxX
14	"	"	Z:-------------	8	AuxG
15	řekl	říci_:W	VpYS---XR-AA---	0	Pred
16	vedoucí	vedoucí-1_^(*8ést-1)	AGIS1-----A----	15	Sb
17	odboru	odbor_^(na_úřadě)	NNIS2-----A----	16	Atr
18	řízení	řízení_^(*4dit)	NNNS2-----A----	17	Atr
19	jakosti	jakost	NNFS2-----A----	18	Atr
20	.	.	Z:-------------	0	AuxK

1	Zjistit	zjistit_:W	Vf--------A----	5	Sb
2	podpětí	podpětí	NNNS4-----A----	1	Obj
3	v	v-1	RR--6----------	2	AuxP
4	domácnosti	domácnost	NNFS6-----A----	3	Atr
5	ale	ale	J^-------------	0	Coord
6	není	být	VB-S---3P-NA---	5	Pred
7	snadné	snadný	AANS1----1A----	6	Pnom
8	.	.	Z:-------------	0	AuxK

1	Skutečný	skutečný	AAIS1----1A----	2	Atr
2	problém	problém	NNIS1-----A----	7	Sb
3	v	v-1	RR--6----------	2	AuxP
4	domácí	domácí	AAFS6----1A----	6	Atr
5	elektrické	elektrický	AAFS6----1A----	6	Atr
6	síti	síť	NNFS6-----A----	3	Atr
7	odhalí	odhalit_:W	VB-S---3P-AA---	0	Pred
8	jen	jen-1_^(pouze)	TT-------------	9	AuxZ
9	odborník	odborník	NNMS1-----A----	7	Sb
10	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	7	AuxG
2	Pokud	pokud	J,-------------	7	AuxC
3	je	být	VB-S---3P-AA---	2	Adv
4	někde	někde	Db-------------	3	Adv
5	podpětí	podpětí	NNNS1-----A----	3	Sb
6	,	,	Z:-------------	2	AuxX
7	vadí	vadit_:T	VB-S---3P-AA---	12	Pred
8	to	ten	PDNS1----------	7	Sb
9	především	především	Db-------------	10	AuxZ
10	ledničkám	lednička	NNFP3-----A----	7	Obj
11	,	,	Z:-------------	12	AuxX
12	ale	ale	J^-------------	0	Coord
13	například	například	Db-------------	15	AuxZ
14	na	na-1	RR--6----------	18	AuxP
15	žárovkách	žárovka	NNFP6-----A----	14	Adv
16	se	se_^(zvr._zájmeno/částice)	P7-X4----------	18	AuxT
17	to	ten	PDNS1----------	18	Sb
18	nepozná	poznat_:W	VB-S---3P-NA---	10	Atr
19	.	.	Z:-------------	0	AuxK

1	Takový	takový	PDIS4----------	2	Atr
2	problém	problém	NNIS4-----A----	3	Sb
3	vzniká	vznikat_:T	VB-S---3P-AA---	0	Pred
4	například	například	Db-------------	5	AuxZ
5	tam	tam	Db-------------	3	Adv
6	,	,	Z:-------------	8	AuxX
7	kde	kde	Db-------------	8	Adv
8	mají	mít	VB-P---3P-AA---	5	Adv
9	doma	doma	Db-------------	8	Adv
10	několik	několik	Ca--4----------	8	Adv
11	let	rok	NNNP2-----A----	10	Atr
12	stále	stále_^(*1ý)	Db-------------	13	Adv
13	stejný	stejný	AAIS1----1A----	14	Atr
14	jistič	jistič	NNIS1-----A----	8	Sb
15	,	,	Z:-------------	16	AuxX
16	ale	ale	J^-------------	8	Coord
17	elektrospotřebičů	elektrospotřebič	NNIP2-----A----	21	Atr
18	mají	mít	VB-P---3P-AA---	16	Pred
19	čím	co-1	PQ--7----------	20	Adv
20	dál	daleko-1_^(dojít_dále_než_...)	Dg-------2A----	18	Adv
21	víc	hodně	Dg-------2A---1	18	Obj
22	.	.	Z:-------------	0	AuxK

1	Pak	pak	Db-------------	3	Adv
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	4	AuxT
3	může	moci_^(mít_možnost_[něco_dělat])	VB-S---3P-AA---	14	Obj
4	stát	stát-1_^(státní_útvar)	NNIS1-----A----	3	Obj
5	,	,	Z:-------------	6	AuxX
6	že	že	J,-------------	3	AuxC
7	někde	někde	Db-------------	8	Adv
8	vznikne	vzniknout_:W	VB-S---3P-AA---	6	Sb
9	problém	problém	NNIS4-----A----	8	Sb
10	s	s-1	RR--7----------	9	AuxP
11	podpětím	podpětí	NNNS7-----A----	10	Atr
12	,	,	Z:-------------	8	AuxX
13	"	"	Z:-------------	3	AuxG
14	dodává	dodávat_:T_^(*4at)	VB-S---3P-AA---	0	Pred
15	Kraják	Kraják	NNMS1-----A----	14	Sb
16	.	.	Z:-------------	0	AuxK

1	Pardubice	Pardubice_;G	NNFP1-----A----	0	ExD
2	-	-	Z:-------------	6	AuxG
3	Na	na-1	RR--6----------	6	AuxP
4	Pardubicku	Pardubicko_;G	NNNS6-----A----	3	Obj
5	se	se_^(zvr._zájmeno/částice)	P7-X4----------	6	AuxT
6	množí	množit_:T	VB-S---3P-AA---	1	Atr
7	počet	počet	NNIS1-----A----	6	Sb
8	rodin	rodina	NNFP2-----A----	7	Atr
9	,	,	Z:-------------	12	AuxX
10	které	který	P4FP1----------	12	Sb
11	si	se_^(zvr._zájmeno/částice)	P7-X3----------	12	AuxT
12	stěžují	stěžovat_:T	VB-P---3P-AA---	8	Atr
13	na	na-1	RR--4----------	12	AuxP
14	to	ten	PDNS4----------	13	Obj
15	,	,	Z:-------------	16	AuxX
16	že	že	J,-------------	14	AuxC
17	jim	on-1	PPXP3--3-------	21	Obj
18	je	být	VB-S---3P-AA---	16	Atr
19	do	do-1	RR--2----------	21	AuxP
20	domácnosti	domácnost	NNFS2-----A----	19	Adv
21	dodáváno	dodávat_:T_^(*4at)	VsNS---XX-AP---	18	Pnom
22	malé	malý	AANS1----1A----	23	Atr
23	množství	množství	NNNS1-----A----	21	Sb
24	elektrické	elektrický	AAFS2----1A----	25	Atr
25	energie	energie	NNFS2-----A----	23	Atr
26	.	.	Z:-------------	0	AuxK

1	Nejcitlivěji	citlivě_^(*1ý)	Dg-------3A----	11	Adv
2	na	na-1	RR--4----------	13	AuxP
3	takzvané	takzvaný	AANS4----1A----	4	Atr
4	podpětí	podpětí	NNNS4-----A----	2	Adv
5	,	,	Z:-------------	7	AuxX
6	které	který	P4NS1----------	11	Obj
7	může	moci_^(mít_možnost_[něco_dělat])	VB-S---3P-AA---	4	Atr
8	elektrospotřebiče	elektrospotřebič	NNIP1-----A----	7	Obj
9	v	v-1	RR--6----------	11	AuxP
10	domácnosti	domácnost	NNFS6-----A----	9	Atr
11	poškozovat	poškozovat_:T	Vf--------A----	7	Obj
12	,	,	Z:-------------	7	AuxX
13	reagují	reagovat_:T	VB-P---3P-AA---	0	Pred
14	počítače	počítač	NNIP1-----A----	15	Sb
15	a	a-1	J^-------------	13	Coord
16	ledničky	lednička	NNFP1-----A----	15	Sb
17	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	8	AuxG
2	Pořád	pořád	Db-------------	8	Adv
3	se	se_^(zvr._zájmeno/částice)	P7-X4----------	8	AuxT
4	nám	já	PP-P3--1-------	8	Obj
5	sám	sám_^(samotný)	PLYS1----------	8	AtvV
6	od	od-1	RR--2----------	8	AuxP
7	sebe	se_^(zvr._zájmeno/částice)	P6-X2----------	6	Adv
8	vypínal	vypínat_:T	VpYS---XR-AA---	18	Pred
9	počítač	počítač	NNIS4-----A----	8	Obj
10	,	,	Z:-------------	14	AuxX
11	tak	tak-3	Db-------------	14	Adv
12	jsme	být	VB-P---1P-AA---	14	AuxV
13	ho	on-1	PHZS4--3-------	14	Obj
14	dali	dát	VpMP---XR-AA---	18	Pred
15	do	do-1	RR--2----------	14	AuxP
16	opravny	opravna	NNFS2-----A----	15	Adv
17	,	,	Z:-------------	18	AuxX
18	ale	ale	J^-------------	0	Coord
19	tam	tam	Db-------------	22	Adv
20	žádnou	žádný	PWFS4----------	21	Atr
21	závadu	závada	NNFS4-----A----	22	Obj
22	nezjistili	zjistit_:W	VpMP---XR-NA---	18	Pred
23	.	.	Z:-------------	0	AuxK

1	Poradili	poradit_:T_:W	VpMP---XR-AA---	3	Pred
2	nám	já	PP-P3--1-------	1	Obj
3	ale	ale	J^-------------	0	Coord
4	,	,	Z:-------------	5	AuxX
5	abychom	aby	J,-P---1-------	1	AuxC
6	si	se_^(zvr._zájmeno/částice)	P7-X3----------	7	Adv
7	zjistili	zjistit_:W	VpMP---XR-AA---	5	Adv
8	,	,	Z:-------------	9	AuxX
9	zda	zda	J,-------------	7	AuxC
10	máme	mít	VB-P---1P-AA---	9	Obj
11	v	v-1	RR--6----------	10	AuxP
12	domácnosti	domácnost	NNFS6-----A----	11	Adv
13	dostatečně	dostatečně_^(*1ý)	Dg-------1A----	14	Adv
14	vysoké	vysoký	AANS4----1A----	16	Atr
15	elektrické	elektrický	AANS4----1A----	16	Atr
16	napětí	napětí_^(elektrické,_mechanické,_ve_vztazích)	NNNS4-----A----	10	Obj
17	.	.	Z:-------------	0	AuxK

1	Elektrikář	elektrikář	NNMS1-----A----	9	Sb
2	,	,	Z:-------------	7	AuxX
3	který	který	P4YS1----------	7	Sb
4	k	k-1	RR--3----------	7	AuxP
5	nám	já	PP-P3--1-------	4	Adv
6	poté	poté	Db-------------	7	Adv
7	přišel	přijít	VpYS---XR-AA---	1	Atr
8	,	,	Z:-------------	7	AuxX
9	zjistil	zjistit_:W	VpYS---XR-AA---	15	Pred
10	,	,	Z:-------------	15	AuxX
11	že	že	J,-------------	15	AuxC
12	tomu	ten	PDZS3----------	14	Sb
13	tak	tak-3	Db-------------	14	Adv
14	je	být	VB-S---3P-AA---	15	Pred
15	a	a-1	J^-------------	25	Coord
16	že	že	J,-------------	15	AuxC
17	to	ten	PDNS1----------	18	Obj
18	může	moci_^(mít_možnost_[něco_dělat])	VB-S---3P-AA---	16	Obj
19	elektrospotřebiče	elektrospotřebič	NNIP1-----A----	18	Obj
20	v	v-1	RR--6----------	22	AuxP
21	domácnosti	domácnost	NNFS6-----A----	20	Atr
22	poškodit	poškodit_:W	Vf--------A----	18	Obj
23	,	,	Z:-------------	18	AuxX
24	"	"	Z:-------------	15	AuxG
25	řekla	říci_:W	VpQW---XR-AA---	0	Pred
26	žena	žena	NNFS1-----A----	25	Sb
27	z	z-1	RR--2----------	26	AuxP
28	Pardubic	Pardubice_;G	NNFP2-----A----	27	Atr
29	,	,	Z:-------------	32	AuxX
30	která	který	P4FS1----------	32	Sb
31	si	se_^(zvr._zájmeno/částice)	P7-X3----------	32	AuxT
32	nepřála	přát	VpQW---XR-NA---	28	Atr
33	být	být	Vf--------A----	34	AuxV
34	jmenována	jmenovat_:T_:W	VsQW---XX-AP---	32	Obj
35	,	,	Z:-------------	36	AuxX
36	aby	aby	J,-------------	33	AuxC
37	neměla	mít	VpQW---XR-NA---	36	Obj
38	s	s-1	RR--7----------	37	AuxP
39	energetiky	energetika_^(věda)	NNFS2-----A----	38	Obj
40	problémy	problém	NNIP1-----A----	37	Obj
41	.	.	Z:-------------	0	AuxK

1	Pokud	pokud	J,-------------	9	AuxC
2	lidé	člověk	NNMP1-----A---1	3	Sb
3	pozorují	pozorovat_:T	VB-P---3P-AA---	1	Adv
4	v	v-1	RR--6----------	3	AuxP
5	domácnosti	domácnost	NNFS6-----A----	4	Adv
6	kolísání	kolísání_^(*3at)	NNNS2-----A----	5	Atr
7	napětí	napětí_^(elektrické,_mechanické,_ve_vztazích)	NNNS2-----A----	6	Atr
8	,	,	Z:-------------	1	AuxX
9	měli	mít	VpMP---XR-AA---	0	Pred
10	by	být	Vc-------------	9	AuxV
11	podle	podle-2	RR--2----------	9	AuxP
12	Pavla	Pavel-1_;Y	NNMS2-----A----	13	Atr
13	Krajáka	Krajácu	NNMS2-----A----	9	Obj
14	z	z-1	RR--2----------	13	AuxP
15	Východočeské	východočeský	AAFS2----1A----	16	Atr
16	energetiky	energetika_^(věda)	NNFS2-----A----	14	Atr
17	,	,	Z:-------------	20	AuxX
18	co	co-5_^(př._co_nejméně,_co_nevidět,_co_chvíli,_co_do_počtu,_atd.)	Db-------------	19	Adv
19	nejdříve	brzy	Dg-------3A----	20	Adv
20	informovat	informovat_:T_:W	Vf--------A----	9	Obj
21	dodavatele	dodavatel	NNMP4-----A----	20	Obj
22	energie	energie	NNFS2-----A----	21	Atr
23	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	2	AuxG
2	Má	mít	VB-S---3P-AA---	4	Adv
3	-	-	Z:-------------	4	AuxG
4	li	li	TT-------------	16	AuxC
5	někdo	někdo	PZM-1----------	6	Atr
6	podezření	podezření	NNNS1-----A----	2	Obj
7	,	,	Z:-------------	8	AuxX
8	že	že	J,-------------	6	AuxC
9	je	být	VB-S---3P-AA---	8	Obj
10	mu	on-1	PHZS3--3-------	13	Obj
11	do	do-1	RR--2----------	13	AuxP
12	domácnosti	domácnost	NNFS2-----A----	11	Adv
13	dodáváno	dodávat_:T_^(*4at)	VsNS---XX-AP---	9	Pnom
14	podpětí	podpětí	NNNS1-----A----	9	Sb
15	,	,	Z:-------------	4	AuxX
16	měl	mít	VpYS---XR-AA---	0	Pred
17	by	být	Vc-------------	16	AuxV
18	se	se_^(zvr._zájmeno/částice)	P7-X4----------	21	AuxT
19	na	na-1	RR--4----------	21	AuxP
20	nás	já	PP-P4--1-------	19	Adv
21	obrátit	obrátit_:W	Vf--------A----	16	Obj
22	.	.	Z:-------------	0	AuxK

1	Přijedeme	přijet-1_^(např._autem)	VB-P---1P-AA---	0	Pred
2	tam	tam	Db-------------	1	Adv
3	a	a-1	J^-------------	1	Coord
4	pomocí	pomocí	RR--2----------	6	AuxP
5	měření	měření_^(*3it)	NNNS2-----A----	4	Adv
6	zjistíme	zjistit_:W	VB-P---1P-AA---	3	Pred
7	,	,	Z:-------------	10	AuxX
8	v	v-1	RR--6----------	10	AuxP
9	čem	co-1	PQ--6----------	8	Adv
10	je	být	VB-S---3P-AA---	3	Pred
11	chyba	chyba	NNFS1-----A----	10	Sb
12	.	.	Z:-------------	0	AuxK

1	Pokud	pokud	J,-------------	7	AuxC
2	problém	problém	NNIS1-----A----	3	Sb
3	vzniká	vznikat_:T	VB-S---3P-AA---	1	Adv
4	naší	můj_^(přivlast.)	PSFS2-P1-------	5	Atr
5	vinou	vina	NNFS7-----A----	3	AuxP
6	,	,	Z:-------------	1	AuxX
7	máme	mít	VB-P---1P-AA---	0	Pred
8	několik	několik	Ca--4----------	7	Obj
9	způsobů	způsob	NNIP2-----A----	8	Atr
10	,	,	Z:-------------	1	AuxX
11	jak	jak-3	Db-------------	13	Adv
12	ho	on-1	PHZS4--3-------	13	Obj
13	odstranit	odstranit_:W	Vf--------A----	7	Obj
14	,	,	Z:-------------	15	AuxX
15	jako	jako	J,-------------	16	AuxY
16	například	například	Db-------------	17	AuxZ
17	zvednutím	zvednutí_^(*3out)	NNNS7-----A----	21	Adv
18	odbočky	odbočka	NNFS2-----A----	17	Atr
19	na	na-1	RR--6----------	13	AuxP
20	transformátoru	transformátor	NNIS6-----A----	19	Atr
21	nebo	nebo	J^-------------	19	Coord
22	změnou	změna	NNFS7-----A----	21	Adv
23	sítě	síť	NNFS2-----A----	22	Atr
24	.	.	Z:-------------	0	AuxK

1	Jakýkoliv	jakýkoliv	PZYS1----------	2	Atr
2	problém	problém	NNIS1-----A----	5	Sb
3	se	se_^(zvr._zájmeno/částice)	P7-X4----------	5	AuxR
4	tedy	tedy	Db-------------	5	AuxY
5	dá	dát	VB-S---3P-AA---	8	Pred
6	řešit	řešit_:T	Vf--------A----	5	Obj
7	,	,	Z:-------------	8	AuxX
8	ale	ale	J^-------------	15	Coord
9	musíme	muset	VB-P---1P-AA---	8	Pred
10	o	o-1	RR--6----------	12	AuxP
11	něm	on-1	P5ZS6--3-------	10	Obj
12	vědět	vědět	Vf--------A----	9	Obj
13	,	,	Z:-------------	8	AuxX
14	"	"	Z:-------------	8	AuxG
15	řekl	říci_:W	VpYS---XR-AA---	0	Pred
16	vedoucí	vedoucí-1_^(*8ést-1)	AGIS1-----A----	15	Sb
17	odboru	odbor_^(na_úřadě)	NNIS2-----A----	16	Atr
18	řízení	řízení_^(*4dit)	NNNS2-----A----	17	Atr
19	jakosti	jakost	NNFS2-----A----	18	Atr
20	.	.	Z:-------------	0	AuxK

1	Zjistit	zjistit_:W	Vf--------A----	5	Sb
2	podpětí	podpětí	NNNS4-----A----	1	Obj
3	v	v-1	RR--6----------	2	AuxP
4	domácnosti	domácnost	NNFS6-----A----	3	Atr
5	ale	ale	J^-------------	0	Coord
6	není	být	VB-S---3P-NA---	5	Pred
7	snadné	snadný	AANS1----1A----	6	Pnom
8	.	.	Z:-------------	0	AuxK

1	Skutečný	skutečný	AAIS1----1A----	2	Atr
2	problém	problém	NNIS1-----A----	7	Sb
3	v	v-1	RR--6----------	2	AuxP
4	domácí	domácí	AAFS6----1A----	6	Atr
5	elektrické	elektrický	AAFS6----1A----	6	Atr
6	síti	síť	NNFS6-----A----	3	Atr
7	odhalí	odhalit_:W	VB-S---3P-AA---	0	Pred
8	jen	jen-1_^(pouze)	TT-------------	9	AuxZ
9	odborník	odborník	NNMS1-----A----	7	Sb
10	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	7	AuxG
2	Pokud	pokud	J,-------------	7	AuxC
3	je	být	VB-S---3P-AA---	2	Adv
4	někde	někde	Db-------------	3	Adv
5	podpětí	podpětí	NNNS1-----A----	3	Sb
6	,	,	Z:-------------	2	AuxX
7	vadí	vadit_:T	VB-S---3P-AA---	12	Pred
8	to	ten	PDNS1----------	7	Sb
9	především	především	Db-------------	10	AuxZ
10	ledničkám	lednička	NNFP3-----A----	7	Obj
11	,	,	Z:-------------	12	AuxX
12	ale	ale	J^-------------	0	Coord
13	například	například	Db-------------	15	AuxZ
14	na	na-1	RR--6----------	18	AuxP
15	žárovkách	žárovka	NNFP6-----A----	14	Adv
16	se	se_^(zvr._zájmeno/částice)	P7-X4----------	18	AuxT
17	to	ten	PDNS1----------	18	Sb
18	nepozná	poznat_:W	VB-S---3P-NA---	10	Atr
19	.	.	Z:-------------	0	AuxK

1	Takový	takový	PDIS4----------	2	Atr
2	problém	problém	NNIS4-----A----	3	Sb
3	vzniká	vznikat_:T	VB-S---3P-AA---	0	Pred
4	například	například	Db-------------	5	AuxZ
5	tam	tam	Db-------------	3	Adv
6	,	,	Z:-------------	8	AuxX
7	kde	kde	Db-------------	8	Adv
8	mají	mít	VB-P---3P-AA---	5	Adv
9	doma	doma	Db-------------	8	Adv
10	několik	několik	Ca--4----------	8	Adv
11	let	rok	NNNP2-----A----	10	Atr
12	stále	stále_^(*1ý)	Db-------------	13	Adv
13	stejný	stejný	AAIS1----1A----	14	Atr
14	jistič	jistič	NNIS1-----A----	8	Sb
15	,	,	Z:-------------	16	AuxX
16	ale	ale	J^-------------	8	Coord
17	elektrospotřebičů	elektrospotřebič	NNIP2-----A----	21	Atr
18	mají	mít	VB-P---3P-AA---	16	Pred
19	čím	co-1	PQ--7----------	20	Adv
20	dál	daleko-1_^(dojít_dále_než_...)	Dg-------2A----	18	Adv
21	víc	hodně	Dg-------2A---1	18	Obj
22	.	.	Z:-------------	0	AuxK

1	Pak	pak	Db-------------	3	Adv
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	4	AuxT
3	může	moci_^(mít_možnost_[něco_dělat])	VB-S---3P-AA---	14	Obj
4	stát	stát-1_^(státní_útvar)	NNIS1-----A----	3	Obj
5	,	,	Z:-------------	6	AuxX
6	že	že	J,-------------	3	AuxC
7	někde	někde	Db-------------	8	Adv
8	vznikne	vzniknout_:W	VB-S---3P-AA---	6	Sb
9	problém	problém	NNIS4-----A----	8	Sb
10	s	s-1	RR--7----------	9	AuxP
11	podpětím	podpětí	NNNS7-----A----	10	Atr
12	,	,	Z:-------------	8	AuxX
13	"	"	Z:-------------	3	AuxG
14	dodává	dodávat_:T_^(*4at)	VB-S---3P-AA---	0	Pred
15	Kraják	Kraják	NNMS1-----A----	14	Sb
16	.	.	Z:-------------	0	AuxK

</TEXT>
</DOC>
