<DOC>
<DOCID>MF-20020114191</DOCID>
<DOCNO>MF-20020114191</DOCNO>
<DATE>01/14/02</DATE>
<TITLE>
1	Koruna	koruna	NNFS1-----A----	4	ExD
2	-	-	Z:-------------	4	Apos
3	dolar	dolar_;b	NNIS1-----A----	4	Sb
4	:	:	Z:-------------	0	Apos
5	největší	velký	AAIS1----3A----	6	Atr
6	růst	růst-1	NNIS1-----A----	4	Sb
7	ze	z-1	RV--2----------	6	AuxP
8	všech	všechen	PLXP2----------	9	Atr
9	měn	měna	NNFP2-----A----	7	Atr

</TITLE>
<HEADING>
1	Analýza	analýza	NNFS1-----A----	0	Pred

</HEADING>
<GEOGRAPHY>Praha</GEOGRAPHY>
<TEXT>
1	Sílící	sílící_^(získávat_sílu;_přech.)_(*3it)	AGFS1-----A----	2	Atr
2	měna	měna	NNFS1-----A----	0	ExD
3	,	,	Z:-------------	7	AuxX
4	sílící	sílící_^(získávat_sílu;_přech.)_(*3it)	AGNS1-----A----	5	Atr
5	hospodářství	hospodářství	NNNS1-----A----	6	Sb
6	,	,	Z:-------------	7	Coord
7	sílící	sílící_^(získávat_sílu;_přech.)_(*3it)	AGFS1-----A----	2	Atr
8	životní	životní_^(souvisí_se_životem;_prostředí,...)	AAFS4----1A----	9	Atr
9	úroveň	úroveň	NNFS4-----A----	7	Obj
10	.	.	Z:-------------	0	AuxK

1	Sice	sice_^(spojka/příslovce;_připouští_se_určitá_fakta)	Db-------------	4	AuxY
2	ne	ne	TT-------------	3	AuxZ
3	vždy	vždy	Db-------------	4	Adv
4	a	a-1	J^-------------	0	Coord
5	doslova	doslova	Db-------------	4	Adv
6	.	.	Z:-------------	0	AuxK

1	Důvěra	důvěra	NNFS1-----A----	6	Sb
2	v	v-1	RR--4----------	1	AuxP
3	měnu	měna	NNFS4-----A----	2	Atr
4	však	však	J^-------------	0	Coord
5	významně	významně_^(*1ý)	Dg-------1A----	6	Adv
6	souvisí	souviset_:T	VB-S---3P-AA---	4	Pred
7	s	s-1	RR--7----------	6	AuxP
8	vyhlídkami	vyhlídka	NNFP7-----A----	7	Obj
9	na	na-1	RR--4----------	8	AuxP
10	slibnou	slibný	AAFS4----1A----	11	Atr
11	budoucnost	budoucnost	NNFS4-----A----	9	Atr
12	ekonomiky	ekonomika	NNFS2-----A----	11	Atr
13	.	.	Z:-------------	0	AuxK

1	Česká	Český-1_;G_^(používá_se_i_pro_jména_org.,_výrobků_atd.)	AAFS1----1A----	2	Atr
2	koruna	koruna	NNFS1-----A----	4	Sb
3	loni	vloni_,h	Db------------1	4	Adv
4	posílila	posílit_:W	VpQW---XR-AA---	0	Pred
5	proti	proti-1	RR--3----------	4	AuxP
6	americkému	americký	AAIS3----1A----	7	Atr
7	dolaru	dolar_;b	NNIS3-----A----	5	Obj
8	nejvíc	hodně	Dg-------3A---1	4	Adv
9	ze	z-1	RV--2----------	8	AuxP
10	všech	všechen	PLXP2----------	12	Atr
11	světových	světový	AAFP2----1A----	12	Atr
12	měn	měna	NNFP2-----A----	9	Adv
13	.	.	Z:-------------	0	AuxK

1	Na	na-1	RR--4----------	4	AuxP
2	Silvestra	Silvestr_;Y	NNMS4-----A----	1	Adv
3	2001	2001	C=-------------	2	Atr
4	byl	být	VpYS---XR-AA---	22	Pred
5	sice	sice_^(spojka/příslovce;_připouští_se_určitá_fakta)	Db-------------	22	AuxY
6	pro	pro-1	RR--4----------	4	AuxP
7	Čechy	Čech-1_;E	NNMP4-----A----	6	Adv
8	dolar	dolar_;b	NNIS1-----A----	7	Atr
9	jen	jen-1_^(pouze)	TT-------------	11	AuxZ
10	o	o-1	RR--4----------	15	AuxP
11	1	1	NNMS1-----A----	10	Obj
12	,	,	Z:-------------	15	AuxX
13	55	55	C=-------------	11	ExD
14	koruny	koruna	NNFS2-----A----	13	Atr
15	levnější	levný	AAFS1----2A----	7	Atr
16	než	než-2	J,-------------	15	AuxC
17	před	před-1	RR--7----------	16	AuxP
18	rokem	rok	NNIS7-----A----	17	Adv
19	,	,	Z:-------------	22	AuxX
20	i	i-1	J^-------------	21	AuxY
21	to	ten	PDNS1----------	23	Sb
22	však	však	J^-------------	0	Coord
23	stačilo	stačit_:T	VpNS---XR-AA---	22	Pred
24	na	na-1	RR--4----------	23	AuxP
25	světové	světový	AANS4----1A----	26	Atr
26	prvenství	prvenství	NNNS4-----A----	24	Adv
27	.	.	Z:-------------	0	AuxK

1	Navzdory	navzdory	Db-------------	3	AuxP
2	recesi	recese	NNFS4-----A----	1	Adv
3	,	,	Z:-------------	8	AuxX
4	na	na-1	RR--6----------	8	AuxP
5	jejímž	jenž_^(který...[ve_vedl._větě])	P1ZS6FS3-------	6	Atr
6	prahu	práh	NNIS6-----A----	4	Adv
7	se	se_^(zvr._zájmeno/částice)	P7-X4----------	8	AuxT
8	ocitly	ocitnout_:W	VpTP---XR-AA--1	0	Pred
9	Spojené	spojený_^(*3it)	AAIP1----1A----	10	Atr
10	státy	stát-1_^(státní_útvar)	NNIP1-----A----	8	Sb
11	,	,	Z:-------------	17	AuxX
12	totiž	totiž	Db-------------	17	AuxY
13	dolar	dolar_;b	NNIS4-----A----	17	Sb
14	proti	proti-1	RR--3----------	17	AuxP
15	většině	většina	NNFS3-----A----	14	Atr
16	platidel	platidlo	NNNP2-----A----	15	Atr
17	zpevnil	zpevnit_:W	VpYS---XR-AA---	10	Atr
18	.	.	Z:-------------	0	AuxK

1	Euro	euro_;b_^(evr._měna)	NNNS1-----A----	5	ExD
2	,	,	Z:-------------	5	AuxX
3	britskou	britský	AAFS4----1A----	4	Atr
4	libru	libra-1_^(jednotka_britské_měny)	NNFS4-----A----	5	Obj
5	a	a-1	J^-------------	0	Coord
6	japonský	japonský	AAIS1----1A----	5	Obj
7	jen	jen-1_^(pouze)	TT-------------	8	AuxZ
8	nevyjímaje	vyjímat_:T	VeYS------N----	1	Atv
9	.	.	Z:-------------	0	AuxK

1	Kromě	kromě	RR--2----------	7	AuxP
2	koruny	koruna	NNFS2-----A----	1	Adv
3	si	se_^(zvr._zájmeno/částice)	P7-X3----------	7	Adv
4	z	z-1	RR--2----------	7	AuxP
5	evropských	evropský	AAFP2----1A----	6	Atr
6	měn	měna	NNFP2-----A----	4	Atr
7	polepšil	polepšit_:W	VpYS---XR-AA---	11	Atr
8	ještě	ještě	Db-------------	10	AuxZ
9	maďarský	maďarský	AAIS1----1A----	10	Atr
10	forint	forint	NNIS1-----A----	11	Sb
11	a	a-1	J^-------------	0	Coord
12	polský	polský	AAIS1----1A----	13	Atr
13	zlotý	zlotý_^(pol._měna)	NNIS1-----A----	11	Sb
14	.	.	Z:-------------	0	AuxK

1	Proti	proti-1	RR--3----------	3	AuxP
2	euru	euro_;b_^(evr._měna)	NNNS3-----A----	1	Adv
3	je	být	VB-S---3P-AA---	0	Pred
4	koruna	koruna	NNFS1-----A----	3	Sb
5	již	již	Db-------------	6	AuxZ
6	několik	několik	Ca--1----------	9	Adv
7	měsíců	měsíc	NNIP2-----A----	6	Atr
8	velmi	velmi	Db-------------	9	Adv
9	pevná	pevný	AANP1----1A----	3	Pnom
10	kvůli	kvůli	RR--3----------	9	AuxP
11	očekávání	očekávání_^(*3at)	NNNS3-----A----	10	Adv
12	masivních	masivní	AAIP2----1A----	13	Atr
13	příjmů	příjem	NNIP2-----A----	11	Atr
14	z	z-1	RR--2----------	13	AuxP
15	privatizace	privatizace	NNFS2-----A----	14	Atr
16	strategických	strategický	AAFP2----1A----	17	Atr
17	firem	firma	NNFP2-----A----	15	Atr
18	.	.	Z:-------------	0	AuxK

1	Vzestup	vzestup	NNIS1-----A----	7	Obj
2	proti	proti-1	RR--3----------	1	AuxP
3	dolaru	dolar_;b	NNIS3-----A----	2	Atr
4	se	se_^(zvr._zájmeno/částice)	P7-X4----------	8	AuxR
5	takto	takto	Db-------------	6	Adv
6	jednoduše	jednoduše	Dg-------1A----	8	Adv
7	vysvětlit	vysvětlit_:W	Vf--------A----	8	Obj
8	nedá	dát	VB-S---3P-NA---	0	Pred
9	.	.	Z:-------------	0	AuxK

1	Kupci	kupec	NNMP1-----A----	14	Sb
2	českých	český	AAFP2----1A----	3	Atr
3	firem	firma	NNFP2-----A----	1	Atr
4	,	,	Z:-------------	7	AuxX
5	kteří	který	P4MP1----------	7	Sb
6	budou	být	VB-P---3F-AA---	7	AuxV
7	potřebovat	potřebovat_:T	Vf--------A----	12	Obj
8	koruny	koruna	NNFP4-----A----	7	Obj
9	na	na-1	RR--6----------	8	AuxP
10	zaplacení	zaplacení_^(*4tit)	NNNS6-----A----	9	Atr
11	státu	stát-1_^(státní_útvar)	NNIS2-----A----	10	Atr
12	,	,	Z:-------------	13	Coord
13	totiž	totiž	Db-------------	14	AuxY
14	přicházejí	přicházet_:T	VB-P---3P-AA---	0	Pred
15	ze	z-1	RV--2----------	14	AuxP
16	zemí	země	NNFP2-----A----	15	Adv
17	eura	euro_;b_^(evr._měna)	NNNS2-----A----	16	Atr
18	.	.	Z:-------------	0	AuxK

1	A	a-1	J^-------------	0	Coord
2	právě	právě	Db-------------	3	AuxZ
3	společnou	společný	AAFS4----1A----	5	Atr
4	evropskou	evropský	AAFS4----1A----	5	Atr
5	měnu	měna	NNFS4-----A----	1	ExD
6	,	,	Z:-------------	9	Coord
7	nikoliv	nikoliv	Db-------------	8	AuxZ
8	dolary	dolar_;b	NNIP4-----A----	6	ExD
9	,	,	Z:-------------	3	AuxX
10	vymění	vyměnit_:W	VB-P---3P-AA---	1	Pred
11	na	na-1	RR--4----------	10	AuxP
12	koruny	koruna	NNFP4-----A----	11	Obj
13	.	.	Z:-------------	0	AuxK

1	Proti	proti-1	RR--3----------	5	AuxP
2	dolaru	dolar_;b	NNIS3-----A----	1	Adv
3	tedy	tedy	Db-------------	5	AuxY
4	koruna	koruna	NNFS1-----A----	5	Sb
5	zpevňuje	zpevňovat_:T	VB-S---3P-AA---	0	Pred
6	pravděpodobně	pravděpodobně_^(*1ý)	Dg-------1A----	5	AuxY
7	proto	proto-2_^(dal_mu_co_proto,_tak_proto!)	Db-------------	5	Adv
8	,	,	Z:-------------	9	AuxX
9	že	že	J,-------------	5	AuxC
10	investoři	investor	NNMP1-----A----	11	Sb
11	mají	mít	VB-P---3P-AA---	9	Obj
12	,	,	Z:-------------	13	AuxX
13	navzdory	navzdory	Db-------------	11	AuxP
14	všem	všechen	PLXP3----------	15	Atr
15	problémům	problém	NNIP3-----A----	13	Adv
16	s	s-1	RR--7----------	15	AuxP
17	velkými	velký	AAIP7----1A----	19	Atr
18	státními	státní	AAIP7----1A----	19	Atr
19	dluhy	dluh	NNIP7-----A----	16	Atr
20	,	,	Z:-------------	16	Apos
21	důvěru	důvěra	NNFS4-----A----	11	Obj
22	v	v-1	RR--4----------	21	AuxP
23	českou	český	AAFS4----1A----	24	Atr
24	ekonomiku	ekonomika	NNFS4-----A----	22	Atr
25	.	.	Z:-------------	0	AuxK

1	Pevnější	pevný	AAFS1----2A----	2	Atr
2	koruna	koruna	NNFS1-----A----	5	Sb
3	proti	proti-1	RR--3----------	2	AuxP
4	dolaru	dolar_;b	NNIS3-----A----	3	Atr
5	má	mít	VB-S---3P-AA---	0	Pred
6	navíc	navíc	Db-------------	5	Adv
7	na	na-1	RR--4----------	5	AuxP
8	ekonomiku	ekonomika	NNFS4-----A----	9	Adv
9	a	a-1	J^-------------	7	Coord
10	životní	životní_^(souvisí_se_životem;_prostředí,...)	AAFS4----1A----	11	Atr
11	úroveň	úroveň	NNFS4-----A----	9	Obj
12	lidí	člověk	NNMP2-----A----	11	Atr
13	příznivější	příznivý	AAIS1----2A----	14	Atr
14	dopad	dopad	NNIS1-----A----	12	Atr
15	.	.	Z:-------------	0	AuxK

1	V	v-1	RR--6----------	4	AuxP
2	euru	euro_;b_^(evr._měna)	NNNS6-----A----	1	Adv
3	spíš	spíše	Dg-------2A----	4	Adv
4	vyvážíme	vyvážet_:T_^(zboží_přes_hranice)	VB-P---1P-AA---	8	Obj
5	,	,	Z:-------------	4	AuxX
6	v	v-1	RR--6----------	8	AuxP
7	dolaru	dolar_;b	NNIS6-----A----	6	Adv
8	dovážíme	dovážet_:T_^(z_ciziny)	VB-P---1P-AA---	0	Pred
9	.	.	Z:-------------	0	AuxK

1	A	a-1	J^-------------	0	Coord
2	tak	tak-3	Db-------------	1	AuxY
3	pevná	pevný	AAFS1----1A----	5	Atr
4	česká	český	AAFS1----1A----	5	Atr
5	měna	měna	NNFS1-----A----	6	Sb
6	zlevňuje	zlevňovat_:T	VB-S---3P-AA---	1	Pred
7	řadu	řada_^(linka,zástup,pořadí,...)	NNFS4-----A----	6	Obj
8	věcí	věc	NNFP2-----A----	7	Atr
9	.	.	Z:-------------	0	AuxK

1	Má	mít	VB-S---3P-AA---	0	Pred
2	spolu	spolu	Db-------------	3	AuxP
3	s	s-1	RR--7----------	1	AuxP
4	nízkými	nízký	AAFP7----1A----	5	Atr
5	cenami	cena-1_^(v_penězích,_naturální,_nevyčíslitelná,...)	NNFP7-----A----	3	Obj
6	ropy	ropa	NNFS2-----A----	5	Atr
7	významnou	významný	AAFS4----1A----	8	Atr
8	zásluhu	zásluha	NNFS4-----A----	1	Obj
9	na	na-1	RR--6----------	8	AuxP
10	tom	ten	PDZS6----------	9	Atr
11	,	,	Z:-------------	12	AuxX
12	že	že	J,-------------	10	AuxC
13	litr	l-1`litr	NNIS1-----A----	15	Sb
14	benzinu	benzín	NNIS2-----A----	13	Atr
15	je	být	VB-S---3P-AA---	12	Obj
16	dnes	dnes	Db-------------	15	Adv
17	o	o-1	RR--4----------	22	AuxP
18	čtyři	čtyři`4	ClXP4----------	19	Atr
19	až	až-2_^(přijde,_až_to_dodělá)	J,-------------	17	Coord
20	pět	pět-1`5	Cn-S4----------	19	ExD
21	korun	koruna	NNFP2-----A----	20	Atr
22	levnější	levný	AAIS1----2A----	15	Pnom
23	než	než-2	J,-------------	22	AuxC
24	na	na-1	RR--6----------	23	AuxP
25	začátku	začátek	NNIS6-----A----	24	Adv
26	roku	rok	NNIS2-----A---1	25	Atr
27	2001	2001	C=-------------	26	Atr
28	.	.	Z:-------------	0	AuxK

1	Za	za-1	RR--4----------	3	AuxP
2	dolary	dolar_;b	NNIP4-----A----	1	Obj
3	dovážíme	dovážet_:T_^(z_ciziny)	VB-P---1P-AA---	9	Pred
4	také	také_^(rovněž)	Db-------------	3	Adv
5	plyn	plyn	NNIS4-----A----	3	Sb
6	,	,	Z:-------------	9	AuxX
7	u	u-1	RR--2----------	10	AuxP
8	něj	on-1	P5ZS2--3-------	7	Atr
9	však	však	J^-------------	0	Coord
10	není	být	VB-S---3P-NA---	9	Pred
11	příznivý	příznivý	AAIS1----1A----	12	Atr
12	dopad	dopad	NNIS1-----A----	17	Obj
13	výhodného	výhodný	AAIS2----1A----	14	Atr
14	kurzu	kurs-1_^(měny,akcií,...)	NNIS2-----A----	12	Atr
15	tak	tak-3	Db-------------	16	Adv
16	rychle	rychle_^(*1ý)	Dg-------1A----	17	Adv
17	vidět	vidět	Vf--------A----	10	Pnom
18	.	.	Z:-------------	0	AuxK

1	Smlouvy	smlouva	NNFP1-----A----	5	Sb
2	na	na-1	RR--4----------	1	AuxP
3	nákup	nákup	NNIS4-----A----	2	Atr
4	plynu	plyn	NNIS2-----A----	3	Atr
5	jsou	být	VB-P---3P-AA---	7	Pred
6	dlouhodobé	dlouhodobý	AAFP1----1A----	5	Pnom
7	,	,	Z:-------------	0	Coord
8	ceny	cena-1_^(v_penězích,_naturální,_nevyčíslitelná,...)	NNFP1-----A----	10	Sb
9	navíc	navíc	Db-------------	10	Adv
10	určuje	určovat_:T	VB-S---3P-AA---	7	Pred
11	regulátor	regulátor	NNMS1-----A----	10	Sb
12	.	.	Z:-------------	0	AuxK

1	Také	také_^(rovněž)	Db-------------	2	AuxZ
2	obchodníci	obchodník	NNMP1-----A----	7	Sb
3	s	s-1	RR--7----------	2	AuxP
4	elektronikou	elektronika	NNFS7-----A----	5	Obj
5	a	a-1	J^-------------	3	Coord
6	počítači	počítač	NNIS3-----A----	7	Obj
7	potvrzují	potvrzovat_:T	VB-P---3P-AA---	0	Pred
8	,	,	Z:-------------	9	AuxX
9	že	že	J,-------------	7	AuxC
10	ceny	cena-1_^(v_penězích,_naturální,_nevyčíslitelná,...)	NNFP1-----A----	13	Sb
11	jejich	jeho_^(přivlast.)	PSXXXXP3-------	12	Atr
12	zboží	zboží	NNNS2-----A----	10	Atr
13	jsou	být	VB-P---3P-AA---	9	Obj
14	nižší	nízký	AAFP1----2A----	13	Pnom
15	než	než-1_,h_^(jenom,_př._byl_tam_než_Pavel)	TT-------------	14	AuxY
16	před	před-1	RR--7----------	13	AuxP
17	rokem	rok	NNIS7-----A----	16	Adv
18	.	.	Z:-------------	0	AuxK

1	Právě	právě	Db-------------	3	AuxZ
2	tyto	tento	PDFP4----------	3	Atr
3	věci	věc	NNFP4-----A----	4	Obj
4	dovážíme	dovážet_:T_^(z_ciziny)	VB-P---1P-AA---	0	Pred
5	za	za-1	RR--4----------	4	AuxP
6	dolary	dolar_;b	NNIP4-----A----	5	Obj
7	.	.	Z:-------------	0	AuxK

1	Ani	ani	J^-------------	2	AuxZ
2	vývozcům	vývozce	NNMP3-----A----	3	Obj
3	,	,	Z:-------------	5	Coord
4	ostře	ostře	Dg-------1A----	5	Adv
5	kritizujícím	kritizující_^(*5ovat)	AGIS6-----A----	7	Atr
6	pevnou	pevný	AAFS4----1A----	7	Atr
7	měnu	měna	NNFS4-----A----	10	Obj
8	vůči	vůči	RR--3----------	7	AuxP
9	euru	euro_;b_^(evr._měna)	NNNS3-----A----	8	Atr
10	,	,	Z:-------------	15	Coord
11	zpevnění	zpevnění_^(*3it)	NNNS1-----A----	15	Sb
12	k	k-1	RR--3----------	11	AuxP
13	dolaru	dolar_;b	NNIS3-----A----	12	Atr
14	tolik	tolik-3_^(ve_spojení_s_adj.)	Db-------------	15	Adv
15	nevadí	vadit_:T	VB-S---3P-NA---	0	Pred
16	.	.	Z:-------------	0	AuxK

1	Jen	jen-1_^(pouze)	TT-------------	2	AuxZ
2	necelá	celý	AAFS1----1N----	3	Atr
3	třetina	třetina	CyFS1----------	10	Sb
4	českého	český	AANS2----1A----	5	Atr
5	zboží	zboží	NNNS2-----A----	3	Atr
6	se	se_^(zvr._zájmeno/částice)	P7-X4----------	10	AuxR
7	totiž	totiž	Db-------------	10	AuxY
8	v	v-1	RR--6----------	10	AuxP
9	cizině	cizina	NNFS6-----A----	8	Adv
10	prodává	prodávat_:T_^(*4at)	VB-S---3P-AA---	0	Pred
11	za	za-1	RR--4----------	10	AuxP
12	dolary	dolar_;b	NNIP4-----A----	11	Obj
13	.	.	Z:-------------	0	AuxK

1	Zbývající	zbývající_^(*4t)	AGNP1-----A----	2	Atr
2	dvě	dva`2	ClHP4----------	5	Atr
3	naopak	naopak	Db-------------	1	Adv
4	za	za-1	RR--4----------	0	AuxP
5	eura	euro_;b_^(evr._měna)	NNNP4-----A----	4	Obj
6	.	.	Z:-------------	0	AuxK

1	V	v-1	RR--6----------	6	AuxP
2	nevýhodné	výhodný	AAFS6----1N----	3	Atr
3	situaci	situace	NNFS6-----A----	1	Adv
4	se	se_^(zvr._zájmeno/částice)	P7-X4----------	6	AuxT
5	naopak	naopak	Db-------------	6	Adv
6	ocitli	ocitnout_:W	VpMP---XR-AA--1	0	Pred
7	lidé	člověk	NNMP1-----A---1	6	Sb
8	,	,	Z:-------------	10	AuxX
9	kteří	který	P4MP1----------	10	Sb
10	potřebovali	potřebovat_:T	VpMP---XR-AA---	7	Atr
11	vybrat	vybrat	Vf--------A----	10	Obj
12	koruny	koruna	NNFP4-----A----	11	Obj
13	z	z-1	RR--2----------	11	AuxP
14	dolarového	dolarový	AANS2----1A----	15	Atr
15	konta	konto	NNNS2-----A----	13	Atr
16	.	.	Z:-------------	0	AuxK

1	Za	za-1	RR--4----------	4	AuxP
2	sto	sto-2`100	NNNS4-----A----	1	Obj
3	dolarů	dolar_;b	NNIP2-----A----	2	Atr
4	dostanou	dostat	VB-P---3P-AA---	0	Pred
5	asi	asi	TT-------------	8	AuxZ
6	o	o-1	RR--4----------	10	AuxP
7	tři	tři`3	ClXP4----------	8	Atr
8	sta	sto-2`100	NNNP4-----A----	4	Obj
9	korun	koruna	NNFP2-----A----	8	Atr
10	méně	málo-3	Dg-------2A----	4	Adv
11	než	než-2	J,-------------	10	AuxC
12	loni	vloni_,h	Db------------1	11	ExD
13	na	na-1	RR--6----------	11	AuxP
14	začátku	začátek	NNIS6-----A----	13	Adv
15	roku	rok	NNIS2-----A---1	14	Atr
16	.	.	Z:-------------	0	AuxK

1	To	ten	PDNS1----------	13	Sb
2	,	,	Z:-------------	3	AuxX
3	že	že	J,-------------	1	AuxC
4	koruna	koruna	NNFS1-----A----	5	Sb
5	patří	patřit_:T	VB-S---3P-AA---	3	Obj
6	mezi	mezi-1	RR--4----------	5	AuxP
7	jednu	jeden`1	ClFS4----------	6	Adv
8	z	z-1	RR--2----------	7	AuxP
9	malá	malý	AAFS1----1A----	11	Atr
10	posilujících	posilující_^(*5ovat)	AGFP2-----A----	11	Atr
11	měn	měna	NNFP2-----A----	8	Atr
12	,	,	Z:-------------	5	AuxX
13	není	být	VB-S---3P-NA---	0	Pred
14	až	až-3_^(až_k_...,_až_dost)	TT-------------	15	AuxZ
15	tak	tak-3	Db-------------	16	Adv
16	překvapivé	překvapivý	AANS1----1A----	13	Pnom
17	.	.	Z:-------------	0	AuxK

1	Česká	Český-1_;G_^(používá_se_i_pro_jména_org.,_výrobků_atd.)	AAFS1----1A----	2	Atr
2	republika	republika	NNFS1-----A----	6	Sb
3	stejně	stejně_^(*1ý)	Dg-------1A----	6	Adv
4	jako	jako	J,-------------	3	AuxC
5	Maďarsko	Maďarsko_;G	NNNS1-----A----	4	ExD
6	jsou	být	VB-P---3P-AA---	0	Pred
7	nyní	nyní	Db-------------	6	Adv
8	nejrychleji	rychle_^(*1ý)	Dg-------3A----	6	Adv
9	rostoucími	rostoucí-2_^(*9ůst-2)	AGFP7-----A----	11	Atr
10	evropskými	evropský	AAFP7----1A----	11	Atr
11	ekonomikami	ekonomika	NNFP7-----A----	6	Pnom
12	.	.	Z:-------------	0	AuxK

1	Za	za-1	RR--4----------	9	AuxP
2	devět	devět`9	Cn-S4----------	1	Adv
3	měsíců	měsíc	NNIP2-----A----	2	Atr
4	loňského	loňský	AAIS2----1A----	5	Atr
5	roku	rok	NNIS2-----A---1	3	Atr
6	se	se_^(zvr._zájmeno/částice)	P7-X4----------	9	AuxT
7	výkon	výkon	NNIS1-----A----	9	Sb
8	země	země	NNFS2-----A----	7	Atr
9	zvýšil	zvýšit_:W	VpYS---XR-AA---	0	Pred
10	o	o-1	RR--6----------	9	AuxP
11	3	3	NNMS1-----A----	10	Obj
12	,	,	Z:-------------	9	Apos
13	6	6	NNMS1-----A----	12	ExD
14	procenta	procento	NNNS2-----A----	13	Atr
15	.	.	Z:-------------	0	AuxK

1	Naopak	naopak	Db-------------	4	Adv
2	Německo	Německo_;G	NNNS1-----A----	4	Sb
3	už	už	Db-------------	4	Adv
4	sužují	sužovat_:T	VB-P---3P-AA---	0	Pred
5	hospodářské	hospodářský	AAIP4----1A----	6	Atr
6	problémy	problém	NNIP4-----A----	4	Obj
7	,	,	Z:-------------	4	Coord
8	Francie	Francie_;G	NNFP1-----A----	9	Sb
9	stojí	stát-3_^(někdo/něco_stojí,_např._na_nohou)	VB-P---3P-AA---	7	Pred
10	na	na-1	RR--6----------	9	AuxP
11	jejich	jeho_^(přivlast.)	PSXXXXP3-------	12	Atr
12	prahu	práh	NNIS2-----A----	10	Adv
13	.	.	Z:-------------	0	AuxK

1	Ani	ani	J^-------------	3	AuxZ
2	ostatní	ostatní	AAFP1----1A----	3	Atr
3	země	země	NNFP1-----A----	7	Sb
4	unie	unie	NNFS2-----A----	3	Atr
5	na	na-1	RR--6----------	7	AuxP
6	tom	ten	PDZS6----------	5	Atr
7	nejsou	být	VB-P---3P-NA---	0	Pred
8	nejlépe	dobře	Dg-------3A----	7	Adv
9	.	.	Z:-------------	0	AuxK

1	Japonsko	Japonsko_;G	NNNS1-----A----	3	Sb
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	3	AuxT
3	potácí	potácet_:T	VB-S---3P-AA---	0	Pred
4	v	v-1	RR--6----------	3	AuxP
5	recesi	recese	NNFS6-----A----	4	Adv
6	již	již	Db-------------	8	AuxZ
7	delší	dlouhý-1_^(fyz._délka;_př._dlouhá_tyč)	AAFS4----2A----	8	Atr
8	dobu	doba	NNFS4-----A----	3	Obj
9	.	.	Z:-------------	0	AuxK

1	Česko	Česko_;G	NNNS1-----A----	3	Sb
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	4	AuxT
3	může	moci_^(mít_možnost_[něco_dělat])	VB-S---3P-AA---	0	Pred
4	pochlubit	pochlubit_:W	Vf--------A----	3	Obj
5	i	i-1	J^-------------	8	AuxZ
6	zatím	zatím	Db-------------	7	Adv
7	nechabnoucím	chabnoucí_^(*2t)	AGIS7-----N----	8	Atr
8	přílivem	příliv	NNIS7-----A----	15	Obj
9	zahraničních	zahraniční	AAFP2----1A----	10	Atr
10	investic	investice	NNFP2-----A---1	8	Atr
11	,	,	Z:-------------	15	AuxX
12	mírným	mírný	AAIS7----1A----	13	Atr
13	růstem	růst-1	NNIS7-----A----	15	Atr
14	cen	cena-1_^(v_penězích,_naturální,_nevyčíslitelná,...)	NNFP2-----A----	13	Atr
15	a	a-1	J^-------------	4	Coord
16	slušným	slušný	AAIS7----1A----	17	Atr
17	vzestupem	vzestup	NNIS7-----A----	15	Atr
18	platů	plat_^(mzda)	NNIP2-----A----	17	Atr
19	.	.	Z:-------------	0	AuxK

1	Evropskou	evropský	AAFS4----1A----	2	Atr
2	unii	unie	NNFS4-----A----	3	Obj
3	máme	mít	VB-P---1P-AA---	7	Pred
4	na	na-1	RR--4----------	3	AuxP
5	dohled	dohled	NNIS4-----A----	4	Obj
6	,	,	Z:-------------	7	AuxX
7	a	a-1	J^-------------	0	Coord
8	tak	tak-3	Db-------------	7	AuxY
9	investoři	investor	NNMP1-----A----	11	Sb
10	Česku	Česko_;G	NNNS3-----A----	11	Obj
11	důvěřují	důvěřovat_:T	VB-P---3P-AA---	7	Pred
12	.	.	Z:-------------	0	AuxK

1	Problémy	problém	NNIP1-----A----	13	Sb
2	s	s-1	RR--7----------	1	AuxP
3	rychle	rychle_^(*1ý)	Dg-------1A----	4	Adv
4	bytnícími	bytnící_^(*3ět)	AGIP7-----A----	5	Atr
5	dluhy	dluh	NNIP7-----A----	2	Atr
6	zatím	zatím	Db-------------	13	Adv
7	stabilitu	stabilita	NNFS4-----A----	13	Obj
8	ekonomiky	ekonomika	NNFS2-----A----	7	Atr
9	v	v-1	RR--6----------	7	AuxP
10	krátkém	krátký	AAIS6----1A----	11	Atr
11	horizontu	horizont	NNIS6-----A---1	9	Atr
12	přímo	přímo	Dg-------1A----	13	Adv
13	neohrožují	ohrožovat_:T	VB-P---3P-NA---	0	Pred
14	.	.	Z:-------------	0	AuxK

1	A	a-1	J^-------------	0	Coord
2	tak	tak-3	Db-------------	1	AuxY
3	investoři	investor	NNMP1-----A----	7	Sb
4	české	český	AAFS6----1A----	5	Atr
5	koruně	koruna	NNFS6-----A----	3	Atr
6	loni	vloni_,h	Db------------1	7	Adv
7	důvěřovali	důvěřovat_:T	VpMP---XR-AA---	1	Pred
8	.	.	Z:-------------	0	AuxK

1	Co	co-1	PQ--4----------	2	Obj
2	znamená	znamenat_:T	VB-S---3P-AA---	0	Pred
3	posílení	posílení_^(*3it)	NNNS4-----A----	2	Obj
4	koruny	koruna	NNFS2-----A----	3	Atr
5	k	k-1	RR--3----------	3	AuxP
6	dolaru	dolar_;b	NNIS3-----A----	5	Atr
7	-	-	Z:-------------	5	Apos
8	zlevnění	zlevnění_^(*3it)	NNNS1-----A----	7	Adv
9	benzinu	benzín	NNIS2-----A----	10	Atr
10	a	a-1	J^-------------	8	Coord
11	nafty	nafta	NNFS2-----A----	10	Atr
12	-	-	Z:-------------	17	AuxG
13	zlevnění	zlevnění_^(*3it)	NNNS1-----A----	17	Sb
14	počítačů	počítač	NNIP2-----A----	13	Atr
15	,	,	Z:-------------	17	AuxX
16	elektroniky	elektronika	NNFP1-----A----	17	Sb
17	a	a-1	J^-------------	7	Coord
18	dalšího	další	AAIS2----1A----	20	Atr
19	dovozového	dovozový	AANS2----1A----	20	Atr
20	zboží	zboží	NNNS2-----A----	17	Atr
21	-	-	Z:-------------	17	Apos
22	výhodnější	výhodný	AAIS1----2A----	23	Atr
23	nákup	nákup	NNIS1-----A----	21	Sb
24	dolarů	dolar_;b	NNIP2-----A----	23	Atr
25	při	při-1	RR--6----------	23	AuxP
26	cestách	cesta_^(konkrétní_i_abstr.;_i_'soudní_cestou')	NNFP6-----A----	25	Atr
27	do	do-1	RR--2----------	26	AuxP
28	ciziny	cizina	NNFS2-----A----	27	Atr
29	-	-	Z:-------------	23	Apos
30	prodražení	prodražení_^(*3it)	NNNS1-----A----	29	Sb
31	vývozů	vývoz	NNIP2-----A----	30	Atr
32	do	do-1	RR--2----------	31	AuxP
33	zemí	země	NNFP2-----A----	32	Atr
34	obchodujících	obchodující_^(*5ovat)	AGFP2-----A----	33	Atr
35	v	v-1	RR--6----------	34	AuxP
36	dolarech	dolar_;b	NNIP6-----A----	35	Adv
37	-	-	Z:-------------	33	Apos
38	menší	malý	AAFS1----2A----	40	Atr
39	korunové	korunový	AAIP1----1A----	40	Atr
40	výnosy	výnos	NNIP1-----A----	37	Sb
41	z	z-1	RR--2----------	40	AuxP
42	dolarových	dolarový	AAIP2----1A----	43	Atr
43	účtů	účet	NNIP2-----A----	41	Atr

</TEXT>
</DOC>
