<DOC>
<DOCID>MF-20021129341</DOCID>
<DOCNO>MF-20021129341</DOCNO>
<DATE>11/29/02</DATE>
<TITLE>
1	Britský	britský	AAIS1----1A----	2	Atr
2	kabinet	kabinet	NNIS1-----A----	3	Sb
3	odvrátil	odvrátit_:W	VpYS---XR-AA---	0	Pred
4	krizi	krize	NNFS4-----A----	3	Obj
5	ostrovní	ostrovní	AAFS2----1A----	6	Atr
6	energetiky	energetika_^(věda)	NNFS2-----A----	4	Atr

</TITLE>
<GEOGRAPHY>Londýn</GEOGRAPHY>
<TEXT>
1	Britské	britský	AAFS6----1A----	2	Atr
2	energetice	energetika_^(věda)	NNFS6-----A----	9	Obj
3	po	po-1	RR--6----------	2	AuxP
4	včerejšku	včerejšek	NNIS6-----A----	3	Atr
5	pro	pro-1	RR--4----------	9	AuxP
6	nejbližší	blízký	AAFS4----3A----	7	Atr
7	dobu	doba	NNFS4-----A----	5	Adv
8	již	již	Db-------------	9	Adv
9	nehrozí	hrozit_:T	VB-S---3P-NA---	0	Pred
10	vážná	vážný	AAFS1----1A----	11	Atr
11	krize	krize	NNFS1-----A----	9	Sb
12	,	,	Z:-------------	15	AuxX
13	která	který	P4FS1----------	15	Sb
14	by	být	Vc-------------	15	AuxV
15	mohla	moci_^(mít_možnost_[něco_dělat])	VpQW---XR-AA---	11	Atr
16	výrazně	výrazně_^(*1ý)	Dg-------1A----	17	Adv
17	zasáhnout	zasáhnout	Vf--------A----	15	Obj
18	trh	trh	NNIS4-----A----	17	Obj
19	s	s-1	RR--7----------	18	AuxP
20	elektřinou	elektřina	NNFS7-----A----	19	Atr
21	.	.	Z:-------------	0	AuxK

1	Vláda	vláda	NNFS1-----A----	5	Sb
2	ostrovního	ostrovní	AANS2----1A----	3	Atr
3	království	království	NNNS2-----A----	1	Atr
4	totiž	totiž	Db-------------	5	AuxY
5	přislíbila	přislíbit_:W	VpQW---XR-AA---	24	Pred
6	výrobci	výrobce	NNMP1-----A----	5	Sb
7	jaderné	jaderný	AAFS2----1A----	8	Atr
8	energie	energie	NNFS2-----A----	6	Atr
9	British	British-1_;K_,t_^(souč._názvů,_např._B._Airways)	AAXXX----1A----	10	Atr
10	Energy	Energy	NNFXX-----A----	8	Atr
11	,	,	Z:-------------	24	AuxX
12	který	který	P4YS1----------	15	Sb
13	do	do-1	RR--2----------	15	AuxP
14	sítě	síť	NNFS2-----A----	13	Adv
15	dodává	dodávat_:T_^(*4at)	VB-S---3P-AA---	24	Pred
16	téměř	téměř	Db-------------	17	AuxZ
17	pětinu	pětina	CyFS4----------	15	Obj
18	elektrické	elektrický	AAFS2----1A----	19	Atr
19	energie	energie	NNFS2-----A----	17	Atr
20	,	,	Z:-------------	24	AuxX
21	další	další	AAFS4----1A----	22	Atr
22	půjčku	půjčka	NNFS4-----A----	15	Obj
23	,	,	Z:-------------	24	AuxX
24	a	a-1	J^-------------	0	Coord
25	odvrátila	odvrátit_:W	VpQW---XR-AA---	24	Pred
26	tak	tak-3	Db-------------	27	Adv
27	bezprostřední	bezprostřední	AAFS4----1A----	28	Atr
28	hrozbu	hrozba	NNFS4-----A----	25	Obj
29	bankrotu	bankrot	NNIS2-----A----	28	Atr
30	této	tento	PDFS2----------	31	Atr
31	firmy	firma	NNFS2-----A----	29	Atr
32	.	.	Z:-------------	0	AuxK

1	British	British-1_;K_,t_^(souč._názvů,_např._B._Airways)	AAXXX----1A----	2	Atr
2	Energy	Energy	NNFXX-----A----	6	Sb
3	se	s-1	RV--7----------	6	AuxT
4	začátkem	začátek	NNIS7-----A----	6	AuxP
5	roku	rok	NNIS2-----A---1	4	Adv
6	ocitla	ocitnout_:W	VpQW---XR-AA--1	10	Pred
7	v	v-1	RR--6----------	6	AuxP
8	problémech	problém	NNIP6-----A----	7	Adv
9	,	,	Z:-------------	10	AuxX
10	neboť	neboť	J^-------------	0	Coord
11	velkoobchodní	velkoobchodní	AAFP4----1A----	12	Atr
12	ceny	cena-1_^(v_penězích,_naturální,_nevyčíslitelná,...)	NNFP4-----A----	17	Sb
13	energie	energie	NNFS2-----A----	12	Atr
14	v	v-1	RR--6----------	12	AuxP
15	Británii	Británie_;G	NNFS6-----A----	14	Atr
16	výrazně	výrazně_^(*1ý)	Dg-------1A----	17	Adv
17	klesly	klesnout_:W	VpTP---XR-AA--1	18	Pred
18	a	a-1	J^-------------	10	Coord
19	dostaly	dostat	VpTP---XR-AA---	18	Pred
20	se	se_^(zvr._zájmeno/částice)	P7-X4----------	19	AuxT
21	pod	pod-1	RR--4----------	19	AuxP
22	úroveň	úroveň	NNFS4-----A----	21	Adv
23	výrobních	výrobní	AAIP2----1A----	24	Atr
24	nákladů	náklad	NNIP2-----A----	22	Atr
25	.	.	Z:-------------	0	AuxK

1	Vláda	vláda	NNFS1-----A----	2	Sb
2	je	být	VB-S---3P-AA---	0	Pred
3	ochotna	ochotný	ACQW------A----	2	Pnom
4	financovat	financovat_:T	Vf--------A----	3	Obj
5	British	British-1_;K_,t_^(souč._názvů,_např._B._Airways)	AAXXX----1A----	6	Atr
6	Energy	Energy	NNFSX-----A----	4	Obj
7	až	až-3_^(až_k_...,_až_dost)	TT-------------	9	AuxZ
8	do	do-1	RR--2----------	4	AuxP
9	9	9	NNMS1-----A----	8	Adv
10	.	.	Z:-------------	0	AuxK

1	března	březen	NNIS2-----A----	9	Obj
2	2003	2003	C=-------------	1	Atr
3	,	,	Z:-------------	9	AuxX
4	za	za-1	RR--4----------	9	AuxP
5	což	což-1	PE--4----------	4	AuxY
6	jí	on-1_^(ona)	PPFS3--3-------	9	Obj
7	vedení	vedení	NNNS1-----A----	9	Sb
8	firmy	firma	NNFS2-----A----	7	Atr
9	slíbilo	slíbit_:W	VpNS---XR-AA---	0	Pred
10	urychlení	urychlení_^(*3it)	NNNS1-----A----	9	Obj
11	restrukturalizace	restrukturalizace	NNFS2-----A----	10	Atr
12	.	.	Z:-------------	0	AuxK

1	Opatření	opatření_^(*3it)	NNNS1-----A----	8	Sb
2	,	,	Z:-------------	8	AuxX
3	k	k-1	RR--3----------	8	AuxP
4	nimž	jenž_^(který_[ve_vedl.větě])	P9XP3----------	3	Adv
5	British	British-1_;K_,t_^(souč._názvů,_např._B._Airways)	AAXXX----1A----	6	Atr
6	Energy	Energy	NNFXX-----A----	1	Atr
7	nyní	nyní	Db-------------	8	Adv
8	sáhne	sáhnout_:W	VB-S---3P-AA---	11	Pred
9	,	,	Z:-------------	8	AuxX
10	se	se_^(zvr._zájmeno/částice)	P7-X4----------	17	AuxT
11	však	však	J^-------------	0	Coord
12	z	z-1	RR--2----------	17	AuxP
13	pohledu	pohled	NNIS2-----A----	12	Adv
14	akcionářů	akcionář	NNMP2-----A----	15	Atr
15	bankrotu	bankrot	NNIS2-----A----	13	Atr
16	téměř	téměř	Db-------------	17	Adv
17	rovnají	rovnat_:T_^(se)_(něčemu)	VB-P---3P-AA---	11	Pred
18	.	.	Z:-------------	0	AuxK

1	Firma	firma	NNFS1-----A----	3	Sb
2	totiž	totiž	Db-------------	3	AuxY
3	uvedla	uvést	VpQW---XR-AA---	0	Pred
4	,	,	Z:-------------	5	AuxX
5	že	že	J,-------------	3	AuxC
6	vydá	vydat-1_:W_^(emitovat:_cenné_papíry,_knihu,_zvuk,...)	VB-S---3P-AA---	5	Adv
7	nové	nový	AAIP1----1A----	9	Atr
8	cenné	cenný	AAIP1----1A----	9	Atr
9	papíry	papír	NNIP1-----A----	6	Sb
10	,	,	Z:-------------	11	AuxX
11	a	a-1	J^-------------	12	AuxY
12	to	ten	PDNS1----------	14	AuxY
13	jak	jak-3	Db-------------	16	AuxY
14	akcie	akcie	NNFP4-----A----	16	Obj
15	,	,	Z:-------------	16	AuxX
16	tak	tak-3	Db-------------	6	Coord
17	dluhopisy	dluhopis	NNIP4-----A----	16	Obj
18	.	.	Z:-------------	0	AuxK

1	Akcionáře	akcionář	NNMS2-----A----	2	ExD
2	však	však	J^-------------	0	Coord
3	firma	firma	NNFS1-----A----	5	Sb
4	hned	hned	Db-------------	5	Adv
5	upozornila	upozornit_:W	VpQW---XR-AA---	2	Pred
6	na	na-1	RR--4----------	5	AuxP
7	to	ten	PDNS4----------	6	Obj
8	,	,	Z:-------------	9	AuxX
9	že	že	J,-------------	7	AuxC
10	tento	tento	PDYS1----------	11	Atr
11	krok	krok	NNIS1-----A----	13	Sb
12	podstatně	podstatně_^(*1ý)	Dg-------1A----	13	Adv
13	sníží	snížit_:W	VB-S---3P-AA---	9	Obj
14	hodnotu	hodnota	NNFS4-----A----	13	Obj
15	jejich	jeho_^(přivlast.)	PSXXXXP3-------	16	Atr
16	akcií	akcie	NNFP2-----A----	14	Atr
17	.	.	Z:-------------	0	AuxK

1	Firma	firma	NNFS1-----A----	2	Sb
2	sáhla	sáhnout_:W	VpQW---XR-AA--1	0	Pred
3	rovněž	rovněž	Db-------------	2	Adv
4	ke	k-1	RV--3----------	2	AuxP
5	změnám	změna	NNFP3-----A----	4	Obj
6	ve	v-1	RV--6----------	5	AuxP
7	vrcholovém	vrcholový	AANS6----1A----	8	Atr
8	vedení	vedení	NNNS2-----A----	6	Atr
9	.	.	Z:-------------	0	AuxK

1	Předseda	předseda	NNMS1-----A----	6	Atr
2	správní	správní_^(např._poplatek;_rada;_řád;...)	AAFS2----1A----	3	Atr
3	rady	rada-1_^(př._dát_někomu_dobrou_radu)	NNFS2-----A----	1	Atr
4	firmy	firma	NNFS2-----A----	3	Atr
5	Robin	Robin_;Y	NNMS1-----A----	6	Atr
6	Jeffrey	Jeffrey_;Y_,t	NNMS1-----A----	7	Sb
7	přišel	přijít	VpYS---XR-AA---	10	Pred
8	o	o-1	RR--6----------	7	AuxP
9	místo	místo-1_^(fyzické_umístění)	NNNS4-----A----	8	Obj
10	a	a-1	J^-------------	0	Coord
11	na	na-1	RR--4----------	14	AuxP
12	jeho	jeho_^(přivlast.)	PSXXXZS3-------	13	Atr
13	pozici	pozice	NNFS4-----A----	11	Obj
14	nastoupí	nastoupit_:W	VB-S---3P-AA---	10	Pred
15	Adrian	Adrian_;Y_^(mužské_jméno)	NNMS1-----A----	14	Sb
16	Montague	Montague_;G	NNNXX-----A----	15	Atr
17	.	.	Z:-------------	0	AuxK

1	Londýn	Londýn_;G	NNIS1-----A----	11	Sb
2	-	-	Z:-------------	11	Coord
3	Britské	britský	AAFS6----1A----	4	Atr
4	energetice	energetika_^(věda)	NNFS6-----A----	2	Adv
5	po	po-1	RR--6----------	4	AuxP
6	včerejšku	včerejšek	NNIS6-----A----	5	Atr
7	pro	pro-1	RR--4----------	11	AuxP
8	nejbližší	blízký	AAFS4----3A----	9	Atr
9	dobu	doba	NNFS4-----A----	7	Adv
10	již	již	Db-------------	11	Adv
11	nehrozí	hrozit_:T	VB-S---3P-NA---	0	Pred
12	vážná	vážný	AAFS1----1A----	13	Atr
13	krize	krize	NNFS1-----A----	11	Sb
14	,	,	Z:-------------	17	AuxX
15	která	který	P4FS1----------	17	Sb
16	by	být	Vc-------------	17	AuxV
17	mohla	moci_^(mít_možnost_[něco_dělat])	VpQW---XR-AA---	13	Atr
18	výrazně	výrazně_^(*1ý)	Dg-------1A----	19	Adv
19	zasáhnout	zasáhnout	Vf--------A----	17	Obj
20	trh	trh	NNIS4-----A----	19	Obj
21	s	s-1	RR--7----------	20	AuxP
22	elektřinou	elektřina	NNFS7-----A----	21	Atr
23	.	.	Z:-------------	0	AuxK

1	Vláda	vláda	NNFS1-----A----	5	Sb
2	ostrovního	ostrovní	AANS2----1A----	3	Atr
3	království	království	NNNS2-----A----	1	Atr
4	totiž	totiž	Db-------------	5	AuxY
5	přislíbila	přislíbit_:W	VpQW---XR-AA---	24	Pred
6	výrobci	výrobce	NNMP1-----A----	5	Sb
7	jaderné	jaderný	AAFS2----1A----	8	Atr
8	energie	energie	NNFS2-----A----	6	Atr
9	British	British-1_;K_,t_^(souč._názvů,_např._B._Airways)	AAXXX----1A----	10	Atr
10	Energy	Energy	NNFXX-----A----	8	Atr
11	,	,	Z:-------------	24	AuxX
12	který	který	P4YS1----------	15	Sb
13	do	do-1	RR--2----------	15	AuxP
14	sítě	síť	NNFS2-----A----	13	Adv
15	dodává	dodávat_:T_^(*4at)	VB-S---3P-AA---	24	Pred
16	téměř	téměř	Db-------------	17	AuxZ
17	pětinu	pětina	CyFS4----------	15	Obj
18	elektrické	elektrický	AAFS2----1A----	19	Atr
19	energie	energie	NNFS2-----A----	17	Atr
20	,	,	Z:-------------	24	AuxX
21	další	další	AAFS4----1A----	22	Atr
22	půjčku	půjčka	NNFS4-----A----	15	Obj
23	,	,	Z:-------------	24	AuxX
24	a	a-1	J^-------------	0	Coord
25	odvrátila	odvrátit_:W	VpQW---XR-AA---	24	Pred
26	tak	tak-3	Db-------------	27	Adv
27	bezprostřední	bezprostřední	AAFS4----1A----	28	Atr
28	hrozbu	hrozba	NNFS4-----A----	25	Obj
29	bankrotu	bankrot	NNIS2-----A----	28	Atr
30	této	tento	PDFS2----------	31	Atr
31	firmy	firma	NNFS2-----A----	29	Atr
32	.	.	Z:-------------	0	AuxK

1	British	British-1_;K_,t_^(souč._názvů,_např._B._Airways)	AAXXX----1A----	2	Atr
2	Energy	Energy	NNFXX-----A----	6	Sb
3	se	s-1	RV--7----------	6	AuxT
4	začátkem	začátek	NNIS7-----A----	6	AuxP
5	roku	rok	NNIS2-----A---1	4	Adv
6	ocitla	ocitnout_:W	VpQW---XR-AA--1	10	Pred
7	v	v-1	RR--6----------	6	AuxP
8	problémech	problém	NNIP6-----A----	7	Adv
9	,	,	Z:-------------	10	AuxX
10	neboť	neboť	J^-------------	0	Coord
11	velkoobchodní	velkoobchodní	AAFP4----1A----	12	Atr
12	ceny	cena-1_^(v_penězích,_naturální,_nevyčíslitelná,...)	NNFP4-----A----	17	Sb
13	energie	energie	NNFS2-----A----	12	Atr
14	v	v-1	RR--6----------	12	AuxP
15	Británii	Británie_;G	NNFS6-----A----	14	Atr
16	výrazně	výrazně_^(*1ý)	Dg-------1A----	17	Adv
17	klesly	klesnout_:W	VpTP---XR-AA--1	18	Pred
18	a	a-1	J^-------------	10	Coord
19	dostaly	dostat	VpTP---XR-AA---	18	Pred
20	se	se_^(zvr._zájmeno/částice)	P7-X4----------	19	AuxT
21	pod	pod-1	RR--4----------	19	AuxP
22	úroveň	úroveň	NNFS4-----A----	21	Adv
23	výrobních	výrobní	AAIP2----1A----	24	Atr
24	nákladů	náklad	NNIP2-----A----	22	Atr
25	.	.	Z:-------------	0	AuxK

1	Vláda	vláda	NNFS1-----A----	2	Sb
2	je	být	VB-S---3P-AA---	0	Pred
3	ochotna	ochotný	ACQW------A----	2	Pnom
4	financovat	financovat_:T	Vf--------A----	3	Obj
5	British	British-1_;K_,t_^(souč._názvů,_např._B._Airways)	AAXXX----1A----	6	Atr
6	Energy	Energy	NNFSX-----A----	4	Obj
7	až	až-3_^(až_k_...,_až_dost)	TT-------------	9	AuxZ
8	do	do-1	RR--2----------	4	AuxP
9	9	9	NNMS1-----A----	8	Adv
10	.	.	Z:-------------	0	AuxK

1	března	březen	NNIS2-----A----	9	Obj
2	2003	2003	C=-------------	1	Atr
3	,	,	Z:-------------	9	AuxX
4	za	za-1	RR--4----------	9	AuxP
5	což	což-1	PE--4----------	4	AuxY
6	jí	on-1_^(ona)	PPFS3--3-------	9	Obj
7	vedení	vedení	NNNS1-----A----	9	Sb
8	firmy	firma	NNFS2-----A----	7	Atr
9	slíbilo	slíbit_:W	VpNS---XR-AA---	0	Pred
10	urychlení	urychlení_^(*3it)	NNNS1-----A----	9	Obj
11	restrukturalizace	restrukturalizace	NNFS2-----A----	10	Atr
12	.	.	Z:-------------	0	AuxK

1	Opatření	opatření_^(*3it)	NNNS1-----A----	8	Sb
2	,	,	Z:-------------	8	AuxX
3	k	k-1	RR--3----------	8	AuxP
4	nimž	jenž_^(který_[ve_vedl.větě])	P9XP3----------	3	Adv
5	British	British-1_;K_,t_^(souč._názvů,_např._B._Airways)	AAXXX----1A----	6	Atr
6	Energy	Energy	NNFXX-----A----	1	Atr
7	nyní	nyní	Db-------------	8	Adv
8	sáhne	sáhnout_:W	VB-S---3P-AA---	11	Pred
9	,	,	Z:-------------	8	AuxX
10	se	se_^(zvr._zájmeno/částice)	P7-X4----------	17	AuxT
11	však	však	J^-------------	0	Coord
12	z	z-1	RR--2----------	17	AuxP
13	pohledu	pohled	NNIS2-----A----	12	Adv
14	akcionářů	akcionář	NNMP2-----A----	15	Atr
15	bankrotu	bankrot	NNIS2-----A----	13	Atr
16	téměř	téměř	Db-------------	17	Adv
17	rovnají	rovnat_:T_^(se)_(něčemu)	VB-P---3P-AA---	11	Pred
18	.	.	Z:-------------	0	AuxK

1	Firma	firma	NNFS1-----A----	3	Sb
2	totiž	totiž	Db-------------	3	AuxY
3	uvedla	uvést	VpQW---XR-AA---	0	Pred
4	,	,	Z:-------------	5	AuxX
5	že	že	J,-------------	3	AuxC
6	vydá	vydat-1_:W_^(emitovat:_cenné_papíry,_knihu,_zvuk,...)	VB-S---3P-AA---	5	Adv
7	nové	nový	AAIP1----1A----	9	Atr
8	cenné	cenný	AAIP1----1A----	9	Atr
9	papíry	papír	NNIP1-----A----	6	Sb
10	,	,	Z:-------------	11	AuxX
11	a	a-1	J^-------------	12	AuxY
12	to	ten	PDNS1----------	14	AuxY
13	jak	jak-3	Db-------------	16	AuxY
14	akcie	akcie	NNFP4-----A----	16	Obj
15	,	,	Z:-------------	16	AuxX
16	tak	tak-3	Db-------------	6	Coord
17	dluhopisy	dluhopis	NNIP4-----A----	16	Obj
18	.	.	Z:-------------	0	AuxK

1	Akcionáře	akcionář	NNMS2-----A----	2	ExD
2	však	však	J^-------------	0	Coord
3	firma	firma	NNFS1-----A----	5	Sb
4	hned	hned	Db-------------	5	Adv
5	upozornila	upozornit_:W	VpQW---XR-AA---	2	Pred
6	na	na-1	RR--4----------	5	AuxP
7	to	ten	PDNS4----------	6	Obj
8	,	,	Z:-------------	9	AuxX
9	že	že	J,-------------	7	AuxC
10	tento	tento	PDYS1----------	11	Atr
11	krok	krok	NNIS1-----A----	13	Sb
12	podstatně	podstatně_^(*1ý)	Dg-------1A----	13	Adv
13	sníží	snížit_:W	VB-S---3P-AA---	9	Obj
14	hodnotu	hodnota	NNFS4-----A----	13	Obj
15	jejich	jeho_^(přivlast.)	PSXXXXP3-------	16	Atr
16	akcií	akcie	NNFP2-----A----	14	Atr
17	.	.	Z:-------------	0	AuxK

1	Firma	firma	NNFS1-----A----	2	Sb
2	sáhla	sáhnout_:W	VpQW---XR-AA--1	0	Pred
3	rovněž	rovněž	Db-------------	2	Adv
4	ke	k-1	RV--3----------	2	AuxP
5	změnám	změna	NNFP3-----A----	4	Obj
6	ve	v-1	RV--6----------	5	AuxP
7	vrcholovém	vrcholový	AANS6----1A----	8	Atr
8	vedení	vedení	NNNS2-----A----	6	Atr
9	.	.	Z:-------------	0	AuxK

1	Předseda	předseda	NNMS1-----A----	6	Atr
2	správní	správní_^(např._poplatek;_rada;_řád;...)	AAFS2----1A----	3	Atr
3	rady	rada-1_^(př._dát_někomu_dobrou_radu)	NNFS2-----A----	1	Atr
4	firmy	firma	NNFS2-----A----	3	Atr
5	Robin	Robin_;Y	NNMS1-----A----	6	Atr
6	Jeffrey	Jeffrey_;Y_,t	NNMS1-----A----	7	Sb
7	přišel	přijít	VpYS---XR-AA---	10	Pred
8	o	o-1	RR--6----------	7	AuxP
9	místo	místo-1_^(fyzické_umístění)	NNNS4-----A----	8	Obj
10	a	a-1	J^-------------	0	Coord
11	na	na-1	RR--4----------	14	AuxP
12	jeho	jeho_^(přivlast.)	PSXXXZS3-------	13	Atr
13	pozici	pozice	NNFS4-----A----	11	Obj
14	nastoupí	nastoupit_:W	VB-S---3P-AA---	10	Pred
15	Adrian	Adrian_;Y_^(mužské_jméno)	NNMS1-----A----	14	Sb
16	Montague	Montague_;G	NNNXX-----A----	15	Atr
17	.	.	Z:-------------	0	AuxK

</TEXT>
</DOC>
