<DOC>
<DOCID>MF-20021023439</DOCID>
<DOCNO>MF-20021023439</DOCNO>
<DATE>10/23/02</DATE>
<TITLE>
1	Dubí	Dubí_;G	NNNS1-----A----	2	Sb
2	chce	chtít	VB-S---3P-AA---	0	Pred
3	pravidla	pravidlo	NNNP1-----A----	2	Obj
4	pro	pro-1	RR--4----------	3	AuxP
5	prostitutky	prostitutka	NNFP4-----A----	4	Atr

</TITLE>
<GEOGRAPHY>Dubí</GEOGRAPHY>
<TEXT>
1	"	"	Z:-------------	4	AuxG
2	Ať	ať	J,-------------	3	AuxY
3	zalezou	zalézt	VB-P---3P-AA---	4	Atr
4	a	a-1	J^-------------	0	Coord
5	platí	platit_:T_:W	VB-P---3P-AA---	4	Pred
6	daně	daň_^(peněžní/naturální_dávka)	NNFP1-----A----	5	Obj
7	,	,	Z:-------------	4	Coord
8	"	"	Z:-------------	2	AuxG
9	zaznělo	zaznít	VpNS---XR-AA---	7	Pred
10	z	z-1	RR--2----------	9	AuxP
11	úst	ústa	NNNP2-----A----	10	Adv
12	starostky	starostka_^(^FM*2a)	NNFS2-----A----	11	Atr
13	Dubí	Dubí_;G	NNNS1-----A----	9	Sb
14	Jutty	Jutta	NNFS2-----A----	13	Atr
15	Kučerové	Kučerová_;S	NNFS2-----A----	14	Atr
16	na	na-1	RR--4----------	12	AuxP
17	adresu	adresa	NNFS4-----A----	16	Atr
18	prostitutek	prostitutka	NNFP2-----A----	17	Atr
19	při	při-1	RR--6----------	18	AuxP
20	včerejší	včerejší	AAFS6----1A----	21	Atr
21	konferenci	konference	NNFS6-----A----	19	Adv
22	.	.	Z:-------------	0	AuxK

1	Ta	ten	PDFS1----------	2	Sb
2	nesla	nést	VpQW---XR-AA---	12	Atr
3	název	název	NNIS4-----A----	2	Obj
4	Prostituce	prostituce	NNFS2-----A----	3	Atr
5	jako	jako	J,-------------	7	AuxY
6	česko	český	A2--------A----	7	Atr
7	-	-	Z:-------------	9	Coord
8	německý	německý	AAIS1----1A----	7	Atr
9	problém	problém	NNIS1-----A----	12	Sb
10	v	v-1	RR--6----------	9	AuxP
11	příhraničí	příhraničí	NNNS6-----A----	10	Atr
12	a	a-1	J^-------------	0	Coord
13	měla	mít	VpQW---XR-AA---	12	Pred
14	přinést	přinést	Vf--------A----	13	Obj
15	konkrétní	konkrétní	AANS4----1A----	16	Atr
16	řešení	řešení_^(*3it)	NNNS4-----A----	14	Obj
17	,	,	Z:-------------	22	AuxX
18	jak	jak-3	Db-------------	22	Adv
19	problémy	problém	NNIP4-----A----	22	Obj
20	s	s-1	RR--7----------	19	AuxP
21	prostitucí	prostituce	NNFS7-----A----	20	Atr
22	řešit	řešit_:T	Vf--------A----	16	Atr
23	.	.	Z:-------------	0	AuxK

1	Dubští	dubský	AAMP1----1A----	5	Sb
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	6	AuxT
3	podle	podle-2	RR--2----------	5	AuxP
4	starostky	starostka_^(^FM*2a)	NNFS2-----A----	3	Adv
5	chtějí	chtít	VB-P---3P-AA---	9	Pred
6	zbavit	zbavit_:W	Vf--------A----	5	Obj
7	pouliční	pouliční	AAFS4----1A----	8	Atr
8	prostituce	prostituce	NNFS2-----A----	6	Obj
9	a	a-1	J^-------------	0	Coord
10	volají	volat_:T	VB-P---3P-AA---	9	Pred
11	po	po-1	RR--6----------	10	AuxP
12	pravidlech	pravidlo	NNNP6-----A----	11	Adv
13	,	,	Z:-------------	10	Coord
14	za	za-1	RR--4----------	19	AuxP
15	jakých	jaký	P4XP2----------	14	Adv
16	bude	být	VB-S---3F-AA---	19	AuxV
17	možné	možný	AAFP1----1A----	16	Pnom
18	prostituci	prostituce	NNFS4-----A----	19	Obj
19	provozovat	provozovat_:T	Vf--------A----	10	Obj
20	.	.	Z:-------------	0	AuxK

1	Představitelé	představitel	NNMP1-----A----	3	Sb
2	města	město	NNNS2-----A----	1	Atr
3	jsou	být	VB-P---3P-AA---	0	Pred
4	odhodláni	odhodlat_:W	VsMP---XX-AP---	3	Pnom
5	jít	jít	Vf--------A----	4	Obj
6	až	až-3_^(až_k_...,_až_dost)	TT-------------	9	AuxZ
7	k	k-1	RR--3----------	5	AuxP
8	Evropskému	evropský	AAIS3----1A----	9	Atr
9	parlamentu	parlament	NNIS3-----A----	7	Obj
10	,	,	Z:-------------	11	AuxX
11	pokud	pokud	J,-------------	3	AuxC
12	se	se_^(zvr._zájmeno/částice)	P7-X4----------	18	AuxT
13	poslanci	poslanec	NNMP1-----A----	14	Sb
14	a	a-1	J^-------------	16	Coord
15	senátoři	senátor	NNMP1-----A----	14	Sb
16	nezačnou	začít-1	VB-P---3P-NA---	11	Adv
17	znovu	znovu	Db-------------	18	Adv
18	zabývat	zabývat_:T	Vf--------A----	16	Obj
19	zákony	zákon	NNIP4-----A----	18	Obj
20	upravujícími	upravující_^(*5ovat)	AGNP7-----A----	21	Atr
21	nabízení	nabízení_^(*2t)	NNNP4-----A----	18	Obj
22	sexuálních	sexuální	AAFP2----1A----	23	Atr
23	služeb	služba	NNFP2-----A----	21	Atr
24	.	.	Z:-------------	0	AuxK

1	Protože	protože	J,-------------	11	AuxC
2	provozování	provozování_^(*3at)	NNNS1-----A----	6	Sb
3	prostituce	prostituce	NNFS2-----A----	2	Atr
4	s	s-1	RR--7----------	3	AuxP
5	sebou	se_^(zvr._zájmeno/částice)	P6-X7----------	4	Atr
6	nese	nést	VB-S---3P-AA---	1	Adv
7	další	další	AAIP1----1A----	9	Atr
8	nepříznivé	příznivý	AAIP1----1N----	9	Atr
9	jevy	jev	NNIP4-----A----	6	Obj
10	,	,	Z:-------------	1	AuxX
11	účastnili	účastnit_:T	VpMP---XR-AA---	0	Pred
12	se	se_^(zvr._zájmeno/částice)	P7-X4----------	11	AuxT
13	konference	konference	NNFS1-----A----	14	Atr
14	odborníci	odborník	NNMP1-----A----	11	Sb
15	z	z-1	RR--2----------	14	AuxP
16	různých	různý	AAIP2----1A----	17	Atr
17	oborů	obor_^(lidské_činnosti)	NNIP2-----A----	15	Atr
18	.	.	Z:-------------	0	AuxK

1	Podle	podle-2	RR--2----------	15	AuxP
2	Hany	Hana_;Y	NNFS2-----A----	1	Adv
3	Šnajderové	Šnajder_;S	NNMP1-----A----	1	Adv
4	z	z-1	RR--2----------	3	AuxP
5	odboru	odbor_^(na_úřadě)	NNIS2-----A----	4	Atr
6	prevence	prevence	NNFS2-----A----	5	Atr
7	kriminality	kriminalita	NNFS2-----A----	6	Atr
8	ministerstva	ministerstvo	NNNS2-----A----	5	Atr
9	vnitra	vnitro	NNNS2-----A----	8	Atr
10	by	být	Vc-------------	15	AuxV
11	hned	hned	Db-------------	15	Adv
12	několik	několik	Ca--1----------	15	Adv
13	problémů	problém	NNIP2-----A----	12	Atr
14	najednou	najednou	Db-------------	15	Adv
15	vyřešila	vyřešit_:W	VpQW---XR-AA---	0	Pred
16	legalizace	legalizace	NNFS1-----A----	15	Sb
17	prostituce	prostituce	NNFS2-----A----	16	Atr
18	.	.	Z:-------------	0	AuxK

1	Například	například	Db-------------	2	AuxZ
2	to	ten	PDNS1----------	19	Sb
3	,	,	Z:-------------	4	AuxX
4	že	že	J,-------------	2	AuxC
5	jsou	být	VB-P---3P-AA---	10	AuxV
6	ženy	žena	NNFP1-----A----	5	Sb
7	k	k-1	RR--3----------	6	AuxP
8	sexu	sex	NNIS3-----A----	7	Atr
9	často	často	Dg-------1A----	10	Adv
10	nuceny	nutit_:T	VsTP---XX-AP---	4	Obj
11	či	či	J^-------------	5	Coord
12	nebezpečí	nebezpečí	NNNS1-----A----	19	Sb
13	pohlavních	pohlavní	AAFP2----1A----	14	Atr
14	chorob	choroba	NNFP2-----A----	12	Atr
15	,	,	Z:-------------	5	AuxX
16	by	být	Vc-------------	19	AuxV
17	se	se_^(zvr._zájmeno/částice)	P7-X4----------	19	AuxR
18	pak	pak	Db-------------	19	Adv
19	dalo	dát	VpNS---XR-AA---	0	Pred
20	omezit	omezit_:W	Vf--------A----	19	Obj
21	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	6	AuxG
2	Ženy	žena	NNFP1-----A----	6	Sb
3	provozující	provozující_^(*5ovat)	AGFS4-----A----	4	Atr
4	prostituci	prostituce	NNFS4-----A----	6	Obj
5	by	být	Vc-------------	6	AuxV
6	měly	mít	VpTP---XR-AA---	0	Pred
7	možnost	možnost_^(*3ý)	NNFS4-----A----	6	Obj
8	využít	využít	Vf--------A----	7	Atr
9	právních	právní	AAIP2----1A----	10	Atr
10	i	i-1	J^-------------	12	Coord
11	jiných	jiný	AAIP2----1A----	10	Atr
12	prostředků	prostředek-1_^(střed)	NNIP2-----A----	8	Obj
13	na	na-1	RR--4----------	12	AuxP
14	ochranu	ochrana	NNFS4-----A----	13	Atr
15	svých	svůj-1_^(přivlast.)	P8XP2----------	17	Atr
16	práv	právo_^(právo_na_něco;_také_jako_obor)	NNNP2-----A----	17	Atr
17	a	a-1	J^-------------	14	Coord
18	zájmů	zájem	NNIP2-----A----	17	Atr
19	.	.	Z:-------------	0	AuxK

1	Bylo	být	VpNS---XR-AA---	23	Obj
2	by	být	Vc-------------	1	AuxV
3	také	také_^(rovněž)	Db-------------	1	Adv
4	možné	možný	AANS1----1A----	1	Pnom
5	vytvořit	vytvořit_:W	Vf--------A----	1	Sb
6	registrační	registrační	AAIS4----1A----	7	Atr
7	systém	systém	NNIS4-----A----	5	Obj
8	,	,	Z:-------------	13	Coord
9	přičemž	přičemž	J,-------------	17	Adv
10	pro	pro-1	RR--4----------	17	AuxP
11	obnovení	obnovení_^(*3it)	NNNS4-----A----	10	ExD
12	licence	licence	NNFS2-----A----	11	Atr
13	na	na-1	RR--4----------	7	AuxP
14	tuto	tento	PDFS4----------	15	Atr
15	činnost	činnost_^(*3ý)	NNFS4-----A----	13	Atr
16	by	být	Vc-------------	17	AuxV
17	musely	muset	VpTP---XR-AA---	8	Pred
18	mít	mít	Vf--------A----	17	Obj
19	zdravotní	zdravotní_,a	AAFS4----1A----	20	Atr
20	prohlídku	prohlídka	NNFS4-----A----	18	Obj
21	,	,	Z:-------------	17	AuxX
22	"	"	Z:-------------	1	AuxG
23	uvedla	uvést	VpQW---XR-AA---	0	Pred
24	Šnajderová	Šnajder	NNFS1-----A----	23	Sb
25	.	.	Z:-------------	0	AuxK

1	Proti	proti-1	RR--3----------	6	AuxP
2	legalizaci	legalizace	NNFS3-----A----	1	Adv
3	prostituce	prostituce	NNFS2-----A----	2	Atr
4	se	se_^(zvr._zájmeno/částice)	P7-X4----------	6	AuxT
5	naopak	naopak	Db-------------	6	Adv
6	postavil	postavit_:W	VpYS---XR-AA---	0	Pred
7	primátor	primátor	NNMS1-----A----	9	Sb
8	Teplic	Teplice_;G	NNFP2-----A----	7	Atr
9	a	a-1	J^-------------	6	Coord
10	senátor	senátor	NNMS1-----A----	12	Atr
11	Jaroslav	Jaroslav_;Y	NNMS1-----A----	12	Atr
12	Kubera	Kubera_;S	NNMS1-----A----	9	Sb
13	.	.	Z:-------------	0	AuxK

1	Ten	ten	PDYS1----------	3	Sb
2	zároveň	zároveň	Db-------------	3	Adv
3	neskrýval	skrývat_:T	VpYS---XR-NA---	0	Pred
4	své	svůj-1_^(přivlast.)	P8FP4---------1	5	Atr
5	pochybnosti	pochybnost_^(*3ý)	NNFP4-----A----	3	Obj
6	,	,	Z:-------------	7	AuxX
7	že	že	J,-------------	5	AuxC
8	konference	konference	NNFS1-----A----	10	Sb
9	nic	nic	PW--4----------	10	Obj
10	nevyřeší	vyřešit_:W	VB-S---3P-NA---	7	Obj
11	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	4	AuxG
2	To	ten	PDNS1----------	4	Sb
3	by	být	Vc-------------	4	AuxV
4	byly	být	VpTP---XR-AA---	14	Pred
5	prostitutky	prostitutka	NNFP1-----A----	14	Sb
6	v	v-1	RR--6----------	5	AuxP
7	zaměstnaneckém	zaměstnanecký	AAIS6----1A----	8	Atr
8	poměru	poměr_^(vztah_mezi_2_věcmi/lidmi)	NNIS6-----A----	6	Atr
9	?	?	Z:-------------	8	AuxG
10	Měly	mít	VpTP---XR-AA---	14	Pred
11	stanovenou	stanovený_^(určit)_(*3it)	AAFS4----1A----	13	Atr
12	pracovní	pracovní	AAFS4----1A----	13	Atr
13	dobu	doba	NNFS4-----A----	10	Obj
14	a	a-1	J^-------------	0	Coord
15	dostávaly	dostávat_:T_^(*4at)	VpTP---XR-AA---	14	Pred
16	stravenky	stravenka	NNFP1-----A----	15	Sb
17	?	?	Z:-------------	14	AuxG
18	Je	být	VB-S---3P-AA---	20	AuxV
19	nesmysl	nesmysl	NNIS1-----A----	18	Sb
20	dělat	dělat_:T	Vf--------A----	15	Obj
21	z	z-1	RR--2----------	20	AuxP
22	prostituce	prostituce	NNFS2-----A----	21	Adv
23	živnost	živnost_^(*3ý)	NNFS1-----A----	22	Atr
24	.	.	Z:-------------	0	AuxK

1	To	ten	PDNS1----------	2	Sb
2	je	být	VB-S---3P-AA---	16	Obj
3	podobné	podobný	AANS1----1A----	2	Pnom
4	,	,	Z:-------------	5	AuxX
5	jako	jako	J,-------------	3	AuxC
6	dělat	dělat_:T	Vf--------A----	5	ExD
7	živnost	živnost_^(*3ý)	NNFS4-----A----	6	Obj
8	z	z-1	RR--2----------	7	AuxP
9	dealerů	dealer	NNMP2-----A----	8	Atr
10	drog	droga	NNFP2-----A----	11	Atr
11	či	či	J^-------------	9	Coord
12	zlodějů	zloděj	NNMP2-----A----	11	Atr
13	autorádií	autorádio	NNNP2-----A----	12	Atr
14	,	,	Z:-------------	2	AuxX
15	"	"	Z:-------------	9	AuxG
16	prohlásil	prohlásit_:W	VpYS---XR-AA---	0	Pred
17	.	.	Z:-------------	0	AuxK

1	Podle	podle-2	RR--2----------	3	AuxP
2	Kubery	Kubera_;S	NNMS2-----A----	1	Adv
3	existuje	existovat_:T	VB-S---3P-AA---	0	Pred
4	jiné	jiný	AANS1----1A----	5	Atr
5	řešení	řešení_^(*3it)	NNNS1-----A----	3	Sb
6	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	3	AuxG
2	Dámy	dáma	NNFS2-----A----	3	Obj
3	zaplatí	zaplatit_:W	VB-S---3P-AA---	0	Pred
4	správní	správní_^(např._poplatek;_rada;_řád;...)	AAIS1----1A----	5	Atr
5	poplatek	poplatek	NNIS1-----A----	3	Sb
6	,	,	Z:-------------	10	AuxX
7	který	který	P4YS1----------	10	Sb
8	by	být	Vc-------------	10	AuxV
9	se	se_^(zvr._zájmeno/částice)	P7-X4----------	10	AuxT
10	pohyboval	pohybovat_:T	VpYS---XR-AA---	5	Atr
11	od	od-1	RR--2----------	10	AuxP
12	padesáti	padesát`50	Cn-P2----------	11	Adv
13	do	do-1	RR--2----------	10	AuxP
14	sta	sto-2`100	NNNS2-----A----	13	Adv
15	tisíc	tisíc-1`1000	ClXS2----------	14	Atr
16	korun	koruna	NNFP2-----A----	15	Atr
17	,	,	Z:-------------	18	AuxX
18	podle	podle-2	RR--2----------	10	AuxP
19	propočtu	propočet	NNIS2-----A----	18	Adv
20	jejich	jeho_^(přivlast.)	PSXXXXP3-------	21	Atr
21	tržeb	tržba	NNFP2-----A----	19	Atr
22	.	.	Z:-------------	0	AuxK

1	Představa	představa	NNFS1-----A----	9	Sb
2	,	,	Z:-------------	3	AuxX
3	že	že	J,-------------	1	AuxC
4	by	být	Vc-------------	6	AuxV
5	prostitutky	prostitutka	NNFP1-----A----	6	Obj
6	platily	platit_:T_:W	VpTP---XR-AA---	3	Obj
7	daně	daň_^(peněžní/naturální_dávka)	NNFP1-----A----	6	Obj
8	,	,	Z:-------------	3	AuxX
9	je	být	VB-S---3P-AA---	0	Pred
10	totiž	totiž	Db-------------	9	AuxY
11	naivní	naivní	AAFP1----1A----	9	Pnom
12	.	.	Z:-------------	0	AuxK

1	Tvrdily	tvrdit_:T	VpTP---XR-AA---	0	Pred
2	by	být	Vc-------------	1	AuxV
3	,	,	Z:-------------	4	AuxX
4	že	že	J,-------------	1	AuxC
5	vlastně	vlastně-2_^(totiž)	Db-------------	8	AuxY
6	žádnou	žádný	PWFS4----------	7	Atr
7	činnost	činnost_^(*3ý)	NNFS4-----A----	8	Obj
8	nevykonávaly	vykonávat_:T_^(*4at)	VpTP---XR-NA---	4	Obj
9	.	.	Z:-------------	0	AuxK

1	Správní	správní_^(např._poplatek;_rada;_řád;...)	AAIS1----1A----	2	Atr
2	poplatek	poplatek	NNIS1-----A----	5	Sb
3	by	být	Vc-------------	5	AuxV
4	však	však	J^-------------	0	Coord
5	musely	muset	VpTP---XR-AA---	4	Pred
6	platit	platit_:T_:W	Vf--------A----	5	Obj
7	předem	předem	Db-------------	6	Adv
8	,	,	Z:-------------	9	AuxX
9	takže	takže	J,-------------	5	AuxC
10	by	být	Vc-------------	12	AuxV
11	to	ten	PDNS1----------	12	Sb
12	fungovalo	fungovat_:T	VpNS---XR-AA---	9	Adv
13	jako	jako	J,-------------	14	AuxY
14	licence	licence	NNFS1-----A----	12	AtvV
15	.	.	Z:-------------	0	AuxK

1	Její	jeho_^(přivlast.)	PSFSXFS3-------	2	Atr
2	součástí	součást	NNFS7-----A----	4	Pnom
3	by	být	Vc-------------	4	AuxV
4	byla	být	VpQW---XR-AA---	13	Obj
5	i	i-1	J^-------------	6	AuxZ
6	povinnost	povinnost_^(*3ý)	NNFS4-----A----	7	Obj
7	podrobit	podrobit_:W	Vf--------A----	4	Sb
8	se	se_^(zvr._zájmeno/částice)	P7-X4----------	7	AuxT
9	lékařským	lékařský	AAFP3----1A----	10	Atr
10	prohlídkám	prohlídka	NNFP3-----A----	7	Obj
11	,	,	Z:-------------	6	AuxX
12	"	"	Z:-------------	4	AuxG
13	řekl	říci_:W	VpYS---XR-AA---	0	Pred
14	.	.	Z:-------------	0	AuxK

1	Kubera	Kubera_;S	NNMS1-----A----	5	Sb
2	si	se_^(zvr._zájmeno/částice)	P7-X3----------	5	AuxT
3	však	však	J^-------------	0	Coord
4	sám	sám_^(samotný)	PLYS1----------	1	Atv
5	uvědomuje	uvědomovat_:T	VB-S---3P-AA---	3	Pred
6	,	,	Z:-------------	7	AuxX
7	že	že	J,-------------	5	AuxC
8	by	být	Vc-------------	14	AuxV
9	jeho	jeho_^(přivlast.)	PSXXXZS3-------	10	Atr
10	návrh	návrh	NNIS1-----A----	16	Obj
11	v	v-1	RR--6----------	10	AuxP
12	současné	současný	AAFS6----1A----	13	Atr
13	době	doba	NNFS6-----A----	11	Adv
14	nebylo	být	VpNS---XR-NA---	7	Obj
15	možné	možný	AANS1----1A----	14	Pnom
16	prosadit	prosadit_:W	Vf--------A----	14	Sb
17	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	3	AuxG
2	Překážkou	překážka	NNFS7-----A----	3	Pnom
3	je	být	VB-S---3P-AA---	0	Pred
4	úmluva	úmluva	NNFS1-----A----	3	Sb
5	o	o-1	RR--6----------	4	AuxP
6	obchodu	obchod	NNIS6-----A---1	5	Atr
7	se	s-1	RV--7----------	6	AuxP
8	ženami	žena	NNFP7-----A----	7	Atr
9	,	,	Z:-------------	11	AuxX
10	kterou	který	P4FS4----------	11	Obj
11	podepsalo	podepsat	VpNS---XR-AA---	8	Atr
12	bývalé	bývalý	AANS1----1A----	13	Atr
13	Československo	Československo_;G	NNNS1-----A----	11	Sb
14	.	.	Z:-------------	0	AuxK

1	Tu	tady	Db------------1	3	Adv
2	by	být	Vc-------------	3	AuxV
3	bylo	být	VpNS---XR-AA---	0	Pred
4	nutné	nutný	AANS1----1A----	3	Pnom
5	vypovědět	vypovědět	Vf--------A----	3	Sb
6	,	,	Z:-------------	7	AuxX
7	protože	protože	J,-------------	3	AuxC
8	zmíněné	zmíněný_^(*3it)	AAFP1----1A----	9	Atr
9	licence	licence	NNFP1-----A----	10	Sb
10	zakazuje	zakazovat_:T	VB-S---3P-AA---	7	Adv
11	,	,	Z:-------------	10	AuxX
12	"	"	Z:-------------	3	AuxG
13	dodal	dodat_:W	VpYS---XR-AA---	3	Pred
14	.	.	Z:-------------	0	AuxK

1	Lidé	člověk	NNMP1-----A---1	9	Sb
2	v	v-1	RR--6----------	1	AuxP
3	Dubí	Dubí_;G	NNNS6-----A----	2	Atr
4	už	už	Db-------------	9	Adv
5	si	se_^(zvr._zájmeno/částice)	P7-X3----------	9	AuxO
6	na	na-1	RR--4----------	9	AuxP
7	prostitutky	prostitutka	NNFP4-----A----	6	Adv
8	většinou	většinou	Db-------------	9	Adv
9	zvykli	zvyknout_:W	VpMP---XR-AA--1	0	Pred
10	.	.	Z:-------------	0	AuxK

1	Problémem	problém	NNIS7-----A----	2	Pnom
2	je	být	VB-S---3P-AA---	0	Pred
3	pro	pro-1	RR--4----------	2	AuxP
4	ně	on-1	P5XP4--3-------	3	Adv
5	hlavně	hlavně_^(*1í)	Dg-------1A----	6	AuxZ
6	kriminalita	kriminalita	NNFS1-----A----	2	Sb
7	,	,	Z:-------------	11	AuxX
8	která	který	P4FS1----------	11	Sb
9	s	s-1	RR--7----------	11	AuxP
10	prostitucí	prostituce	NNFS7-----A----	9	Adv
11	souvisí	souviset_:T	VB-S---3P-AA---	6	Atr
12	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	11	AuxG
2	Průzkum	průzkum	NNIS1-----A----	11	Sb
3	,	,	Z:-------------	9	AuxX
4	co	co-1	PQ--4----------	9	Obj
5	lidem	člověk	NNMP3-----A----	9	Obj
6	v	v-1	RR--6----------	9	AuxP
7	Dubí	Dubí_;G	NNNS6-----A----	6	Atr
8	nejvíce	hodně	Dg-------3A----	9	Adv
9	vadí	vadit_:T	VB-S---3P-AA---	18	Pred
10	,	,	Z:-------------	9	AuxX
11	postavil	postavit_:W	VpYS---XR-AA---	0	Pred
12	prostituci	prostituce	NNFS4-----A----	11	Obj
13	až	až-3_^(až_k_...,_až_dost)	TT-------------	16	AuxZ
14	na	na-1	RR--4----------	11	AuxP
15	desáté	desátý	CrNS4----------	16	Atr
16	místo	místo-1_^(fyzické_umístění)	NNNS4-----A----	14	Adv
17	,	,	Z:-------------	18	AuxX
18	ale	ale	J^-------------	11	Coord
19	na	na-1	RR--6----------	23	AuxP
20	prvních	první	CrNP6----------	21	Atr
21	místech	místo-1_^(fyzické_umístění)	NNNP6-----A----	19	Adv
22	se	se_^(zvr._zájmeno/částice)	P7-X4----------	23	AuxT
23	objevila	objevit_:W	VpQW---XR-AA---	18	Pred
24	kriminalita	kriminalita	NNFS1-----A----	23	Sb
25	,	,	Z:-------------	27	AuxX
26	kterou	který	P4FS4----------	27	Obj
27	mají	mít	VB-P---3P-AA---	24	Atr
28	na	na-1	RR--6----------	27	AuxP
29	svědomí	svědomí	NNNS6-----A----	28	Obj
30	právě	právě	Db-------------	31	AuxZ
31	pasáci	pasák	NNMP1-----A----	27	Sb
32	.	.	Z:-------------	0	AuxK

1	Je	být	VB-S---3P-AA---	0	Pred
2	nutné	nutný	AANS1----1A----	1	Pnom
3	dostat	dostat	Vf--------A----	1	Sb
4	prostituci	prostituce	NNFS4-----A----	3	Obj
5	do	do-1	RR--2----------	3	AuxP
6	domů	domů	Db-------------	5	Adv
7	.	.	Z:-------------	0	AuxK

1	Co	co-1	PQ--1----------	4	Sb
2	by	být	Vc-------------	4	AuxV
3	se	se_^(zvr._zájmeno/částice)	P7-X4----------	4	AuxT
4	dělo	dělo	NNNS1-----A----	10	Sb
5	mimo	mimo-1	RR--4----------	4	AuxP
6	,	,	Z:-------------	5	AuxX
7	by	být	Vc-------------	8	AuxV
8	bylo	být	VpNS---XR-AA---	10	Pred
9	nezákonné	zákonný	AANS1----1N----	8	Pnom
10	a	a-1	J^-------------	23	Coord
11	bylo	být	VpNS---XR-AA---	10	Pred
12	by	být	Vc-------------	11	AuxV
13	na	na-1	RR--6----------	11	AuxP
14	policii	policie	NNFS6-----A----	13	Adv
15	,	,	Z:-------------	20	AuxX
16	jak	jak-3	Db-------------	20	Adv
17	si	se_^(zvr._zájmeno/částice)	P7-X3----------	20	AuxT
18	s	s-1	RR--7----------	20	AuxP
19	tím	ten	PDZS7----------	18	Obj
20	poradí	poradit_:T_:W	VB-S---3P-AA---	23	Obj
21	,	,	Z:-------------	20	AuxX
22	"	"	Z:-------------	11	AuxG
23	řekl	říci_:W	VpYS---XR-AA---	0	Pred
24	ředitel	ředitel	NNMS1-----A----	29	Atr
25	dubské	dubský	AAFS2----1A----	27	Atr
26	městské	městský	AAFS2----1A----	27	Atr
27	policie	policie	NNFS2-----A----	24	Atr
28	Jan	Jan_;Y	NNMS1-----A----	29	Atr
29	Ryska	ryska	NNFS1-----A----	23	Sb
30	.	.	Z:-------------	0	AuxK

1	S	s-1	RR--7----------	4	AuxP
2	hrozivými	hrozivý	AAIP7----1A----	3	Atr
3	údaji	údaj	NNIP7-----A----	1	Adv
4	přišla	přijít	VpQW---XR-AA---	0	Pred
5	ředitelka	ředitelka_^(*2)	NNFS1-----A----	4	Sb
6	Výchovného	výchovný	AAIS2----1A----	7	Atr
7	ústavu	ústav	NNIS2-----A----	5	Atr
8	pro	pro-1	RR--4----------	7	AuxP
9	děti	dítě	NNFP4-----A----	10	Atr
10	a	a-1	J^-------------	8	Coord
11	mládež	mládež	NNFS4-----A----	10	Atr
12	v	v-1	RR--6----------	7	AuxP
13	Kostomlatech	Kostomlaty_;G	NNIP6-----A----	12	Atr
14	pod	pod-1	RR--7----------	13	AuxP
15	Milešovkou	Milešovka	NNFS7-----A----	14	Adv
16	Milena	Milena_;Y	NNFS1-----A----	17	Atr
17	Mitterwaldová	Mitterwald	NNFS1-----A----	15	Atr
18	.	.	Z:-------------	0	AuxK

1	Informace	informace	NNFP1-----A----	2	Sb
2	označuje	označovat_:T	VB-S---3P-AA---	6	Pred
3	za	za-1	RR--4----------	2	AuxP
4	neoficiální	oficiální	AAFS4----1N----	3	Obj
5	,	,	Z:-------------	6	AuxX
6	ale	ale	J^-------------	0	Coord
7	zřejmě	zřejmě_^(*1ý)	Dg-------1A----	10	AuxY
8	se	se_^(zvr._zájmeno/částice)	P7-X4----------	10	AuxT
9	příliš	příliš	Db-------------	10	Adv
10	neliší	lišit_:T	VB-S---3P-NA---	6	Pred
11	od	od-1	RR--2----------	10	AuxP
12	skutečnosti	skutečnost_^(*3ý)	NNFS2-----A----	11	Adv
13	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	3	AuxG
2	Dívky	dívka	NNFP1-----A----	3	Sb
3	začínají	začínat_:T	VB-P---3P-AA---	0	Pred
4	pohlavně	pohlavně_^(*1í)	Dg-------1A----	5	Adv
5	žít	žít	Vf--------A----	3	Obj
6	před	před-1	RR--7----------	3	AuxP
7	čtrnáctým	čtrnáctý	CrIS7----------	8	Atr
8	rokem	rok	NNIS7-----A----	6	Adv
9	věku	věk	NNIS2-----A----	8	Atr
10	.	.	Z:-------------	0	AuxK

1	Osm	osm`8	Cn-S1----------	3	Obj
2	děvčat	děvče	NNNP2-----A----	1	Atr
3	znásilnil	znásilnit_:W	VpYS---XR-AA---	0	Pred
4	otec	otec	NNMS1-----A----	7	Sb
5	,	,	Z:-------------	7	AuxX
6	děda	děda	NNMS1-----A----	7	Sb
7	či	či	J^-------------	3	Coord
8	strýc	strýc	NNMS1-----A----	7	Sb
9	,	,	Z:-------------	10	AuxX
10	když	když	J,-------------	3	AuxC
11	byly	být	VpTP---XR-AA---	10	Adv
12	pět	pět-1`5	Cn-S1----------	15	Adv
13	,	,	Z:-------------	15	AuxX
14	osm	osm`8	Cn-S1----------	15	Obj
15	a	a-1	J^-------------	11	Coord
16	deset	deset`10	Cn-S1----------	15	Obj
17	let	rok	NNNP2-----A----	15	Atr
18	staré	stará-1_^(manželka)	NNFS2-----A----	17	Atr
19	.	.	Z:-------------	0	AuxK

1	Většina	většina	NNFS1-----A----	3	Sb
2	pak	pak	Db-------------	3	Adv
3	provozuje	provozovat_:T	VB-S---3P-AA---	0	Pred
4	prostituci	prostituce	NNFS4-----A----	3	Obj
5	bez	bez-1	RR--2----------	3	AuxP
6	přinucení	přinucení_^(*4tit)	NNNS2-----A----	5	Adv
7	.	.	Z:-------------	0	AuxK

1	Všechna	všechen	PLNP1----------	2	Atr
2	děvčata	děvče	NNNP1-----A----	3	Sb
3	berou	brát	VB-P---3P-AA---	7	Obj
4	drogy	droga	NNFP1-----A----	3	Obj
5	,	,	Z:-------------	3	AuxX
6	"	"	Z:-------------	3	AuxG
7	uvedla	uvést	VpQW---XR-AA---	0	Pred
8	ředitelka	ředitelka_^(*2)	NNFS1-----A----	7	Sb
9	ústavu	ústav	NNIS2-----A----	8	Atr
10	.	.	Z:-------------	0	AuxK

1	Vedení	vedení	NNNS1-----A----	3	Sb
2	města	město	NNNS2-----A----	1	Atr
3	věří	věřit_:T	VB-S---3P-AA---	0	Pred
4	,	,	Z:-------------	5	AuxX
5	že	že	J,-------------	3	AuxC
6	se	se_^(zvr._zájmeno/částice)	P7-X4----------	8	AuxT
7	zákonodárce	zákonodárce	NNMS1-----A----	8	Sb
8	podaří	podařit_:W	VB-S---3P-AA---	5	Obj
9	o	o-1	RR--6----------	14	AuxP
10	potřebě	potřeba	NNFS6-----A----	9	Obj
11	zákonů	zákon	NNIP2-----A----	10	Atr
12	o	o-1	RR--6----------	11	AuxP
13	prostituci	prostituce	NNFS6-----A----	12	Atr
14	přesvědčit	přesvědčit_:W	Vf--------A----	8	Obj
15	.	.	Z:-------------	0	AuxK

1	"	"	Z:-------------	11	AuxG
2	Prostituci	prostituce	NNFS4-----A----	3	Sb
3	musí	muset	VB-S---3P-AA---	11	Pred
4	upravovat	upravovat_:T	Vf--------A----	3	Obj
5	zákony	zákon	NNIP4-----A----	4	Obj
6	,	,	Z:-------------	9	AuxX
7	což	což-1	PE--1----------	9	Sb
8	se	se_^(zvr._zájmeno/částice)	P7-X4----------	9	AuxT
9	neděje	dít_:T	VB-S---3P-NA---	5	Atr
10	,	,	Z:-------------	11	AuxX
11	a	a-1	J^-------------	0	Coord
12	my	já	PP-P1--1-------	16	Sb
13	vlastními	vlastní-1_^(příslušný_k_něčemu)	AAFP7----1A----	14	Atr
14	vyhláškami	vyhláška	NNFP7-----A----	16	Obj
15	nic	nic	PW--4----------	16	Obj
16	nevyřešíme	vyřešit_:W	VB-P---1P-NA---	11	Pred
17	.	.	Z:-------------	0	AuxK

1	Stát	stát-1_^(státní_útvar)	NNIS1-----A----	4	Sb
2	se	se_^(zvr._zájmeno/částice)	P7-X4----------	4	AuxT
3	stále	stále_^(*1ý)	Db-------------	4	Adv
4	tváří	tvářet_:T	VB-S---3P-AA---	0	Pred
5	,	,	Z:-------------	6	AuxX
6	jako	jako	J,-------------	4	AuxC
7	by	být	Vc-------------	10	AuxV
8	tento	tento	PDYS1----------	9	Atr
9	problém	problém	NNIS1-----A----	10	Sb
10	neexistoval	existovat_:T	VpYS---XR-NA---	6	Adv
11	,	,	Z:-------------	6	AuxX
12	"	"	Z:-------------	10	AuxG
13	prohlásila	prohlásit_:W	VpQW---XR-AA---	4	Pred
14	starostka	starostka_^(^FM*2a)	NNFS1-----A----	17	Atr
15	Dubí	Dubí_;G	NNNS1-----A----	17	Atr
16	Jutta	Jutta	NNMS1-----A----	17	Atr
17	Kučerová	Kučerová_;S	NNFS1-----A----	13	Sb
18	.	.	Z:-------------	0	AuxK

1	Foto	foto	NNNS1-----A----	0	ExD
2	:	:	Z:-------------	6	AuxG
3	Zatímco	zatímco	J,-------------	15	AuxC
4	se	se_^(zvr._zájmeno/částice)	P7-X4----------	6	AuxT
5	politici	politik	NNMP1-----A----	6	Sb
6	bavili	bavit_:T	VpMP---XR-AA---	3	Adv
7	o	o-1	RR--4----------	6	AuxP
8	prostituci	prostituce	NNFS4-----A----	7	Obj
9	,	,	Z:-------------	3	AuxX
10	ty	ten	PDFP1----------	18	Obj
11	,	,	Z:-------------	15	AuxX
12	kterých	který	P4XP2----------	15	Obj
13	se	se_^(zvr._zájmeno/částice)	P7-X4----------	15	AuxT
14	konference	konference	NNFS1-----A----	15	Sb
15	týkala	týkat_:T	VpQW---XR-AA---	10	Atr
16	nejvíc	hodně	Dg-------3A---1	15	Obj
17	,	,	Z:-------------	3	AuxX
18	pracovaly	pracovat_:T	VpTP---XR-AA---	1	Pred
19	FOTO	foto	NNNS1-----A----	20	Sb
20	:	:	Z:-------------	18	Apos
21	MAFA	Mafa_;K	NNFS1-----A----	22	ExD
22	-	-	Z:-------------	18	Apos
23	MARTIN	Martin-1_;Y	NNMS1-----A----	24	Atr
24	ADAMEC	Adamec_;S	NNMS1-----A----	22	ExD

</TEXT>
</DOC>
